export const SECTION_RECEIVE = 'SECTION_RECEIVE';
export const SECTION_REQUEST = 'SECTION_REQUEST';
export const SECTION_REQUEST_SUCCESS = 'SECTION_REQUEST_SUCCESS';
export const SECTION_REQUEST_FAILURE = 'SECTION_REQUEST_FAILURE';
export const SECTIONS_RECEIVE = 'SECTIONS_RECEIVE';
export const SECTIONS_REQUEST = 'SECTIONS_REQUEST';
export const SECTIONS_REQUEST_SUCCESS = 'SECTIONS_REQUEST_SUCCESS';
export const SECTIONS_REQUEST_FAILURE = 'SECTIONS_REQUEST_FAILURE';

export const PAGE_RECEIVE = 'PAGE_RECEIVE';
export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_REQUEST_SUCCESS = 'PAGE_REQUEST_SUCCESS';
export const PAGE_REQUEST_FAILURE = 'PAGE_REQUEST_FAILURE';

export const PLUGIN_RECEIVE = 'PLUGIN_RECEIVE';
export const PLUGIN_REQUEST = 'PLUGIN_REQUEST';
export const PLUGIN_REQUEST_SUCCESS = 'PLUGIN_REQUEST_SUCCESS';
export const PLUGIN_REQUEST_FAILURE = 'PLUGIN_REQUEST_FAILURE';
export const PLUGINS_RECEIVE = 'PLUGINS_RECEIVE';
export const PLUGINS_REQUEST = 'PLUGINS_REQUEST';
export const PLUGINS_REQUEST_SUCCESS = 'PLUGINS_REQUEST_SUCCESS';
export const PLUGINS_REQUEST_FAILURE = 'PLUGINS_REQUEST_FAILURE';

export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAILURE = 'SEARCH_REQUEST_FAILURE';

export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE';

export const GET_FAVORITES     = 'GET_FAVORITES';
export const FAVORITE_PLUGIN   = 'FAVORITE_PLUGIN';
export const UNFAVORITE_PLUGIN = 'UNFAVORITE_PLUGIN';
