<?php

class WP_34_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'jenmylo'     => array( 'Jen Mylo',       'User Experience Lead'    ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Core Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'nacin'       => array( 'Andrew Nacin',      'Core Developer'  ),
					'dd32'        => array( 'Dion Hulse',        'Core Developer'  ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer'  ),
					'duck_'       => array( 'Jon Cave',          'Guest Committer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'scribu'         => 'Cristi Burc&#259;',
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
					'helen'          => 'Helen Hou-Sandi',
					'aaroncampbell'  => 'Aaron D. Campbell',
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'maxcutler'       => 'Max Cutler',
					'kurtpayne'       => 'Kurt Payne',
					'markoheijnen'    => 'Marko Heijnen',
					'sabreuse'        => 'Amy Hendrix',
					'georgestephanis' => 'George Stephanis',
					'sushkov'         => 'Stas Su&#537;kov',
				),
			),
		);
		return $groups;
	}

	// As of [20948], 3.4-RC1.
	function props() {
		return array(
			'082net',
			'BenChapman',
			'Caspie',
			'CoenJacobs',
			'Cyapow',
			'DH-Shredder',
			'DrewAPicture',
			'GaryJ',
			'GautamGupta',
			'Ipstenu',
			'Japh',
			'JarretC',
			'Jayjdk',
			'Lardjo',
			'Latz',
			'Mamaduka',
			'master-jake', // "Master Jake"
			'MattyRob',
			'Namely',
			'Nao',
			'Otto42',
			'PeteMall',
			'Rarst',
			'SergeyBiryukov',
			'TobiasBg',
			'TomAuger',
			'Utkarsh',
			'Viper007Bond',
			'aaroncampbell',
			'ajacommerce',
			'akshayagarwal',
			'aldenta',
			'alex-ye',
			'alexkingorg',
			'ampt',
			'andrea_r',
			'andrewryno',
			'andy',
			'arena',
			'arieputranto',
			'bananastalktome',
			'barry',
			'batmoo',
			'benbalter',
			'billerickson',
			'boonebgorges',
			'c3mdigital',
			'camiloclc',
			'casben79',
			'ceefour',
			'cheald',
			'chellycat',
			'chexee',
			'chipbennett',
			'convissor',
			'danielbachhuber',
			'daniloercoli',
			'deltafactory',
			'demetris',
			'devesine',
			'dgwyer',
			'dimadin',
			'djcp',
			'dllh',
			'dougwrites',
			'ebababi',
			'edward-mindreantre', // "edward mindreantre"
			'ejdanderson',
			'emhr',
			'empireoflight',
			'ericlewis',
			'ericmann',
			'evansolomon',
			'filosofo',
			'fredwu',
			'garyc40',
			'georgestephanis',
			'greuben',
			'griffinjt',
			'hearvox',
			'helenyhou',
			'hugobaeta', // props missed by committer in [20138]
			'husobj',
			'iammattthomas',
			'iandstewart',
			'insertvisionhere',
			'intoxstudio',
			'jaquers',
			'jeremyclarke',
			'jeremyfelt',
			'jiehanzheng',
			'jkudish',
			'johnbillion',
			'johnjamesjacoby',
			'joostdevalk',
			'josephscott',
			'justindgivens',
			'kawauso',
			'kenan3008',
			'klagraff',
			'kobenland',
			'koke',
			'kovshenin',
			'kurtpayne',
			'lancewillett',
			'leewillis77',
			'linuxologos',
			'markauk',
			'markoheijnen',
			'mattonomics',
			'mattwiebe',
			'matveb',
			'maxcutler',
			'mdawaffe',
			'merty',
			'mfields',
			'mgolawala',
			'mikeschinkel',
			'mitchoyoshitaka',
			'mrtorrent',
			'netweblogic',
			'niallkennedy',
			'nikolayyordanov', // "nikolay.yordanov"
			'norocketsurgeon',
			'npetetin',
			'nprasath002',
			'nunomorgadinho',
			'ocean90',
			'ocollet',
			'ounziw',
			'pavelevap',
			'pbiron',
			'pishmishy',
			'prettyboymp',
			'ptahdunbar',
			'pw201',
			'ramiy',
			'redsweater',
			'rmccue',
			'roscius',
			'rosshanney',
			'russellwwest',
			'ryanduff',
			'sabreuse',
			'scott-gonzalez', // "scott.gonzalez"
			'scribu',
			'settle',
			'simonwheatley',
			'sirzooro',
			'sivel',
			'skithund',
			'sksmatt',
			'solarissmoke',
			'sorich87',
			'soulseekah',
			'stephdau',
			'sushkov',
			'tamlyn',
			'tenpura',
			'thezman84',
			'tollmanz',
			'toppa',
			'tott',
			'transom',
			'trepmal',
			'tw2113',
			'vanillalounge',
			'webord',
			'wojtekszkutnik',
			'wonderslug',
			'xibe',
			'xknown',
			'yoavf',
			'zeo',
			'zx2c4',
		);
	}

	function external_libraries() {
		return array(
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
		);
	}

}
