<?php

class WP_35_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Core Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'dd32'        => array( 'Dion Hulse',        'Core Developer'  ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer'  ),
					'duck_'       => array( 'Jon Cave',          'Guest Committer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'scribu'         => 'Cristi Burc&#259;',
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
					'helen'          => 'Helen Hou-Sandi',
					'lancewillett'  => 'Lance Willett',
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'lessbloat'      => 'Dave Martin',
					'obenland'       => 'Konstantin Obenland',
					'DH-Shredder'    => 'Mike Schroder',
					'drewstrojny'    => 'Drew Strojny',
					'wonderboymusic' => array( 'Scott Taylor', '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'mattwiebe'      => 'Matt Wiebe',
				),
			),
		);
		return $groups;
	}

	// As of final release, r23123
	function props() {
		return array(
			'aaroncampbell',
			'aaronholbrook', // props missed by committer
			'alecrust',
			'alex-ye',
			'alexkingorg',
			'alexvorn2',
			'alyssonweb',
			'ampt',
			'andrear', // andrea.r
			'andrewryno',
			'andrewspittle',
			'andy',
			'apokalyptik',
			'azaozz',
			'bainternet',
			'bananastalktome',
			'barrykooij',
			'batmoo',
			'barry',
			'bbrooks', // given props as 'Ben Brooks'
			'benkulbertis',
			'bergius',
			'betzster',
			'bigdawggi',
			'bolo1988',
			'bpetty',
			'bradparbs',
			'bradthomas127',
			'bradyvercher',
			'brandondove',
			'BrianLayman',
			'c3mdigital',
			'cannona',
			'casben79',
			'Caspie',
			'cdog',
			'cfinke',
			'chellycat',
			'chexee',
			'Chouby',
			'chriswallace',
			'coffee2code',
			'corvannoorloos',
			'dan-rivera', // Dan Rivera
			'dd32',
			'deltafactory',
			'DH-Shredder',
			'dimadin',
			'djzone',
			'dllh',
			'doublesharp',
			'DrewAPicture',
			'drewstrojny',
			'duck_',
			'eddiemoya',
			'elyobo',
			'emiluzelac',
			'empireoflight',
			'ericlewis',
			'ericmann',
			'ericwahlforss',
			'ethitter',
			'evansolomon',
			'f-j-kaiser', // F J Kaiser
			'fadingdust',
			'foxinni',
			'gandham',
			'GaryJ', // given props as Gary-J
			'garyc40',
			'GeertDD',
			'georgestephanis',
			'GhostToast',
			'gluten',
			'gnarf',
			'goldenapples',
			'greenshady',
			'GregLone',
			'griffinjt',
			'hakre',
			'hanni',
			'hardy101',
			'hd-J',
			'hebbet',
			'helenyhou',
			'hugobaeta',
			'husobj',
			'iamfriendly',
			'iammattthomas',
			'iamtakashi',
			'iandstewart',
			'ikailo',
			'Ipstenu',
			'itworx',
			'j-idris',
			'jakemgold',
			'jakubtyrcha', // jakub.tyrcha
			'jamescollins',
			'jammitch',
			'jenmylo',
			'Japh',
			'JarretC',
			'javert03',
			'Jayjdk',
			'jblz',
			'jbrinley',
			'jcakec',
			'jeffsebring',
			'jeremyfelt',
			'JerrySarcastic',
			'jkudish',
			'jndetlefsen',
			'joehoyle',
			'joelhardi',
			'johnbillion',
			'johnjamesjacoby',
			'johnpbloch',
			'jond3r',
			'jondavidjohn',
			'joostdekeijzer',
			'jorbin',
			'josephscott',
			'jtsternberg',
			'JustinSainton',
			'Kawauso',
			'Keruspe',
			'kitchin',
			'klagraff',
			'knutsp',
			'koke',
			'koop',
			'kopepasah',
			'kovshenin',
			'kurtpayne',
			'Kyrylo',
			'lancewillett',
			'larysa',
			'Latz',
			'ldebrouwer',
			'leogermani',
			'lessbloat',
			'lesteph',
			'lgedeon',
			'lightningspirit',
			'linuxologos',
			'MadtownLems',
			'mailnew2ster',
			'Mamaduka',
			'maor',
			'MarcusPope',
			'markel',
			'markjaquith',
			'markoheijnen',
			'markoheinjen',
			'martythornley',
			'matt',
			'mattdanner',
			'mattwiebe',
			'MattyRob',
			'maxcutler',
			'mbijon',
			'mdawaffe',
			'mdgl',
			'melchoyce',
			'merty',
			'mfields',
			'mgdl',
			'MikeHansenMe',
			'mikelittle',
			'mikeschinkel',
			'mimecine',
			'miqrogroove',
			'mitchoyoshitaka',
			'mohanjith',
			'Moraleidame', // Moraleida.me
			'mpvanwinkle77',
			'mrroundhill',
			'mtdesign',
			'murky',
			'nacin',
			'Nao',
			'nbachiyski',
			'neoxx',
			'niallkennedy',
			'nikolov.tmw',
			'nprasath002',
			'ntm',
			'nvartolomei',
			'obenland',
			'ocean90',
			'op12no2',
			'Otto42',
			'pas5027', // props missed by committer (r22460)
			'pavelevap',
			'pdclark',
			'pento',
			'PeteMall',
			'philiparthurmoore',
			'phill_brown',
			'picklepete',
			'picklewagon',
			'PotterSys',
			'pross',
			'r-a-y',
			'ramiy',
			'rmccue',
			'rstern',
			'ryan',
			'ryanimel',
			'RyanJKoehler',
			'ryelle',
			'rzen',
			'sabreuse',
			'saltcod',
			'saracannon',
			'sc0ttclark',
			'sc0ttkclark',
			'scottgonzalez', // scott.gonzalez (props missed by committer, r22513)
			'scribu',
			'sennza',
			'senzza',
			'sergeysbetkenovgaroru', // sergey.s.betke@novgaro.ru
			'SergeyBiryukov',
			'simonwheatley',
			'sirzooro',
			'sivel',
			'sixhours',
			'solarissmoke',
			'ssamture',
			'sterlo',
			'sumindmitriy',
			'sushkov',
			'swekitsune',
			'targz-1', // tar.gz
			'taylorde',
			'thee17',
			'timbeks',
			'timfs',
			'tlovett1',
			'tmoorewp',
			'TobiasBg',
			'tollmanz',
			'TomasM',
			'TomAuger',
			'tommcfarlin',
			'toppa',
			'toscho',
			'tott',
			'trepmal',
			'usermrpapa',
			'vhauri',
			'viniciusmassuchetto',
			'Viper007Bond',
			'waclawjacek',
			'waldojaquith',
			'webord',
			'westi',
			'wet',
			'willmot',
			'wojtekszkutnik', // wojtek.szkutnik
			'wonderboymusic',
			'wpmuguru',
			'wpsmith',
			'xibe',
			'xknown',
			'yoavf',
			'yogi-t', // Yogi T
			'zamoose',
			'zeo',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery Masonry', 'http://masonry.desandro.com/' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore', 'http://underscorejs.org/' ),
		);
	}
}
