<?php

class WP_36_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'dd32'        => array( 'Dion Hulse',        'Core Developer'  ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer'  ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
					'helen'          => 'Helen Hou-Sandi',
					'aaroncampbell'  => 'Aaron D. Campbell',
					'lancewillett'   => 'Lance Willett',
					'wonderboymusic' => array( 'Scott Taylor', '0e9fc8ea22885ed718ee37d31dcffb8c' ),
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'lessbloat'       => 'Dave Martin',
					'obenland'        => 'Konstantin Obenland',
					'kovshenin'       => 'Konstantin Kovshenin',
					'Joen'            => 'Joen Asmussen',
					'DrewAPicture'    => 'Drew Jaynes',
					'adamsilverstein' => 'Adam Silverstein',
				),
			),
		);
		return $groups;
	}

	// As of final release, r23123
	function props() {
		return array(
			'aaroncampbell',
			'aaronholbrook',
			'adamsilverstein',
			'ahoereth',
			'AKTed',
			'alex-ye',
			'alexkingorg',
			'anatolbroder',
			'andrewryno',
			'andy',
			'apimlott',
			'asannad',
			'awellis13',
			'azaozz',
			'bananastalktome',
			'barry',
			'batmoo',
			'beaulebens',
			'beezeee',
			'belloswan',
			'bilalcoder',
			'bobbingwide',
			'bobbravo2',
			'bpetty',
			'bradparbs',
			'bradyvercher',
			'brianlayman',
			'c3mdigital',
			'cais',
			'carldanley',
			'Caspie',
			'celloexpressions',
			'cfinke',
			'charlestonsw',
			'cheeserolls',
			'chipbennett',
			'chmac',
			'chriswallace',
			'cochran',
			'coffee2code',
			'corvannoorloos',
			'crazycoders',
			'csixty4',
			'danielbachhuber',
			'daniloercoli',
			'dannydehaan',
			'davidwilliamson',
			'dd32',
			'desrosj',
			'devesine',
			'dfavor',
			'dh-shredder',
			'DH-Shredder',
			'dimadin',
			'dllh',
			'dovyp',
			'DrewAPicture',
			'DrewAPicture',
			'duck_',
			'dvarga',
			'elfin',
			'empireoflight',
			'ericlewis',
			'ericmann',
			'ethitter',
			'evansolomon',
			'f-j-kaiser ', #  F J Kaiser
			'faishal',
			'fanquake',
			'feedmeastraycat',
			'frank-klein ', #  Frank Klein
			'FStop',
			'garyc40',
			'GaryJ',
			'gcorne',
			'GeertDD',
			'georgestephanis',
			'gish',
			'gorgoglionemeister',
			'greuben',
			'h4ck3rm1k3',
			'hakre',
			'hbanken',
			'hebbet',
			'helen',
			'helgatheviking',
			'hirozed',
			'hurtige',
			'hypertextranch',
			'iandunn',
			'Ipstenu',
			'jakub',
			'Jayjdk',
			'jbutkus',
			'jcastaneda',
			'JDTrower',
			'jeremyfelt',
			'JerrySarcastic',
			'jkudish',
			'joehoyle',
			'joen',
		#	'John Dyer',
			'johnbillion',
			'johnjamesjacoby',
			'jonbishop',
			'jond3r',
			'jorbin',
			'jordie23',
			'josephscott',
			'jrbeilke',
			'jrf',
			'JustinSainton',
			'jvisick77',
			'kadamwhite',
			'karmatosed',
			'kawauso',
			'keoshi',
			'koop',
			'kovshenin',
			'kraftbj',
			'ktdreyer',
			'kurtpayne',
			'kwight',
			'lancewillett',
			'leewillis77',
			'lessbloat',
			'lightningspirit',
			'macbrink',
			'maor',
			'MarcusPope',
			'mark-k',
			'markjaquith',
			'markmcwilliams',
			'markoheijnen',
			'matt',
			'MatthewRuddy',
			'mattwiebe',
			'maxcutler',
			'mboynes',
			'mdawaffe',
			'melchoyce',
			'mfields',
			'mgibbs189',
			'MikeHansenMe',
			'mintindeed',
			'mitchoyoshitaka',
			'mjbanks',
			'momo360modena',
			'mordauk',
			'MZAWeb',
			'n7studios',
			'nacin',
			'najamelan',
			'nao',
			'niallkennedy',
			'nickdaugherty',
			'nickmomrick',
			'ninnypants',
			'norcross',
			'nprasath002',
			'obenland',
			'ocean90',
			'ParadisePorridge',
			'pauldewouters',
			'pavelevap',
			'pdclark',
			'PeteMall',
			'phill_brown',
			'pollett',
			'programmin',
			'r24421',
			'rachelbaker',
			'ramiy',
			'rdall',
			'redpixelstudios',
			'redsweater',
			'reidburke',
			'retlehs',
			'rlerdorf',
			'rmccue',
			'rodrigosprimo',
			'roulandf',
			'rovo89',
			'ryanduff',
			'ryanhellyer',
			'ryelle',
			'sabreuse',
			'saracannon',
			'sc0ttkclark',
			'scholesmafia',
			'scribu',
			'sergejmueller',
			'SergeyBiryukov',
			'settle',
			'sim',
			'simonwheatley',
			'siobhan',
			'sirzooro',
			'slene',
			'solarissmoke',
			'soulseekah',
			'SriniG',
			'stephenh1988',
			'storkontheroof',
			'sunnyratilal',
			'sweetie089',
			'tar',
			'taupecat',
			'technosailor',
			'tenpura',
			'TheLastCicada',
			'thomasvanderbeek',
			'tivnet',
			'tjsingleton',
			'tlovett1',
			'TobiasBg',
			'tollmanz',
			'toscho',
			'TravisHoffman',
			'trepmal',
			'tw2113',
			'uuf6429',
			'viniciusmassuchetto',
			'Viper007Bond',
			'westi',
			'wojtek',
			'wonderboymusic',
			'wpewill',
			'WraithKenny',
			'wycks',
			'xibe',
			'xknown',
			'yoavf',
			'zekeweeks',
			'zeo',
			'ziegenberg',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery Masonry', 'http://masonry.desandro.com/' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
		);
	}
}
