<?php

class WP_32_Credits extends WP_Credits {

	function groups() {
		return array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'jenmylo'     => array( 'Jen Mylo',       'User Experience Lead'    ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'extended-core-team' => array(
				'name'    => 'Extended Core Team',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'nacin'         => array( 'Andrew Nacin',      'Core Committer'       ),
					'koop'          => array( 'Daryl Koopersmith', 'Guest Committer'      ),
					'dd32'          => array( 'Dion Hulse',        'Core Committer'       ),
					'josephscott'   => array( 'Joseph Scott',      'XML-RPC'              ),
					'iammattthomas' => array( 'Matt Thomas',       'Designer'             ),
					'nbachiyski'    => array( 'Nikolay Bachiyski', 'Internationalization' ),
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'duck_'         => array( 'Jon Cave',            'Developer'     ),
					'scribu'        => array( 'Cristi Burc&#259;',   'Developer'     ),
					'ocean90'       => array( 'Dominik Schilling',   'Developer'     ),
					'iandstewart'   => array( 'Ian Stewart',         'Twenty Eleven' ),
					'lancewillett'  => array( 'Lance Willett',       'Twenty Eleven' ),
					'matveb'        => array( 'Mat&#237;as Ventura', 'Twenty Eleven' ),
					'aaroncampbell' => array( 'Aaron Campbell',      'Developer'     ),
					'EmpireOfLight' => array( 'Ben Dunkle',          'Icon Design'   ),
					'xknown'        => array( 'Alex Concha',         'Developer'     ),
				),
			),
		);
	}

	function props() {
		return array(
			'aaroncampbell',
			'aldenta',
			'ampt',
			'andrewryno',
			'andy',
			'batmoo',
			'benbalter',
			'BenChapman',
			'bi0xid',
			'blepoxp',
			'bluntelk',
			'boonebgorges',
			'brandonburke',
			'Caspie',
			'cfinke',
			'CharlesClarkson',
			'chexee',
			'cnorris23',
			'coffee2code',
			'cyberhobo',
			'daniloercoli',
			'dcowgill',
			'demetris',
			'devinreams',
			'DH-Shredder',
			'dimadin',
			'dllh',
			'dougwrites',
			'dvwallin',
			'ericmann',
			'fabifott',
			'filosofo',
			'frumph',
			'garyc40',
			'greenshady',
			'greuben',
			'guyn',
			'hakre',
			'hebbet',
			'helen',
			'hew',
			'holizz',
			'jacobwg',
			'Jayjdk',
			'JDTrower',
			'jfarthing84',
			'jkudish',
			'joelhardi',
			'johnbillion',
			'johnjamesjacoby',
			'johnonolan',
			'joostdevalk',
			'jorbin',
			'jtsternberg',
			'kawauso',
			'kevinB',
			'knutsp',
			'koke',
			'kovshenin',
			'ldebrouwer',
			'linuxologos',
			'lloydbudd',
			'marcis20',
			'markmcwilliams',
			'MattyRob',
			'mcepl',
			'mdawaffe',
			'mfields',
			'MichaelH',
			'michaeltyson',
			'mintindeed',
			'miqrogroove',
			'mitchoyoshitaka',
			'mrroundhill',
			'natecook',
			'nathanrice',
			'niallkennedy',
			'nickbohle',
			'nprasath002',
			'nuxwin',
			'Otto42',
			'pavelevap',
			'peaceablewhale',
			'PeteMall',
			'pross',
			'ptahdunbar',
			'Rahe',
			'ramiy',
			'rasheed',
			'rosshanney',
			'ryanimel',
			'saracannon',
			'SidHarrell',
			'sbressler',
			'SergeyBiryukov',
			'shakenstirred',
			'sivel',
			'solarissmoke',
			'sorich87',
			'szadok',
			'technosailor',
			'tenpura',
			'tetele',
			'tfnab',
			'tigertech',
			'trepmal',
			'Utkarsh',
			'vanillalounge',
			'valentinas',
			'webduo',
			'wpmuguru',
			'xibe',
			'xknown',
			'yoavf',
			'zeo',
			'ziofix',
		);
	}

	function external_libraries() {
		return array(
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'SWFObject', 'http://code.google.com/p/swfobject/' ),
			array( 'SWFUpload', 'http://www.swfupload.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
		);
	}

}
