<?php

class WP_39_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => array(
					'dd32'        => array( 'Dion Hulse',        'Core Developer' ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer' ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
					'helen'       => array( 'Helen Hou-Sandí',   'Core Developer' ),
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'wonderboymusic' => array( 'Scott Taylor',    '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'johnbillion'    => array( 'John Blackbourn', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'DrewAPicture'   => 'Drew Jaynes',
					'lancewillett'   => 'Lance Willett',
					'gcorne'         => 'Gregory Cornelius',
					'DH-Shredder'    => 'Mike Schroder',
				),
			),
			'recent-rockstars' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'adamsilverstein'    => 'Adam Silverstein',
					'avryl'              => 'Janneke Van Dorpe',
					'ehg'                => 'Chris Blower',
					'EmpireOfLight'      => 'Ben Dunkle',
					'ethitter'           => 'Erick Hitter',
					'jeremyfelt'         => 'Jeremy Felt',
					'jorbin'             => 'Aaron Jorbin',
					'kovshenin'          => 'Konstantin Kovshenin',
					'kpdesign'           => 'Kim Parsell',
					'matveb'             => 'Matías Ventura',
					'mcsf'               => 'Miguel Fonseca',
					'melchoyce'          => 'Mel Choyce',
					'michael-arestad'    => array( 'Michael Arestad', '46e0f1b10224bb4e832ea9633acee2b8' ),
					'obenland'           => 'Konstantin Obenland',
					'pento'              => 'Gary Pendergast',
					'shaunandrews'       => 'Shaun Andrews',
					'smashcut'           => 'Michael Pick',
					'westonruter'        => array( 'Weston Ruter', '22ed378fbf1d918ef43a45b2a1f34634' ),
				),
			),
		);
		return $groups;
	}

	// As of final release, r25914 to r26862
	function props() {
		return array(
			'_jameslee',
			'aaroncampbell',
			'adamsilverstein',
			'adelval',
			'afercia',
			'ajay',
			'akeda',
			'alex-ye',
			'aliso',
			'andy',
			'andykeith',
			'antorome',
			'atimmer',
			'aubreypwd',
			'avryl',
			'azaozz',
			'barry',
			'bassgang',
			'batmoo',
			'bcworkz',
			'bigdawggi',
			'bobbingwide',
			'bobbravo2',
			'bootsz',
			'bpetty',
			'bradparbs',
			'bradt',
			'bramd',
			'brasofilo',
			'bravokeyl',
			'c3mdigital',
			'celloexpressions',
			'cfinke',
			'cgaffga',
			'chiragswadia',
			'chouby',
			'chriseverson',
			'chrisguitarguy',
			'chrisscott',
			'ciantic',
			'cmmarslender',
			'coffee2code',
			'cojennin',
			'collinsinternet',
			'corphi',
			'corvannoorloos',
			'cramdesign',
			'danielbachhuber',
			'dannydehaan',
			'davidakennedy', // props missed by committer [27860]
			'davidanderson',
			'davidmarichal',
			'dd32',
			'denis-de-bernardy',
			'dh-shredder',
			'djpaul',
			'dougwollison',
			'dpe415',
			'drewapicture',
			'drozdz',
			'drprotocols',
			'duck_',
			'dustyf',
			'eatingrules',
			'ehg',
			'eightface',
			'ejdanderson',
			'eliorivero',
			'empireoflight',
			'enej',
			'ericlewis',
			'ericmann',
			'ethitter',
			'evarlese',
			'fahmiadib',
			'fboender',
			'frank-klein',
			'garyc40',
			'garyj',
			'gcorne',
			'genkisan',
			'georgestephanis',
			'gradyetc',
			'grahamarmfield',
			'greglone',
			'hakre',
			'hanni',
			'helen',
			'iamfriendly',
			'iammattthomas',
			'ippetkov',
			'ipstenu',
			'jackreichert',
			'janrenn',
			'janw.oostendorp',
			'jartes',
			'jaycc',
			'jayjdk',
			'jbkkd',
			'jdgrimes',
			'jeffsebring',
			'jenmylo',
			'jeremyfelt',
			'jesin',
			'jnielsendotnet',
			'joedolson',
			'joehoyle',
			'johnbillion',
			'johnjamesjacoby',
			'johnpbloch',
			'johnregan3',
			'jond3r',
			'joostdevalk',
			'jorbin',
			'joshuaabenazer',
			'jstraitiff',
			'juliobox',
			'justinsainton',
			'kadamwhite',
			'kasparsd',
			'kawauso',
			'kerikae',
			'kitchin',
			'klihelp',
			'knutsp',
			'kopepasah',
			'kovshenin',
			'kpdesign',
			'kraftbj',
			'kwight',
			'kworthington',
			'lancewillett',
			'ldebrouwer',
			'leewillis77',
			'lkwdwrd',
			'lpointet',
			'mark8barnes',
			'markjaquith',
			'markoheijnen',
			'marventus',
			'mattheu',
			'mattonomics',
			'mattyrob',
			'matveb',
			'mauryaratan',
			'maxcutler',
			'mboynes',
			'mcadwell',
			'mcsf',
			'mdbitz',
			'melchoyce',
			'meloniq',
			'michael-arestad',
			'michelwppi',
			'mikecorkum',
			'mikehansenme',
			'mikemanger',
			'mikeschinkel',
			'miqrogroove',
			'mitchoyoshitaka',
			'miyauchi',
			'mjbanks',
			'mor10',
			'mordauk',
			'morganestes',
			'nacin',
			'nao',
			'nendeb55',
			'neoxx',
			'nessworthy',
			'netweb',
			'nicolealleyinteractivecom',
			'nikv',
			'nivijah',
			'nofearinc',
			'norcross',
			'nprasath002',
			'nunomorgadinho', // props missed by committer [27184]
			'obenland',
			'ocean90',
			'olivm',
			'originalexe',
			'oso96_2000',
			'otto42',
			'ounziw',
			'patricknami',
			'paulwilde',
			'pavelevap',
			'pbearne',
			'pento',
			'philiparthurmoore',
			'piontkowski',
			'plocha',
			'prettyboymp',
			'pross',
			'raamdev',
			'rachelbaker',
			'ramonchiara',
			'rarst',
			'redsweater',
			'rhyswynne',
			'ricardocorreia',
			'richard2222',
			'rickalee',
			'rmccue',
			'robmiller',
			'rodrigosprimo',
			'romaimperator',
			'roothorick',
			'ruudjoyo',
			'ryelle',
			'sabreuse',
			'salcode',
			'sandyr',
			'sbruner',
			'scottlee',
			'scribu',
			'sdasse',
			'seanchayes',
			'sergeybiryukov',
			'shahpranaf',
			'shaunandrews',
			'shelob9',
			'shinichin',
			'simonwheatley',
			'siobhan',
			'siobhyb',
			'sirzooro',
			'solarissmoke',
			'sonjanyc',
			'soulseekah',
			'spencerfinnell',
			'spmlucas',
			'stephcook22',
			'stephenharris',
			'stevenkword',
			'tanner-m',
			'tbrams',
			'tellyworth',
			'theorboman',
			'tivnet',
			'tlovett1',
			'tobiasbg',
			'tomauger',
			'topher1kenobe',
			'topquarky',
			'toru',
			'toszcze',
			'trepmal',
			'umeshsingla',
			'undergroundnetwork',
			'vancoder',
			'vanillalounge',
			'varunagw',
			'wawco',
			'westonruter',
			'willmot',
			'wokamoto',
			'wonderboymusic',
			'wpsmith',
			'xknown',
			'xsonic',
			'yoavf',
			'yurivictor',
			'zbtirrell',
			'zodiac1978',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'Masonry', 'http://masonry.desandro.com/' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/lowe/zxcvbn' ),
		);
	}
}
