<?php

class WP_37_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'dd32'        => array( 'Dion Hulse',        'Core Developer'  ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer'  ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
					'helen'          => 'Helen Hou-Sandi',
					'wonderboymusic' => array( 'Scott Taylor',    '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'johnbillion'    => array( 'John Blackbourn', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'DrewAPicture'   => 'Drew Jaynes',
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'jeremyfelt' => 'Jeremy Felt',
					'c3mdigital' => 'Chris Olbekson',
					'kpdesign'   => 'Kim Parsell',
				),
			),
		);
		return $groups;
	}

	// As of final release, r25892.
	function props() {
		return array(
			'aaroncampbell',
			'aaronholbrook',
			'adamsilverstein',
			'aeg0125',
			'ahoereth',
			'alex-ye',
			'andg',
			'andreasnrb',
			'andrewspittle',
			'askapache',
			'atimmer',
			'azaozz',
			'bananastalktome',
			'barry',
			'beaulebens',
			'benmoody',
			'betzster',
			'bftrick',
			'bhengh',
			'bmb',
			'bpetty',
			'brianhogg',
			'buffler',
			'butuzov',
			'c3mdigital',
			'cais',
			'calin', // 3.7.1
			'carldanley',
			'celloexpressions',
			'charlesclarkson',
			'chipbennett',
			'chouby',
			'chrisbliss18', // 3.7.1
			'chrisrudzki',
			'cimmo',
			'coenjacobs',
			'coffee2code',
			'convissor',
			'creativeinfusion',
			'crrobi01',
			'csixty4',
			'daankortenbach',
			'danielbachhuber',
			'dartiss',
			'davidjlaietta',
			'dd32',
			'desroj',
			'desrosj',
			'devesine',
			'dh-shredder',
			'dimadin',
			'dllh',
			'dpash',
			'drewapicture',
			'drprotocols',
			'duck_',
			'dustyf',
			'dzver',
			'enej',
			'ericlewis',
			'ericmann',
			'evansolomon',
			'faishal',
			'faison',
			'fjarrett',
			'foofy',
			'frank-klein',
			'garyc40',
			'garyj', // 3.7.1
			'gayadesign',
			'gcorne',
			'georgestephanis',
			'gizburdt',
			'goldenapples',
			'gradyetc',
			'greuben',
			'hakre',
			'helen',
			'hotchkissconsulting',
			'iamfriendly',
			'iandunn',
			'ipstenu',
			'iworks',
			'jakubtyrcha',
			'jamescollins',
			'jayjdk',
			'jchristopher',
			'jdgrimes',
			'jenmylo',
			'jeremyfelt',
			'jkudish',
			'joehoyle',
			'johnafish',
			'johnbillion',
			'johnjamesjacoby',
			'johnnyb',
			'johnpbloch',
			'jond3r',
			'jonlynch',
			'joostdevalk',
			'jorbin',
			'josephscott',
			'justinsainton',
			'kadamwhite',
			'ketwaroo',
			'kevinb',
			'kitchin',
			'koop',
			'kovshenin',
			'kpdesign',
			'kraftbj',
			'kurtpayne',
			'lancewillett',
			'layotte',
			'leewillis77',
			'lessbloat',
			'lgedeon',
			'lucp', // 3.7.1
			'marco_teethgrinder',
			'markjaquith',
			'markmcwilliams',
			'markoheijnen',
			'melchoyce',
			'mikehansenme',
			'mikeschinkel',
			'miqrogroove',
			'mitchoyoshitaka',
			'miyauchi',
			'mordauk',
			'nacin',
			'nao',
			'naomicbush',
			'natejacobs',
			'nathanrice',
			'nbachiyski',
			'neoxx',
			'netweb',
			'niallkennedy',
			'nickdaugherty',
			'nickmomrik',
			'nikv',
			'noahsilverstein',
			'nofearinc',
			'norcross',
			'nukaga',
			'nullvariable',
			'obenland',
			'ocean90',
			'paolal',
			'pauldewouters',
			'pavelevap',
			'pbiron',
			'pento',
			'peterjaap',
			'philiparthurmoore',
			'plocha',
			'pollett',
			'pross',
			'ptahdunbar',
			'r3df',
			'ramiy',
			'rasheed',
			'raybernard',
			'rboren',
			'rdall',
			'rfair404',
			'rmccue',
			'rmmcue',
			'rodrigosprimo',
			'rpattillo',
			'ryan',
			'rzen',
			'sabreuse',
			'scottsweb',
			'scribu',
			'scruffian',
			'sergeybiryukov',
			'shinichin',
			'sillybean',
			'simonwheatley',
			'siobhan',
			'siobhyb',
			'sirzooro',
			'solarissmoke',
			'sorich87',
			'stephenharris',
			'strangerstudios',
			'sweetie089',
			'swissspidy',
			'technosailor',
			'tenpura',
			'tivnet',
			'tlovett1',
			'tmtoy',
			'tobiasbg',
			'tomauger',
			'toscho',
			'trepmal',
			'tw2113',
			'usermrpapa',
			'vericgar',
			'vinod-dalvi',
			'viper007bond',
			'webord',
			'westonruter',
			'wikicms',
			'willnorris',
			'wojtekszkutnik',
			'wonderboymusic',
			'wpmuguru',
			'wpsmith',
			'wycks',
			'xparham',
			'yoavf',
			'yurivictor',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery Masonry', 'http://masonry.desandro.com/' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/lowe/zxcvbn' ),
		);
	}
}
