<?php

class WP_33_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'jenmylo'     => array( 'Jen Mylo',       'User Experience Lead'    ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Core Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'nacin'       => array( 'Andrew Nacin',      'Core Developer'  ),
					'dd32'        => array( 'Dion Hulse',        'Core Developer'  ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer'  ),
					'duck_'       => array( 'Jon Cave',          'Guest Committer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'scribu'         => 'Cristi Burc&#259;',
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' => 'Sergey Biryukov',
				),
			),
			'recent-rockstars' => array(
				'name'    => 'Recent Rockstars',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'helen'       => 'Helen Hou-Sandi',
					'chexee'      => 'Chelsea Otakan',
					'johnbillion' => array( 'John Blackbourn', '0000ba6dd1b089e1746abbfe6281ee3b' ),
				),
			),		
		);
		return $groups;
	}

	// As of [19669], 3.3.1.
	function props() {
		return array(
			'aaroncampbell',
			'adambackstrom',
			'adeptris',
			'alexkingorg',
			'amereservant',
			'ampt',
			'AndrewFrazier',
			'andrewryno',
			'andy',
			'ansimation',
			'arena',
			'batmoo',
			'benbalter',
			'brandondove',
			'carlospaulino',
			'Caspie',
			'cebradesign',
			'cgrymala',
			'chexee',
			'chipbennett',
			'chrisbliss18',
			'CoenJacobs',
			'coffee2code',
			'cyberhobo',
			'DaMsT', // props missed by committer
			'danielbachhuber',
			'davecpage',
			'dcowgill',
			'deltafactory',
			'demetris',
			'designsimply',
			'devinreams',
			'dgwyer',
			'DH-Shredder',
			'dimadin',
			'dllh',
			'dougwrites',
			'dragoonis',
			'DrewAPicture',
			'eduplessis',
			'eightamrock',
			'ejdanderson',
			'eko-fr',
			'Elpie',
			'elyobo',
			'empireoflight',
			'ericmann',
			'ethitter',
			'evansolomon',
			'exell.christopher',
			'filosofo',
			'fonglh',
			'garyc40',
			'GaryJ',
			'georgestephanis',
			'gluten',
			'goldenapples',
			'goto10',
			'hakre',
			'helenyhou',
			'iammattthomas',
			'iandstewart',
			'Ipstenu',
			'jacobwg',
			'jakemgold',
			'jakub.tyrcha',
			'jamescollins',
			'Jayjdk',
			'jeremyclarke',
			'jgadbois',
			'Jick',
			'joehoyle',
			'johnbillion',
			'johnjamesjacoby',
			'johnonolan',
			'johnpbloch',
			'jorbin',
			'josephscott',
			'jtclarke',
			'justindgivens',
			'JustinSainton',
			'kawauso',
			'kevinB',
			'kitchin',
			'koke',
			'kovshenin',
			'kurtpayne',
			'l3rady',
			'lancewillett',
			'Latz',
			'ldebrouwer',
			'linuxologos',
			'lloydbudd',
			'logiclord',
			'lordandrei',
			'lukeschlather',
			'lumination',
			'madjax',
			'mako09',
			'MarcusPope',
			'mark-k',
			'markmcwilliams',
			'markoheijnen',
			'masonjames',
			'mattwiebe',
			'MattyRob',
			'matveb',
			'mau',
			'mbijon',
			'mdawaffe',
			'merty',
			'mfields',
			'mhauan',
			'miqrogroove',
			'mitchoyoshitaka',
			'mrtorrent',
			'Nao',
			'natebedortha',
			'nbachiyski', // commit
			'ocean90',
			'olivM',
			'olleicua',
			'otto42',
			'pagesimplify',
			'paulhastings0',
			'pavelevap',
			'PeteMall',
			'peterwilsoncc',
			'ppaire',
			'ptahdunbar',
			'r-a-y',
			'ramiy',
			'rasheed',
			'rosshanney',
			'ruslany',
			'ryanhellyer',
			'ryanimel',
			'saracannon',
			'sbressler',
			'scottbasgaard',
			'scottconnerly',
			'scribu',
			'SergeyBiryukov',
			'settle',
			'sillybean',
			'Simek',
			'simonwheatley',
			'sirzooro',
			'solarissmoke',
			'sorich87',
			'tech163',
			'tenpura',
			'tfnab',
			'TheDeadMedic',
			'tmoorewp',
			'TomAuger',
			'trepmal',
			'usermrpapa',
			'valendesigns',
			'vanillalounge',
			'vegasgeek',
			'Viper007Bond',
			'vnsavage',
			'wonderboymusic',
			'wpmuguru',
			'wpweaver',
			'WraithKenny', // props missed by committer
			'xknown',
			'yoavf',
			'yuraz',
			'zeo',
		);
	}

	function external_libraries() {
		return array(
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
		);
	}

}
