<?php

class WP_38_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'dd32'        => array( 'Dion Hulse',        'Core Developer' ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer' ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ocean90'        => 'Dominik Schilling',
					'SergeyBiryukov' =>'Sergey Biryukov',
					'helen'          => 'Helen Hou-Sandi',
					'wonderboymusic' => array( 'Scott Taylor',    '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'johnbillion'    => array( 'John Blackbourn', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'DrewAPicture'   => 'Drew Jaynes',
					'iammattthomas'  => 'Matt Thomas',
					'lancewillett'   => 'Lance Willett',
					'Otto42'         => 'Samuel Wood',
				),
			),
			'recent-rockstars' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'apeatling'          => 'Andy Peatling',
					'dbernar1'           => 'Dan Bernardic',
					'drw158'             => 'Dave Whitley',
					'EmpireOfLight'      => 'Ben Dunkle',
					'isaackeyet'         => 'Isaac Keyet',
					'Joen'               => 'Joen Asmussen',
					'kraftbj'            => 'Brandon Kraft',
					'lessbloat'          => 'Dave Martin',
					'littlethingsstudio' => 'Kate Whitley',
					'matveb'             => 'Matías Ventura',
					'melchoyce'          => 'Mel Choyce',
					'mitchoyoshitaka'    => 'Michael Erlewine',
					'ryelle'             => 'Kelly Dwan',
					'shaunandrews'       => 'Shaun Andrews',
					'tillkruess'         => 'Till Krüss',
					'jorbin'             => 'Aaron Jorbin',
					'kadamwhite'         => 'K. Adam White',
					'yoavf'              => 'Yoav Farhi',
					'celloexpressions'   => 'Nick Halsey',
					'iamtakashi'         => 'Takashi Irie',
					'obenland'           => 'Konstantin Obenland',
				),
			),
		);
		return $groups;
	}

	// As of final release, r25914 to r26862
	function props() {
		return array(
			'aaronholbrook',
			'adamsilverstein',
			'admiralthrawn',
			'ahoereth',
			'andypeatling',
			'ankitgadertcampcom',
			'apeatling',
			'aralbald',
			'atimmer',
			'aubreypwd',
			'azaozz',
			'bamadesigner',
			'bananastalktome',
			'bassgang',
			'batmoo', // props missed by committer, r26046
			'binarymoon',
			'bpetty',
			'bradyvercher',
			'buffler', // 2014 pre-3.8
			'cainm',
			'calin',
			'carldanley',
			'caspie',
			'celloexpressions',
			'chellycat',
			'chrisbliss18',
			'codebykat',
			'coffee2code',
			'corphi',
			'danieldudzic',
			'datafeedrcom',
			'dbernar1',
			'dd32',
			'defries',
			'designsimply',
			'devesine',
			'dh-shredder',
			'dimadin',
			'dougwollison',
			'drewapicture',
			'drozdz',
			'drw158',
			'duck_',
			'dziudek',
			'empireoflight',
			'ericlewis',
			'ericmann',
			'ethitter',
			'evansolomon',
			'faison',
			'fliespl',
			'frank-klein',
			'garyj',
			'georgestephanis',
			'gnarf37',
			'gradyetc',
			'grapplerulrich',
			'hanni',
			'helen',
			'iammattthomas',
			'iamtakashi',
			'iandunn',
			'iblamefish',
			'ipstenu',
			'isaackeyet',
			'jacklenox',
			'janhenckens',
			'jartes',
			'jayjdk',
			'jblz',
			'jdgrimes',
			'jeffr0',
			'jeherve', // 2014 pre-3.8
			'jenmylo',
			'jeremyfelt',
			'jhned',
			'jim912',
			'joedolson', // 2014 pre-3.8
			'joen',
			'johnafish',
			'johnbillion',
			'johnjamesjacoby',
			'joostdevalk',
			'jorbin',
			'joshuaabenazer',
			'jpry',
			'justinsainton',
			'kadamwhite',
			'koki4a',
			'kovshenin',
			'kpdesign',
			'kraftbj',
			'kwight',
			'l10n',
			'lancewillett',
			'latz',
			'leewillis77',
			'lessbloat',
			'lite3',
			'littlethingsstudio',
			'lucp',
			'mako09',
			'markjaquith',
			'markmcwilliams',
			'markoheijnen',
			'matt',
			'mattheu',
			'mattwiebe',
			'matveb',
			'mauryaratan',
			'mdbitz',
			'mbmufffin', // 2014 pre-3.8
			'megane9988',
			'melchoyce',
			'micahwave',
			'michelwppi',
			'mikehansenme',
			'mikelittle',
			'mitchoyoshitaka',
			'miyauchi',
			'morganestes',
			'mt8biz',
			'nacin',
			'nao',
			'nbachiyski',
			'neil_pie',
			'netweb',
			'nickdaugherty',
			'ninio',
			'ninnypants',
			'nofearinc',
			'nukaga',
			'nvwd',
			'obenland',
			'ocean90',
			'odysseygate',
			'originalexe',
			'otto42',
			'ounziw',
			'pauldewouters',
			'pavelevap',
			'pento',
			'ptahdunbar',
			'raamdev',
			'rachelbaker',
			'radices',
			'rdall',
			'rickalee',
			'rodrigosprimo',
			'ryan',
			'ryelle',
			'rzen',
			'sabreuse', // 2014 pre-3.8
			'sanchothefat',
			'sboisvert',
			'scottbasgaard',
			'scribu',
			'seanchayes',
			'senlin', // #26059
			'sergeybiryukov',
			'shaunandrews',
			'shinichin',
			'simonwheatley',
			'siobhan',
			'siobhyb',
			'sirbrillig',
			'sixhours',
			'solarissmoke',
			'soulseekah',
			'stephenharris',
			'stevenkword',
			'swissspidy',
			'taupecat', // 2014 pre-3.8
			'thomasguillot',
			'tierra',
			'tillkruess',
			'tivnet',
			'tlamedia',
			'tmtoy',
			'tobiasbg',
			'tollmanz',
			'tommcfarlin',
			'trepmal',
			'trishasalas', // 2014 pre-3.8
			'westi',
			'westonruter',
			'wet',
			'wonderboymusic',
			'yoavf',
			'yonasy',
			'zodiac1978',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery Masonry', 'http://masonry.desandro.com/' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/lowe/zxcvbn' ),
		);
	}
}
