<?php

class WP_41_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => array(
					'johnbillion' => array( 'John Blackbourn', 'Release Lead', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'dd32'        => array( 'Dion Hulse',        'Core Developer' ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer' ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
					'helen'       => array( 'Helen Hou-Sandí',   'Core Developer' ),
					'ocean90'        => array( 'Dominik Schilling', 'Core Developer' ),
					'SergeyBiryukov' => array( 'Sergey Biryukov', 'Core Developer' ),
					'wonderboymusic' => array( 'Scott Taylor', 'Core Developer', '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'lancewillett'   => 'Lance Willett',
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'boonebgorges'   => 'Boone B. Gorges',
					'pento'          => 'Gary Pendergast',
					'jorbin'         => 'Aaron Jorbin',
					'kovshenin'      => 'Konstantin Kovshenin',
					'jeremyfelt'     => 'Jeremy Felt',
					'DrewAPicture'   => 'Drew Jaynes',
					'iandstewart'    => 'Ian Stewart',
				),
			),
			'recent-rockstars' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
				),
			),
		);
		return $groups;
	}

	// As of final release, r25914 to r26862
	function props() {
		return array(
			'5um17',
			'aaroncampbell',
			'adamsilverstein',
			'afercia',
			'akumria',
			'alex-ye',
			'amruta123b',
			'andg',
			'andrewryno',
			'ankit-k-gupta',
			'ankitgadertcampcom',
			'antpb',
			'aprea',
			'arippberger',
			'avryl',
			'azaozz',
			'babbardel',
			'bainternet',
			'barrykooij',
			'benjmay',
			'birgire',
			'bobbingwide',
			'boonebgorges',
			'bordoni',
			'bradyvercher',
			'bramd',
			'briandichiara',
			'bswatson',
			'cainm',
			'camdensegal',
			'captaintheme',
			'caspie',
			'ccprice',
			'celloexpressions',
			'cfinke',
			'cfoellmann',
			'chellycat',
			'chrico',
			'chrisbliss18',
			'chriscct7',
			'chrisl27',
			'clorith',
			'cmmarslender',
			'coffee2code',
			'collinsinternet',
			'colorful-tones',
			'convissor',
			'corphi',
			'curtjen',
			'cyclometh',
			'dancameron',
			'danielbachhuber',
			'davidakennedy',
			'davidjlaietta',
			'davidthemachine',
			'dcavins',
			'dd32',
			'desaiuditd',
			'desrosj',
			'dh-shredder',
			'dlh',
			'dmchale',
			'dominikschwind-1',
			'donutz',
			'drewapicture',
			'duck_',
			'dustinhartzler',
			'dustyf',
			'ebinnion',
			'eliorivero',
			'empireoflight',
			'engelen',
			'ericlewis',
			'ew_holmes',
			'fab1en',
			'filosofo',
			'florianziegler',
			'garyc40',
			'gcorne',
			'georgestephanis',
			'gregrickaby',
			'greuben',
			'hardy101',
			'hauvong',
			'helen',
			'hereswhatidid',
			'heshiming',
			'hiwhatsup',
			'honeysilvas',
			'hugodelgado',
			'iamtakashi',
			'iandstewart',
			'ianmjones',
			'ideag',
			'igmoweb',
			'imath',
			'ipm-frommen',
			'ipstenu',
			'ivankristianto',
			'ixkaito',
			'jaimieolmstead',
			'jakubtyrcha',
			'janhenckens',
			'japh',
			'jarednova',
			'jayjdk',
			'jazzs3quence',
			'jb510',
			'jbrinley',
			'jdgrimes',
			'jeanyoungkim',
			'jeffstieler',
			'jeherve',
			'jeremyfelt',
			'jesin',
			'jessepollak',
			'jfarthing84',
			'jipmoors',
			'joedolson',
			'joemcgill',
			'johnbillion',
			'johneckman',
			'johnrom',
			'johnstonphilip',
			'joostdevalk',
			'jorbin',
			'joshuaabenazer',
			'jrf',
			'jtsternberg',
			'julien731',
			'justinsainton',
			'jwenerd',
			'kadamwhite',
			'kamelkev',
			'karmatosed',
			'karpstrucking',
			'kdoran',
			'keesiemeijer',
			'kevinlangleyjr',
			'kitchin',
			'knutsp',
			'koop',
			'kosvrouvas',
			'kovshenin',
			'kpdesign',
			'kraftbj',
			'kraftner',
			'kristastevens',
			'kurtpayne',
			'kwight',
			'lancewillett',
			'landakram',
			'latz',
			'liljimmi',
			'linuxologos',
			'loushou',
			'mackensen',
			'manoz69',
			'mantismamita',
			'marcosf',
			'markjaquith',
			'markoheijnen',
			'marsjaninzmarsa',
			'matt',
			'mattheu',
			'mattkeys',
			'mattwiebe',
			'matveb',
			'mboynes',
			'mcsf',
			'mdawaffe',
			'melchoyce',
			'merty',
			'michael-arestad',
			'michalzuber',
			'mikehansenme',
			'mikejolley',
			'mikeyarce',
			'miqrogroove',
			'miyauchi',
			'mlteal',
			'mnelson4',
			'momo360modena',
			'mor10',
			'mordauk',
			'morganestes',
			'mvd7793',
			'nacin',
			'neoxx',
			'nerrad',
			'netweb',
			'niallkennedy',
			'nikolovtmw',
			'nikv',
			'nobinobi',
			'nobleclem',
			'nofearinc',
			'noplanman',
			'nprasath002',
			'nvwd',
			'obenland',
			'ocean90',
			'offereins',
			'originalexe',
			'otto42',
			'p_enrique',
			'pauldewouters',
			'paulschreiber',
			'paulwilde',
			'pavelevap',
			'pento',
			'peterchester',
			'peterwilsoncc',
			'philiparthurmoore',
			'phpmypython',
			'psycleuk',
			'ptahdunbar',
			'pushplaybang',
			'quietnic',
			'rachelbaker',
			'ramiabraham',
			'ramiy',
			'rarst',
			'realloc',
			'rianrietveld',
			'richardmtl',
			'rickalee',
			'rmccue',
			'rodrigosprimo',
			'ryankienstra',
			'ryelle',
			'rzen',
			'sakinshrestha',
			'samhotchkiss',
			'sc0ttkclark',
			'senff',
			'sergeybiryukov',
			'shooper',
			'simonp303',
			'simonwheatley',
			'skaeser',
			'slobodanmanic',
			'smashcut',
			'socki03',
			'softmodeling',
			'solarissmoke',
			'soulseekah',
			'stephdau',
			'stephenharris',
			'stevegrunwell',
			'studionashvegas',
			'sumobi',
			'tacoverdo',
			'tai',
			'tareq1988',
			'technical_mastermind',
			'tellyworth',
			'tillkruess',
			'tivnet',
			'tjnowell',
			'tlovett1',
			'tmtrademark',
			'tobiasbg',
			'tollmanz',
			'tomasm',
			'tomharrigan',
			'topher1kenobe',
			'transom',
			'trepmal',
			'tschutter',
			'tw2113',
			'tywayne',
			'umeshsingla',
			'vinod-dalvi',
			'viper007bond',
			'vlajos',
			'voldemortensen',
			'wedi',
			'westonruter',
			'wonderboymusic',
			'wpsmith',
			'xknown',
			'yoavf',
			'zodiac1978',
			'zrothauser',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/color/' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/query-object/' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'Masonry', 'http://masonry.desandro.com/' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://codylindley.com/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ),
		);
	}
}
