<?php

class WP_43_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'matt'        => array( 'Matt Mullenweg',  'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',    'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',    'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'azaozz'      => array( 'Andrew Ozz',      'Lead Developer'          ),
					'helen'       => array( 'Helen Hou-Sandí', 'Lead Developer'          ),
					'dd32'        => array( 'Dion Hulse',      'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => array(
					'obenland'       => array( 'Konstantin Obenland', 'Release Lead'   ),
					'ocean90'        => array( 'Dominik Schilling',   'Core Developer' ),
					'wonderboymusic' => array( 'Scott Taylor',        'Core Developer' ),
					'SergeyBiryukov' => array( 'Sergey Biryukov',     'Core Developer' ),
					'boonebgorges'   => array( 'Boone B. Gorges',     'Core Developer' ),
					'pento'          => array( 'Gary Pendergast',     'Core Developer' ),
					'johnbillion'    => array( 'John Blackbourn',     'Core Developer', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'DrewAPicture'   => array( 'Drew Jaynes',         'Docs Committer' ),
					'lancewillett'   => 'Lance Willett',
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'iseulde'        => 'Ella Iseulde Van Dorpe',
					'westonruter'    => array( 'Weston Ruter', '22ed378fbf1d918ef43a45b2a1f34634' ),
					'jorbin'         => 'Aaron Jorbin',
					'jeremyfelt'     => 'Jeremy Felt',
					'ryan'           => 'Ryan Boren',
					'afercia'        => 'Andrea Fercia',
				),
			),
			'recent-rockstars' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'valendesigns'     => 'Derek Herman',
					'celloexpressions' => array( 'Nick Halsey', '42e659bb8c86851c230e527f8ce1764b'  ),
					'voldemortensen'   => 'Garth Mortensen',
					'rianrietveld'     => 'Rian Rietveld',
					'designsimply'     => 'Sheri Bigelow',
					'adamsilverstein'  => 'Adam Silverstein',
				),
			),
		);

		return $groups;
	}

	function props() {
		return array(
			'aaroncampbell',
			'adamkheckler',
			'adamsilverstein',
			'afercia',
			'afragen',
			'akibjorklund',
			'akirk',
			'andfinally',
			'andg',
			'ankit-k-gupta',
			'antpb',
			'anubisthejackle',
			'aramzs',
			'arjunskumar',
			'avnarun',
			'azaozz',
			'bcole808',
			'binarykitten',
			'birgire',
			'bjornjohansen',
			'bolo1988',
			'boonebgorges',
			'brad2dabone',
			'bradt',
			'bramd',
			'brianlayman',
			'c3mdigital',
			'calevans',
			'celloexpressions',
			'chasewiseman',
			'chipbennett',
			'chouby',
			'chriscct7',
			'clorith',
			'coffee2code',
			'craig',
			'creativeinfusion',
			'danielbachhuber',
			'daniluk4000',
			'daveal',
			'davidakennedy',
			'daxelrod',
			'dd32',
			'deconf',
			'denis-de-bernardy',
			'desaiuditd',
			'designsimply',
			'dh-shredder',
			'dimadin',
			'dipeshkakadiya',
			'djpaul',
			'dlh',
			'dmchale',
			'dmsnell',
			'drewapicture',
			'earnjam',
			'ebinnion',
			'eclev91',
			'eligijus',
			'eliorivero',
			'eltobiano',
			'empireoflight',
			'ericlewis',
			'ericmann',
			'fab1en',
			'flixos90',
			'francoeurdavid',
			'frank-klein',
			'gabrielperezs',
			'garyj',
			'georgestephanis',
			'glennm',
			'greuben',
			'gtuk',
			'gungeekatx',
			'hailin',
			'hauvong',
			'helen',
			'henrikakselsen',
			'hnle',
			'hrishiv90',
			'hugobaeta',
			'icaleb',
			'imath',
			'ipstenu',
			'isaacchapman',
			'iseulde',
			'ixkaito',
			'izem',
			'jacklenox',
			'jadpm',
			'jamesgol',
			'jancbeck',
			'jdgrimes',
			'jeremyfelt',
			'jesin',
			'jfarthing84',
			'jipmoors',
			'jkudish',
			'jmichaelward',
			'joedolson',
			'joehoyle',
			'joemcgill',
			'johnbillion',
			'johnjamesjacoby',
			'joostdevalk',
			'jorbin',
			'jpry',
			'jpyper',
			'jrf',
			'jtsternberg',
			'juliobox',
			'karinchristen',
			'karpstrucking',
			'katzwebdesign',
			'kevkoeh',
			'kitchin',
			'kovshenin',
			'kraftbj',
			'krogsgard',
			'kucrut',
			'lamosty',
			'lancewillett',
			'leewillis77',
			'leogopal',
			'liljimmi',
			'loushou',
			'lumaraf',
			'magicroundabout',
			'markjaquith',
			'markoheijnen',
			'marsjaninzmarsa',
			'martinsachse',
			'mattwiebe',
			'mattyrob',
			'maxxsnake',
			'mcguive7',
			'mdawaffe',
			'melchoyce',
			'mercime',
			'metodiew',
			'michael-arestad',
			'michaelryanmcneill',
			'mihai',
			'mikehansenme',
			'miqrogroove',
			'mnelson4',
			'mordauk',
			'morganestes',
			'mrutz',
			'mte90',
			'nabil_kadimi',
			'nacin',
			'Nao',
			'nazmulhossainnihal',
			'nbachiyski',
			'netweb',
			'nicholas_io',
			'nickmomrik',
			'nikonratm',
			'nofearinc',
			'obenland',
			'ocean90',
			'ohryan',
			'onnimonni',
			'oxymoron',
			'ozh',
			'pareshradadiya-1',
			'paulwilde',
			'pavelevap',
			'pento',
			'peterrknight',
			'peterwilsoncc',
			'philiparthurmoore',
			'picard102',
			'polevaultweb',
			'posykrat',
			'pragunbhutani',
			'rabmalin',
			'rachelbaker',
			'ralston',
			'ramiy',
			'rarylson',
			'rauchg',
			'ravinderk',
			'rclations',
			'rdall',
			'realloc',
			'redsweater',
			'rhurling',
			'rianrietveld',
			'ritteshpatel',
			'rmarks',
			'rmccue',
			'rodrigosprimo',
			'rommelxcastro',
			'ryan',
			'ryelle',
			'sagarjadhav',
			'salcode',
			'santagada',
			'sc0ttkclark',
			'scribu',
			'scruffian',
			'seanchayes',
			'sebastiantiede',
			'sergeybiryukov',
			'shooper',
			'simonwheatley',
			'siobhan',
			'solarissmoke',
			'stephdau',
			'stevegrunwell',
			'stevenkword',
			'stuartshields',
			'sudar',
			'sunnyratilal',
			'swissspidy',
			'taka2',
			'tellyworth',
			'tharsheblows',
			'thorbrink',
			'tlexcellent',
			'tmatsuur',
			'tobiasbg',
			'tollmanz',
			'tomasm',
			'tomharrigan',
			'toro_unit',
			'toru',
			'tryon',
			'tywayne',
			'tyxla',
			'ungestaltbar',
			'valendesigns',
			'veraxus',
			'viper007bond',
			'vivekbhusal',
			'voldemortensen',
			'welcher',
			'westonruter',
			'willgladstone',
			'willnorris',
			'willstedt',
			'wonderboymusic',
			'yoavf',
			'ysalame',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/color/' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/query-object/' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'Masonry', 'http://masonry.desandro.com/' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://codylindley.com/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Twemoji', 'https://github.com/twitter/twemoji' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ),
		);
	}
}
