<?php

class WP_40_Credits extends WP_Credits {

	function groups() {
		$groups = array(
			'project-leaders' => array(
				'name'    => 'Project Leaders',
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'ryan'        => array( 'Ryan Boren',     'Lead Developer'          ),
					'markjaquith' => array( 'Mark Jaquith',   'Lead Developer', '097a87a525e317519b5ee124820012fb' ),
					'matt'        => array( 'Matt Mullenweg', 'Cofounder, Project Lead' ),
					'nacin'       => array( 'Andrew Nacin',   'Lead Developer'          ),
					'azaozz'      => array( 'Andrew Ozz',     'Lead Developer'          ),
					'westi'       => array( 'Peter Westwood', 'Lead Developer'          ),
				),
			),
			'core-developers' => array(
				'name'    => 'Contributing Developers',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => array(
					'helen'       => array( 'Helen Hou-Sandí',   'Release Lead' ),
					'dd32'        => array( 'Dion Hulse',        'Core Developer' ),
					'koop'        => array( 'Daryl Koopersmith', 'Core Developer' ),
					'duck_'       => array( 'Jon Cave',          'Core Developer' ),
					'ocean90'        => array( 'Dominik Schilling', 'Core Developer' ),
					'SergeyBiryukov' => array( 'Sergey Biryukov', 'Core Developer' ),
				),
			),
			'contributing-developers' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'wonderboymusic' => array( 'Scott Taylor',    '0e9fc8ea22885ed718ee37d31dcffb8c' ),
					'johnbillion'    => array( 'John Blackbourn', '0000ba6dd1b089e1746abbfe6281ee3b' ),
					'DrewAPicture'   => 'Drew Jaynes',
				),
			),
			'recent-rockstars' => array(
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => array(
					'avryl' => 'Janneke Van Dorpe',
					'ericlewis' => 'Eric Andrew Lewis',
					'shaunandrews' => 'Shaun Andrews',
					'gcorne' => 'Gregory Cornelius',
					'celloexpressions' => array( 'Nick Halsey', '42e659bb8c86851c230e527f8ce1764b' ),
					'westonruter' => array( 'Weston Ruter', '22ed378fbf1d918ef43a45b2a1f34634' ),
					'miqrogroove' => array( 'Robert Chapin', 'fc6128ee96fa6ea66a9dc9ed244072b5' ),
					'stephdau' => 'Stephane Daury',
					'tellyworth' => 'Alex Shiels',
					'joedolson' => 'Joe Dolson',
					'kovshenin' => 'Konstantin Kovshenin',
					'adamsilverstein' => 'Adam Silverstein',
				),
			),
		);
		return $groups;
	}

	// As of final release, r25914 to r26862
	function props() {
		return array(
			'5um17',
			'aaroncampbell',
			'adamsilverstein',
			'afercia',
			'alexanderrohmann',
			'alex-ye',
			'aliso',
			'amit',
			'andrezrv',
			'andy',
			'ankit-k-gupta',
			'arnee',
			'atimmer',
			'aubreypwd',
			'avryl',
			'azaozz',
			'boda1982',
			'boonebgorges',
			'bordoni',
			'bradyvercher',
			'bramd',
			'brianlayman',
			'c3mdigital',
			'camdensegal',
			'caxelsson',
			'celloexpressions',
			'cfinke',
			'chouby',
			'chrico',
			'chrisl27',
			'clifgriffin',
			'clorith',
			'codenameeli',
			'coffee2code',
			'collinsinternet',
			'compute',
			'corphi',
			'danielbachhuber',
			'danielhuesken',
			'dannydehaan',
			'davidakennedy',
			'davidthemachine',
			'dd32',
			'debaat',
			'dh-shredder',
			'dimadin',
			'dkotter',
			'dlh',
			'dllh',
			'dnaber-de',
			'donncha',
			'drewapicture',
			'duck_',
			'dustyn',
			'ebinnion',
			'eddiemoya',
			'edwin-at-studiojoyocom',
			'eherman24',
			'ehg',
			'ejdanderson',
			'empireoflight',
			'engelen',
			'erayalakese',
			'ericlewis',
			'ericmann',
			'extendwings',
			'fab1en',
			'fahmiadib',
			'feedmeastraycat',
			'filosofo',
			'frank-klein',
			'funkatronic',
			'garhdez',
			'garyc40',
			'garyj',
			'garza',
			'gauravmittal1995',
			'gavra',
			'gcorne',
			'georgestephanis',
			'ghost1227',
			'grahamarmfield',
			'greenshady',
			'greglone',
			'harmr',
			'harrym',
			'hebbet',
			'helen',
			'hinnerk',
			'hlashbrooke',
			'iamfriendly',
			'iamtakashi',
			'iljoja',
			'imath',
			'ipstenu',
			'issuu',
			'ixkaito',
			'jacklenox',
			'jackreichert',
			'jacobdubail',
			'janhenkg',
			'jartes',
			'jayjdk',
			'jaza613',
			'jdgrimes',
			'jeffstieler',
			'jeremyfelt',
			'jerrysarcastic',
			'jesin',
			'jesper800',
			'jessepollak',
			'jgadbois',
			'jjeaton',
			'jkudish',
			'joedolson',
			'joehoyle',
			'johnbillion',
			'johnjamesjacoby',
			'johnzanussi',
			'jonnyauk',
			'joostdevalk',
			'jorbin',
			'jpry',
			'jtsternberg',
			'juliobox',
			'jupiterwise',
			'justinsainton',
			'jwenerd',
			'kadamwhite',
			'kapeels',
			'katzwebdesign',
			'kau-boy',
			'kevinlangleyjr',
			'kitchin',
			'knutsp',
			'koop',
			'kovshenin',
			'kpdesign',
			'kraftbj',
			'krogsgard',
			'kurtpayne',
			'kwight',
			'kworthington',
			'lancewillett',
			'layotte',
			'leewillis77',
			'lessbloat',
			'lgedeon',
			'liljimmi',
			'lritter',
			'lukecarbis',
			'm_i_n',
			'm_uysl',
			'mackensen',
			'markjaquith',
			'markoheijnen',
			'mattheu',
			'mattheweppelsheimer',
			'mattwiebe',
			'mattyrob',
			'mauteri',
			'mboynes',
			'mdawaffe',
			'mdbitz',
			'meekyhwang',
			'melchoyce',
			'michalzuber',
			'midxcat',
			'mikehansenme',
			'mikejolley',
			'mikelittle',
			'mikemanger',
			'mikeyarce',
			'miqrogroove',
			'mjbanks',
			'mnelson4',
			'mordauk',
			'morganestes',
			'mrmist',
			'muvimotv',
			'nabil_kadimi',
			'nacin',
			'namibia',
			'nbachiyski',
			'nd987',
			'neil_pie',
			'nessworthy',
			'netweb',
			'niallkennedy',
			'ninos-ego',
			'nvwd',
			'obenland',
			'ocean90',
			'oso96_2000',
			'otto42',
			'paulschreiber',
			'paulwilde',
			'pavelevap',
			'pbearne',
			'pdclark',
			'pento',
			'philiparthurmoore',
			'philipjohn',
			'psoluch',
			'purzlbaum',
			'rachelbaker',
			'rclations',
			'rdall',
			'redsweater',
			'rhurling',
			'rickalee',
			'rmccue',
			'rob1n',
			'rohan013',
			'ruudjoyo',
			'ryelle',
			'rzen',
			'sabreuse',
			'sammybeats',
			'sathishn',
			'schoenwaldnils',
			'scribu',
			'seanchayes',
			'senlin',
			'sergejmueller',
			'sergeybiryukov',
			'shanebp',
			'sharonaustin',
			'shaunandrews',
			'simonp303',
			'simonwheatley',
			'sivel',
			'sixhours',
			'slimndap',
			'slobodanmanic',
			'smashcut',
			'softmodeling',
			'solarissmoke',
			'sphoid',
			'stephdau',
			'stompweb',
			'strangerstudios',
			'sumobi',
			't4k1s',
			'tai',
			'targz-1',
			'taylorde',
			'tellyworth',
			'thomasvanderbeek',
			'tillkruess',
			'tjnowell',
			'tmeister',
			'tobiasbg',
			'tollmanz',
			'topher1kenobe',
			'torresga',
			'trepmal',
			'treyhunner',
			'umeshsingla',
			'usermrpapa',
			'vancoder',
			'vinod-dalvi',
			'viper007bond',
			'vlajos',
			'voldemortensen',
			'westonruter',
			'willmot',
			'winterdev',
			'wojtekszkutnik',
			'wonderboymusic',
			'wpsmith',
			'yoavf',
			'zamfeer',
			'zoerooney',
		);
	}

	function external_libraries() {
		return array(
			array( 'Backbone.js', 'http://backbonejs.org/' ),
			array( 'Class POP3', 'http://squirrelmail.org/' ),
			array( 'Color Animations', 'http://plugins.jquery.com/project/color' ),
	//		array( 'ColorPicker', 'http://' ),
			array( 'Horde Text Diff', 'http://pear.horde.org/' ),
			array( 'hoverIntent', 'http://plugins.jquery.com/project/hoverIntent' ),
			array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
			array( 'Iris', 'https://github.com/Automattic/Iris' ),
			array( 'jQuery', 'http://jquery.com/' ),
			array( 'jQuery UI', 'http://jqueryui.com/' ),
			array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
			array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
			array( 'jQuery.query', 'http://plugins.jquery.com/project/query-object' ),
	//		array( 'jquery.schedule', 'http://' ),
			array( 'jQuery.suggest', 'http://plugins.jquery.com/project/suggest' ),
			array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
			array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
			array( 'Masonry', 'http://masonry.desandro.com/' ),
			array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
			array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
			array( 'PemFTP', 'http://www.phpclasses.org/browse/package/1743.html' ),
			array( 'phpass', 'http://www.openwall.com/phpass/' ),
			array( 'PHPMailer', 'http://code.google.com/a/apache-extras.org/p/phpmailer/' ),
			array( 'Plupload', 'http://www.plupload.com/' ),
			array( 'SimplePie', 'http://simplepie.org/' ),
			array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
			array( 'Thickbox', 'http://jquery.com/demo/thickbox/' ),
			array( 'TinyMCE', 'http://www.tinymce.com/' ),
			array( 'Underscore.js', 'http://underscorejs.org/' ),
			array( 'zxcvbn', 'https://github.com/lowe/zxcvbn' ),
		);
	}
}
