<?php

class WP_58_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                => [ 'Matt Mullenweg', 'Release Lead' ],
					'JeffPaul'            => [ 'Jeff Paul', 'Release Lead' ],
					'desrosj'             => [ 'Jonathan Desrosiers', 'Release Lead' ],
					'youknowriad'         => 'Riad Benguella',
					'chanthaboune'        => 'Josepha Haden',
					'milana_cap'          => 'Milana Cap',
					'Boniu91'             => 'Piotrek Boniu',
					'mariaojob'           => 'Mary Job',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'ellatrix'            => 'Ella van Durpe',
					'gziolo'              => 'Greg Ziółkowski',
					'noisysocks'          => 'Robert Anderson',
					'talldanwp'           => 'Daniel Richards',
					'isabel_brison'       => 'Isabel Brison',
					'andraganescu'        => 'Andrei Draganescu',
					'mcsf'                => 'Miguel Fonseca',
					'annezazu'            => 'Anne McCarthy',
					'daisyo'              => 'Daisy Olsen',
					'adamsilverstein'     => 'Adam Silverstein',
					'ryelle'              => 'Kelly Choyce-Dwan',
					'TimothyBlynJacobs'   => 'Timothy Jacobs',
					'Joen'                => 'Joen Asmussen',
					'nosolosw'            => 'André Maneiro',
					'sarayourfriend'      => 'sarayourfriend',
					'ntsekouras'          => 'Nik Tsekouras',
					'peterwilsoncc'       => 'Peter Wilson',
					'aristath'            => 'Ari Stathopoulos',
					'Mamaduka'            => 'George Mamadashvili',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'lukecarbis'          => 'Luke Carbis',
					'helen'               => 'Helen Hou-Sandí',
					'cbringmann'          => 'Chloé Bringmann',
					'marybaum'            => 'Mary Baum',
					'webcommsat'          => 'Abha Thakor',
					'spacedmonkey'        => 'Jonny Harris',
					'kevin940726'         => 'Kai Hao',
					'audrasjb'            => 'Jean-Baptiste Audras',
					'johnbillion'         => 'John Blackbourn',
					'jorgefilipecosta'    => 'Jorge Costa',
					'hellofromTonya'      => 'Tonya Mork',
					'jorbin'              => 'Aaron Jorbin',
					'poena'               => 'Carolina Nymark',
					'walbo'               => 'Petter Walbø Johnsgård',
					'Bernhard Reiter'     => 'Bernhard Reiter',
					'davidbaumwald'       => 'David Baumwald',
					'mukesh27'            => 'Mukesh Panchal',
					'ocean90'             => 'Dominik Schilling',
					'chaion07'            => 'Ahmed Chaion',
					'itsjusteileen'       => 'Eileen Violini',
					'zieladam'            => 'Adam Zielinski',
					'femkreations'        => 'Femy Praseeth',
					'meher'               => 'Meher Bala',
					'oglekler'            => 'Olga Gleckler',
					'francina'            => 'Francesca Marano',
					'beafialho'           => 'Beatriz Fialho',
					'melchoyce'           => 'Mel Choyce-Dwan',
					'kjellr'              => 'Kjell Reigstad',
					'jameskoster'         => 'James Koster',
					'matveb'              => 'Matias Ventura',
					'kafleg'              => 'Ganga Kafle',
					'dufresnesteven'      => 'Steve Dufresne',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'2linctools',
			'5ubliminal',
			'5um17',
			'9primus',
			'aaronrobertshaw',
			'abderrahman',
			'abhijitrakas',
			'achbed',
			'adamsilverstein',
			'addiestavlo',
			'aduth',
			'afercia',
			'afragen',
			'ajitbohra',
			'ajlende',
			'akabarikalpesh',
			'akirk',
			'alanjacobmathew',
			'aleperez92',
			'alexstine',
			'algala',
			'aliveic',
			'aljullu',
			'amandariu',
			'amarinediary',
			'andraganescu',
			'andrewserong',
			'andy',
			'ankitmaru',
			'annalamprou',
			'annezazu',
			'anotherdave',
			'anotia',
			'antonisme',
			'antonlukin',
			'antonvlasenko',
			'antpb',
			'apeatling',
			'apedog',
			'apokalyptik',
			'arena',
			'ariskataoka',
			'aristath',
			'arkrs',
			'arnaudban',
			'arthur791004',
			'arunsathiya',
			'aruphi',
			'aspexi',
			'assassinateur',
			'atjn',
			'audrasjb',
			'aurooba',
			'ayeshrajans',
			'azaozz',
			'barry',
			'bartkalisz',
			'beafialho',
			'benoitchantre',
			'bernhard-reiter',
			'bhwebworks',
			'birgire',
			'blobfolio',
			'bmcculley',
			'bobbingwide',
			'boblinthorst',
			'bogdanpreda',
			'boniu91',
			'boonebgorges',
			'bph',
			'bradleyt',
			'bradt',
			'brechtvds',
			'brentswisher',
			'brettshumaker',
			'bueltge',
			'burhandodhy',
			'cameronjonesweb',
			'carike',
			'carlalexander',
			'carlomanf',
			'carlosgprim',
			'caseymilne',
			'cbringmann',
			'celloexpressions',
			'cenay',
			'ceyhun0',
			'chaion07',
			'chanthaboune',
			'chetan200891',
			'chintan1896',
			'chipsnyder',
			'chouby',
			'chriscct7',
			'chrisvanpatten',
			'circlecube',
			'claytoncollie',
			'clorith',
			'codeamp',
			'coffee2code',
			'collizo4sky',
			'copons',
			'coreymckrill',
			'costdev',
			'courane01',
			'cr0ybot',
			'crazycoders',
			'critterverse',
			'cvoell',
			'cybr',
			'czapla',
			'daddou',
			'daisyo',
			'damonganto',
			'danfarrow',
			'danieldudzic',
			'dariak',
			'dartiss',
			'davidanderson',
			'davidbaumwald',
			'davidbinda',
			'davidkryzaniak',
			'davidszabo',
			'davidwebca',
			'davilera',
			'dd32',
			'dekervit',
			'desaiuditd',
			'design_dolphin',
			'desrosj',
			'deustron',
			'devle',
			'devnel',
			'devrekli',
			'dhruvkb',
			'dianeco',
			'diddledan',
			'dimadin',
			'dingdang',
			'displaynone',
			'djbu',
			'dkampdesign',
			'dlh',
			'donmhico',
			'donnapep',
			'dougwollison',
			'dpcalhoun',
			'dpik',
			'dragongate',
			'dragunoff',
			'drebbitsweb',
			'drewapicture',
			'dufresnesteven',
			'dway',
			'earnjam',
			'eatsleepcode',
			'ediamin',
			'eidolonnight',
			'ellatrix',
			'emarticor',
			'empatogen',
			'enchiridion',
			'enej',
			'engahmeds3ed',
			'epiqueras',
			'etoledom',
			'fabiankaegy',
			'fabianpimminger',
			'fantasy1125',
			'felipeelia',
			'felixbaumgaertner',
			'femkreations',
			'fierevere',
			'fijisunshine',
			'filosofo',
			'firewatch',
			'flixos90',
			'florianbrinkmann',
			'francina',
			'frosso1',
			'fullofcaffeine',
			'gaambo',
			'gab81',
			'gadgetroid',
			'galbaras',
			'garrett-eclipse',
			'garyj',
			'geekpress',
			'geekstreetwp',
			'geoffrey1963',
			'georgestephanis',
			'geriux',
			'get_dave',
			'gitlost',
			'glendaviesnz',
			'gmagicscott',
			'goaroundagain',
			'grantmkin',
			'grapplerulrich',
			'gregorlove',
			'gwwar',
			'gziolo',
			'hannahmalcolm',
			'happiryu',
			'hareesh-pillai',
			'hazdiego',
			'hedgefield',
			'helen',
			'hellofromtonya',
			'hermpheus',
			'herregroen',
			'herrvigg',
			'htmgarcia',
			'hypest',
			'iandunn',
			'ianmjones',
			'icopydoc',
			'imath',
			'immeet94',
			'infolu',
			'ipstenu',
			'isabel_brison',
			'itsjonq',
			'ixkaito',
			'jacklenox',
			'jamesbonham',
			'jameskoster',
			'jamesros161',
			'jamil95',
			'janak007',
			'janwoostendorp',
			'javiarce',
			'jaymanpandya',
			'jb510',
			'jblz',
			'jdgrimes',
			'jdy68',
			'jeffikus',
			'jeffpaul',
			'jeherve',
			'jeremy80',
			'jeremyfelt',
			'jeremyyip',
			'jeroenreumkens',
			'jeryj',
			'jffng',
			'jillebehm',
			'jipmoors',
			'jnylen0',
			'joedolson',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnny5',
			'jonkastonka',
			'jonoaldersonwp',
			'jonsurrell',
			'jontyravi',
			'joostdevalk',
			'jorbin',
			'jorgefilipecosta',
			'joseeyoast',
			'joyously',
			'jrf',
			'jsnajdr',
			'jsnjohnston',
			'juanfra',
			'juanmaguitar',
			'juliobox',
			'justinahinon',
			'k3nsai',
			'kaavyaiyer',
			'kafleg',
			'kapilpaul',
			'karmatosed',
			'kebbet',
			'kellychoffman',
			'kevin940726',
			'kevinfodness',
			'khromov',
			'kirasong',
			'kishanjasani',
			'kittmedia',
			'kjellr',
			'klevyke',
			'knutsp',
			'koke',
			'kraftbj',
			'kraftner',
			'kreppar',
			'krstarica',
			'lakrisgubben',
			'laxman-prajapati',
			'lephleg',
			'lev0',
			'lewiscowles',
			'lifeforceinst',
			'linux4me2',
			'lmurillom',
			'lovor',
			'lukecarbis',
			'm-e-h',
			'm0ze',
			'm_uysl',
			'maedahbatool',
			'mamaduka',
			'manooweb',
			'marekhrabe',
			'mark-k',
			'markjaquith',
			'markoheijnen',
			'markparnell',
			'marybaum',
			'marylauc',
			'matt',
			'mattchowning',
			'matveb',
			'maxpertici',
			'mbabker',
			'mblach',
			'mciampini',
			'mcsf',
			'mdawaffe',
			'meher',
			'melchoyce',
			'meloniq',
			'mensmaximus',
			'metalandcoffee',
			'mhuntdesign',
			'mihdan',
			'mike_cowobo',
			'mikehansenme',
			'mikejolley',
			'milana_cap',
			'miqrogroove',
			'mista-flo',
			'mkaz',
			'mkdgs',
			'moch11',
			'mmuyskens',
			'mmxxi',
			'mohamedfaragallah',
			'monikarao',
			'mor10',
			'mordauk',
			'mrjoeldean',
			'mrpauloen',
			'mte90',
			'mukesh27',
			'munyagu',
			'mweichert',
			'nalininonstopnewsuk',
			'nao',
			'naoki0h',
			'nayanchamp7',
			'netweb',
			'nhuja',
			'nicegamer7',
			'ninanmnm',
			'ninetyninew',
			'noisysocks',
			'nosolosw',
			'notlaura',
			'nrqsnchz',
			'ntsekouras',
			'nvartolomei',
			'oandregal',
			'obenland',
			'ocean90',
			'oglekler',
			'oguzkocer',
			'olafklejnstrupjensen',
			'olgabulat',
			'onemaggie',
			'otshelnik-fm',
			'otto42',
			'oxyrealm',
			'ozh',
			'paaggeli',
			'paaljoachim',
			'pabline',
			'palmiak',
			'paragoninitiativeenterprises',
			'patkemper',
			'patricklindsay',
			'paulschreiber',
			'paulstonier',
			'pavelvisualcomposer',
			'pbearne',
			'pbiron',
			'pento',
			'peterwilsoncc',
			'phena109',
			'philipmjackson',
			'pianist787',
			'pixolin',
			'poena',
			'pondermatic',
			'presskopp',
			'presstoke',
			'priethor',
			'promz',
			'pschrottky',
			'psealock',
			'psrpinto',
			'ptahdunbar',
			'pwallner',
			'pyronaur',
			'quadthemes',
			'rachelbaker',
			'radixweb',
			'rafaelgalani',
			'rafhun',
			'rahmohn',
			'ramiy',
			'ramonopoly',
			'rarst',
			'ravipatel',
			'rellect',
			'renehermi',
			'retrofox',
			'revgeorge',
			'reynhartono',
			'rianrietveld',
			'ribaricplusplus',
			'rima1889',
			'rinatkhaziev',
			'rkradadiya',
			'rmccue',
			'rnaby',
			'robdxw',
			'rogerlos',
			'rogertheriault',
			'roo2',
			'rtm909',
			'ryelle',
			'ryno267',
			'ryokuhi',
			'sabernhardt',
			'sabrinazeidan',
			'sahilmepani',
			'sandipmondal',
			'sanketchodavadiya',
			'sannevndrmeulen',
			'sarahricker',
			'sarayourfriend',
			'sasagar',
			'satrancali',
			'savicmarko1985',
			'schlessera',
			'scottconnerly',
			'scruffian',
			'sean212',
			'seanchayes',
			'sebbb',
			'sephsekla',
			'sergeybiryukov',
			'sergioestevao',
			'sergiomdgomes',
			'shaunandrews',
			'shimon246',
			'shital-patel',
			'silb3r',
			'simison',
			'siobhyb',
			'sirstuey',
			'skithund',
			'snapfractalpop',
			'soean',
			'solarissmoke',
			'soulseekah',
			'spacedmonkey',
			'spikeuk1',
			'spytzo',
			'stacimc',
			'stefanjoebstl',
			'stevegrunwell',
			'stevehenty',
			'stevenkword',
			'stodorovic',
			'strategio',
			'subrataemfluence',
			'sumaiyasiddika',
			'sumanm',
			'sumitsingh',
			'sunxiyuan',
			'sushmak',
			'swissspidy',
			'synchro',
			'szaqal21',
			'talldanwp',
			'tamlyn',
			'tellyworth',
			'terraling',
			'terriann',
			'themes-1',
			'thomas-vitale',
			'thomasplevy',
			'tigertech',
			'tikifez',
			'timothyblynjacobs',
			'timotijhof',
			'tjnowell',
			'tkama',
			'tmatsuur',
			'tmdk',
			'tobiasbg',
			'tobifjellner',
			'toro_unit',
			'torres126',
			'toru',
			'travel_girl',
			'travisnorthcutt',
			'trejder',
			'tw2113',
			'tyxla',
			'tz-media',
			'utsav72640',
			'utz119',
			'vanyukov',
			'vcanales',
			'vdwijngaert',
			'vetyst',
			'vimes1984',
			'vipulc2',
			'vladytimy',
			'vyskoczilova',
			'walbo',
			'wangql',
			'wb1234',
			'webcommsat',
			'webdragon',
			'welcher',
			'wendyjchen',
			'westonruter',
			'wfmattr',
			'whyisjake',
			'wildworks',
			'williampatton',
			'wpgurudev',
			'wphound',
			'wppinar',
			'xavivars',
			'xknown',
			'xkon',
			'y_kolev',
			'yakimun',
			'yansern',
			'youknowriad',
			'yuliyan',
			'yvettesonneveld',
			'zackkrida',
			'zebulan',
			'zieladam',
			'zkancs',
			'zodiac1978',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'http://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'http://getid3.sourceforge.net/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ],
			[ 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'http://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'http://mediaelementjs.com/' ],
			[ 'Moment', 'http://momentjs.com/' ],
			[ 'PclZip', 'http://www.phpconcept.net/pclzip/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'http://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'http://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'http://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'http://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'http://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'http://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

