<?php

class WP_55_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'              => [ 'Matt Mullenweg', 'Release Lead' ],
					'whyisjake'         => [ 'Jake Spurlock', 'Release Lead' ],
					'davidbaumwald'     => [ 'David Baumwald', 'Release Lead' ],
					'SergeyBiryukov'    => 'Sergey Biryukov',
					'ellatrix'          => 'Ella van Durpe',
					'michaelarestad'    => 'Michael Arestad',
					'azaozz'            => 'Andrew Ozz',
					'audrasjb'          => 'Jean-Baptiste Audras',
					'justinahinon'      => 'Justin Ahinon',
					'marybaum'          => 'Mary Baum',
					'flixos90'          => 'Felix Arntz',
					'swissspidy'        => 'Pascal Birchler',
					'pbiron'            => 'Paul Biron',
					'ryelle'            => 'Kelly Dwan',
					'tellyworth'        => 'Alex Shiels',
					'dufresnesteven'    => 'Steve Dufresne',
					'coreymckrill'      => 'Corey McKrill',
					'cbringmann'        => 'Chloé Bringmann',
					'JeffPaul'          => 'Jeff Paul',
					'francina'          => 'Francesca Marano',
					'desrosj'           => 'Jonathan Desrosiers',
					'youknowriad'       => 'Riad Benguella',
					'aduth'             => 'Andrew Duthie',
					'gziolo'            => 'Greg Ziółkowski',
					'talldanwp'         => 'Daniel Richards',
					'jorgefilipecosta'  => 'Jorge Costa',
					'Joen'              => 'Joen Asmussen',
					'epiqueras'         => 'Enrique Piqueras',
					'ocean90'           => 'Dominik Schilling',
					'afercia'           => 'Andrea Fercia',
					'TimothyBlynJacobs' => 'Timothy Jacobs',
					'johnbillion'       => 'John Blackbourn',
					'ianbelanger'       => 'Ian Belanger',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'estelaris'         => 'Estela Rueda',
					'webcommsat'        => 'Abha Thakor',
					'nrqsnchz'          => 'Enrique Sánchez',
					'afragen'           => 'Andy Fragen',
					'Clorith'           => 'Marius Jensen',
					'zebulan'           => 'Zebulan Stanphill',
					'nosolosw'          => 'Andrés Maneiro',
					'itsjonq'           => 'Jon Quach',
					'SergioEstevao'     => 'Sérgio Estêvão',
					'andraganescu'      => 'Andrei Draganescu',
					'mkaz'              => 'Marcus Kazmierczak',
					'noisysocks'        => 'Robert Anderson',
					'noahtallen'        => 'Noah Allen',
					'spacedmonkey'      => 'Jonny Harris',
					'garrett-eclipse'   => 'Garrett Hyder',
					'happiryu'          => 'Luke Walczak',
					'dd32'              => 'Dion Hulse',
					'sabernhardt'       => 'Stephen Bernhardt',
					'ramiy'             => 'Rami Yushuvaev',
					'isabel_brison'     => 'Isabel Brison',
					'mukesh27'          => 'Mukesh Panchal',
					'chanthaboune'      => 'Josepha Haden',
					'annezazu'          => 'Anne McCarthy',
					'angelasjin'        => 'Angela Jin',
					'matveb'            => 'Matias Ventura',
					'mcsf'              => 'Miguel Fonseca',
					'pablohoneyhoney'   => 'Pablo Honey',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'a2hosting',
			'a4jpcom',
			'a6software',
			'aaroncampbell',
			'abderrahman',
			'achbed',
			'achyuthajoy',
			'acosmin',
			'acsnaterse',
			'adamsilverstein',
			'addiestavlo',
			'addyosmani',
			'adnanlimdi',
			'adrian',
			'aduth',
			'afercia',
			'afragen',
			'ahortin',
			'airamerica',
			'ajayghaghretiya1',
			'ajitbohra',
			'ajlende',
			'ajoah',
			'akabarikalpesh',
			'akbarhusen',
			'akbarhusen429',
			'akhileshsabharwal',
			'akirk',
			'akissz',
			'aladin02dz',
			'alexandreb3',
			'ali11007',
			'alishanvr',
			'aljullu',
			'allendav',
			'alshakero',
			'amaschas',
			'anbumz',
			'andfinally',
			'andizer',
			'andraganescu',
			'andreamiddleton',
			'anevins',
			'ankit-k-gupta',
			'ankitmaru',
			'annezazu',
			'antonisme',
			'antpb',
			'apeatling',
			'apedog',
			'archon810',
			'argentite',
			'arpitgshah',
			'asalce',
			'ashiagr',
			'ashour',
			'asif2bd',
			'assassinateur',
			'atachibana',
			'atimmer',
			'audrasjb',
			'aussi',
			'automaton',
			'avixansa',
			'ayeshrajans',
			'azaozz',
			'azhiyadev',
			'backups',
			'barry',
			'barryceelen',
			'bartczyz',
			'bartekcholewa',
			'bartkalisz',
			'bastho',
			'batmoo',
			'bbrdaric',
			'bcworkz',
			'bdbch',
			'bdcstr',
			'beatpanda',
			'bencroskery',
			'benjamingosset',
			'benoitchantre',
			'bernhard-reiter',
			'bettyjj',
			'bgermann',
			'bhargavbhandari90',
			'bigcloudmedia',
			'bigdawggi',
			'billerickson',
			'birgire',
			'bjornw',
			'bmartinent',
			'bobbingwide',
			'boogah',
			'bookdude13',
			'boonebgorges',
			'bpayton',
			'bph',
			'brentswisher',
			'brianhogg',
			'bridgetwillard',
			'bruandet',
			'burhandodhy',
			'caiocrcosta',
			'calvin_ngan',
			'cameronamcintyre',
			'carike',
			'carloslfu',
			'carriganvb',
			'casiepa',
			'cbringmann',
			'cbutlerjr',
			'ceyhun',
			'chesio',
			'chetan200891',
			'chintan1896',
			'chipsnyder',
			'chouby',
			'chriscct7',
			'christian1012',
			'christophherr',
			'chrisvanpatten',
			'chunkysteveo',
			'circlecube',
			'cjbj',
			'cklee',
			'clarinetlord',
			'clayray',
			'claytoncollie',
			'cliffpaulick',
			'clorith',
			'cloudstek',
			'codeforest',
			'coffee2code',
			'commeuneimage',
			'confridin',
			'coolmann',
			'copons',
			'coreymckrill',
			'costasovo',
			'cpasqualini',
			'cristovaov',
			'curtisbelt',
			'cvoell',
			'cyberhobo',
			'cybr',
			'danielbachhuber',
			'danielhuesken',
			'danieltj',
			'darkog',
			'dartiss',
			'davidakennedy',
			'davidanderson',
			'davidbaumwald',
			'davidbinda',
			'davidvee',
			'davilera',
			'davisshaver',
			'dboy1988',
			'dbrumbaugh10up',
			'dchymko',
			'dd32',
			'deepaklalwani',
			'dekervit',
			'delowardev',
			'demetris',
			'dency',
			'denisco',
			'derekakelly',
			'desaiuditd',
			'desmith',
			'desrosj',
			'devesine',
			'dhrrob',
			'dianeco',
			'diddledan',
			'dilipbheda',
			'dimadin',
			'dimitrism',
			'dingo_d',
			'dinhtungdu',
			'djennez',
			'djpaul',
			'dkarfa',
			'dlh',
			'dmchale',
			'dmenard',
			'dmethvin',
			'doc987',
			'donmhico',
			'dono12',
			'dontdream',
			'doobeedoo',
			'dossy',
			'dpacks',
			'dperonne',
			'dratwas',
			'drewapicture',
			'drlightman',
			'drprotocols',
			'drw158',
			'dryanpress',
			'dshanske',
			'dsifford',
			'dsixinetu',
			'dudo',
			'dufresnesteven',
			'dushakov',
			'dustinbolton',
			'dvershinin',
			'earnjam',
			'ebinnion',
			'eddiemoya',
			'eddystile',
			'ediamin',
			'ehtis',
			'ekatherine',
			'ellatrix',
			'elmastudio',
			'elrae',
			'emanuel_blagonic',
			'emlebrun',
			'empireoflight',
			'emrikol',
			'enej',
			'enricosorcinelli',
			'epiqueras',
			'ericlewis',
			'esemlabel',
			'esoj',
			'espiat',
			'estelaris',
			'etoledom',
			'etruel',
			'ev3rywh3re',
			'fabiankaegy',
			'felix-edelmann',
			'ferdiesletering',
			'fftfaisal',
			'fjarrett',
			'fierevere',
			'figureone',
			'finomeno',
			'flixos90',
			'florianatwhodunit',
			'florianbrinkmann',
			'foack',
			'foliovision',
			'folletto',
			'francina',
			'francoist',
			'frank-klein',
			'frankprendergast',
			'franzarmas',
			'fullofcaffeine',
			'functionalrhyme',
			'futtta',
			'gaambo',
			'gadgetroid',
			'galbaras',
			'gamerz',
			'garavani',
			'garethgillman',
			'garrett-eclipse',
			'garubi',
			'garyc40',
			'garyj',
			'gchtr',
			'geertdd',
			'geminilabs',
			'geriux',
			'get_dave',
			'gh640',
			'giorgio25b',
			'gisselfeldt',
			'gitlost',
			'gkloveweb',
			'glendaviesnz',
			'gma992',
			'gmays',
			'goldsounds',
			'gothickgothickorguk',
			'gradina',
			'grapestain',
			'grapplerulrich',
			'greenshady',
			'greglone',
			'gregmulhauser',
			'grierson',
			'grzegorzjanoszka',
			'gsmumbo',
			'guidobras',
			'gwendydd',
			'gwwar',
			'gziolo',
			'h71',
			'hakre',
			'halgatewood',
			'hankthetank',
			'happiryu',
			'hareesh-pillai',
			'haukep',
			'hazdiego',
			'helen',
			'hellofromtonya',
			'henrywright',
			'herregroen',
			'hlanggo',
			'hlashbrooke',
			'hommealone',
			'howdy_mcgee',
			'hronak',
			'huntlyc',
			'hvar',
			'hypest',
			'ianbelanger',
			'iandstewart',
			'iandunn',
			'ianjvr',
			'ibachal',
			'ibdz',
			'ifrins',
			'igorradovanov',
			'imath',
			'infinum',
			'ipstenu',
			'isabel_brison',
			'ishitaka',
			'itowhid06',
			'itsjonq',
			'itsjusteileen',
			'itzmekhokan',
			'iworks',
			'ixkaito',
			'jackfungi',
			'jacklinkers',
			'jadonn',
			'jadpm',
			'jagirbahesh',
			'jainnidhi',
			'jameskoster',
			'janr',
			'janthiel',
			'jarretc',
			'jason_the_adams',
			'jaswsinc',
			'javidalkaruzi',
			'javiercasares',
			'jaz_on',
			'jb510',
			'jbinda',
			'jbouganim',
			'jchristopher',
			'jdgrimes',
			'jdorner',
			'jean-david',
			'jeffpaul',
			'jeffr0',
			'jeherve',
			'jenilk',
			'jenmylo',
			'jeremyfelt',
			'jeremyyip',
			'jeroenrotty',
			'jeryj',
			'jesin',
			'jfarthing84',
			'jffng',
			'jgrodel',
			'jigneshnakrani',
			'jim_panse',
			'jipmoors',
			'jivanpal',
			'jnylen0',
			'joedolson',
			'joehoyle',
			'joemcgill',
			'joen',
			'johannadevos',
			'johnbillion',
			'johnjamesjacoby',
			'johnnyb',
			'johnpgreen',
			'johnstonphilip',
			'johnwatkins0',
			'jonathanstegall',
			'jonkolbert',
			'jonnybot',
			'jonoaldersonwp',
			'jonsurrell',
			'joostdevalk',
			'jorbin',
			'jorgefilipecosta',
			'josephdickson',
			'joshuawold',
			'joyously',
			'jrchamp',
			'jrf',
			'juanfra',
			'juanlopez4691',
			'jules-colle',
			'julianm',
			'juliobox',
			'justinahinon',
			'justlevine',
			'justnorris',
			'kadamwhite',
			'kaggdesign',
			'kaira',
			'kaitlin414',
			'kamataryo',
			'karmatosed',
			'kasparsd',
			'kbjohnson90',
			'kburgoine',
			'kebbet',
			'keesiemeijer',
			'kellybleck',
			'kennethroberson5556',
			'khag7',
			'kharisblank',
			'kinjaldalwadi',
			'kirasong',
			'kirilzh',
			'kishanjasani',
			'kitchin',
			'kittmedia',
			'kjellr',
			'knutsp',
			'koke',
			'kraftbj',
			'kreppar',
			'krogsgard',
			'krstarica',
			'ksoares',
			'kthmd',
			'la-geek',
			'lalitpendhare',
			'landau',
			'larrach',
			'laternastudio',
			'laurelfulford',
			'laxman-prajapati',
			'layotte',
			'leprincenoir',
			'levdbas',
			'lex_robinson',
			'lilmike',
			'linyows',
			'lipathor',
			'littlebigthing',
			'liuhaibin',
			'ljharb',
			'logig',
			'lschuyler',
			'lucasbustamante',
			'lukecavanagh',
			'lukestramasonder',
			'lwill',
			'm_butcher',
			'machouinard',
			'mackensen',
			'madtownlems',
			'mailnew2ster',
			'man4toman',
			'manojlovic',
			'manooweb',
			'mapk',
			'marcio-zebedeu',
			'marcoz',
			'marekdedic',
			'marekhrabe',
			'mariovalney',
			'markdubois',
			'markgoho',
			'markjaquith',
			'markoheijnen',
			'markparnell',
			'markrh',
			'markshep',
			'marktimemedia',
			'markusthiel',
			'martijn-van-der-kooij',
			'martychc23',
			'marybaum',
			'matheusfd',
			'matjack1',
			'matt',
			'mattchowning',
			'mattheweppelsheimer',
			'matthieumota',
			'mattrad',
			'mattyrob',
			'matveb',
			'maximeculea',
			'maxme',
			'maxpertici',
			'mayankmajeji',
			'mboynes',
			'mcsf',
			'mcshane',
			'mdgl',
			'melchoyce',
			'menakas',
			'mensmaximus',
			'metalandcoffee',
			'mfields',
			'michael-arestad',
			'mihai2u',
			'mihdan',
			'miinasikk',
			'mikaumoto',
			'mike-haydon-swo',
			'mikeschinkel',
			'mikeyarce',
			'milana_cap',
			'milindmore22',
			'mimitips',
			'mintindeed',
			'miqrogroove',
			'mislavjuric',
			'mista-flo',
			'miyauchi',
			'mkaz',
			'mnelson4',
			'mohsinrasool',
			'monikarao',
			'mor10',
			'mrgrt',
			'mrmist',
			'mrtall',
			'msafi',
			'msaggiorato',
			'mt8biz',
			'mte90',
			'mukesh27',
			'munyagu',
			'musamamasood',
			'nabilmoqbel',
			'nacin',
			'nalininonstopnewsuk',
			'nao',
			'narwen',
			'nateinaction',
			'nathanrice',
			'navidos',
			'nbachiyski',
			'needle',
			'neodjandre',
			'neonkowy',
			'nerrad',
			'netpassprodsr',
			'netsurfer2705',
			'netweb',
			'netweblogic',
			'nextendweb',
			'nfmohit',
			'nickdaugherty',
			'nickylimjj',
			'nicolaskulka',
			'nielsdeblaauw',
			'nielslange',
			'nigrosimone',
			'nikhilbhansi',
			'nilovelez',
			'niresh12495',
			'nmenescardi',
			'noahtallen',
			'noisysocks',
			'nosolosw',
			'nrqsnchz',
			'ntsekouras',
			'nullbyte',
			'numidwasnotavailable',
			'oakesjosh',
			'obenland',
			'obliviousharmony',
			'ocean90',
			'ockham',
			'offereins',
			'oglekler',
			'omarreiss',
			'onokazu',
			'optimizingmatters',
			'opurockey',
			'otto42',
			'ov3rfly',
			'ovann86',
			'overclokk',
			'p_enrique',
			'paaljoachim',
			'pablohoneyhoney',
			'pacifika',
			'paddy',
			'palmiak',
			'paresh07',
			'parvand',
			'passoniate',
			'paulschreiber',
			'paulstonier',
			'pavelevap',
			'pbearne',
			'pbiron',
			'pcfreak30',
			'pderksen',
			'pdfernhout',
			'pedromendonca',
			'pentatonicfunk',
			'pento',
			'pereirinha',
			'pessoft',
			'peterwilsoncc',
			'pfefferle',
			'philipmjackson',
			'pierlo',
			'pigdog234',
			'pikamander2',
			'pingram3541',
			'pionect',
			'pixelverbieger',
			'piyushmca',
			'pkarjala',
			'pkvillanueva',
			'planningwrite',
			'planvova',
			'pmbaldha',
			'poena',
			'pputzer',
			'pratik028',
			'pravinparmar2404',
			'presskopp',
			'presslabs',
			'priyankkpatel',
			'priyomukul',
			'procifer',
			'prografika',
			'programmin',
			'progremzion',
			'properlypurple',
			'pschrottky',
			'psdtohtmlguru',
			'psykro',
			'puneetsahalot',
			'punitsoftac',
			'pvogel2',
			'quadthemes',
			'r-a-y',
			'raajtram',
			'rahe',
			'raineorshine',
			'rajeshsingh520',
			'ramiy',
			'rarst',
			'rastaban',
			'ravanh',
			'ravatparmar',
			'ravenswd',
			'rawrly',
			'rcutmore',
			'rebasaurus',
			'redsand',
			'regankhadgi',
			'remzicavdar',
			'renathoc',
			'renggo888',
			'retlehs',
			'retrofox',
			'riaanlom',
			'rianrietveld',
			'riasat',
			'richtabor',
			'rilwis',
			'ringisha',
			'ritterml',
			'rmccue',
			'rnaby',
			'rob006',
			'robertpeake',
			'ronalfy',
			'roytanck',
			'rtagliento',
			'ruxandra',
			'ryan',
			'ryankienstra',
			'ryanshoover',
			'ryelle',
			'ryokuhi',
			'ryotasakamoto',
			'ryotsun',
			'sabernhardt',
			'sachittandukar',
			'sagarjadhav',
			'sainthkh',
			'sajjad67',
			'salcode',
			'salvatoreformisano',
			'salvoaranzulla',
			'samful',
			'samueljseay',
			'sanzeeb3',
			'sarahricker',
			'sathyapulse',
			'sayedwp',
			'sc0ttkclark',
			'scarolan',
			'schlessera',
			'scholdstrom',
			'scottsmith',
			'scribu',
			'scruffian',
			'seanchayes',
			'seanpaulrasmussen',
			'seayou',
			'seedsca',
			'senatorman',
			'sergeybiryukov',
			'sergioestevao',
			'sergiomdgomes',
			'seth17',
			'sgr33n',
			'shamai',
			'shaunandrews',
			'shawnz',
			'shiki',
			'shireling',
			'shital-patel',
			'shooper',
			'shulard',
			'siliconforks',
			'simison',
			'simonjanin',
			'simonwheatley',
			'sinatrateam',
			'sippis',
			'sixhours',
			'sjmur',
			'skarabeq',
			'skorasaurus',
			'skoskie',
			'slushman',
			'smub',
			'snapfractalpop',
			'soean',
			'solarissmoke',
			'sorenbronsted',
			'soulseekah',
			'spacedmonkey',
			'sphakka',
			'squarecandy',
			'sreedoap',
			'sstoqnov',
			'sswebster',
			'sswells',
			'starbuck',
			'stephencronin',
			'sterndata',
			'stevegibson12',
			'stevenkussmaul',
			'stevenkword',
			'stevenlinx',
			'stiofansisland',
			'strangerstudios',
			'stuffradio',
			'subrataemfluence',
			'sum1',
			'sunnyratilal',
			'superpoincare',
			'sushyant',
			'suzylah',
			'swissspidy',
			'synchro',
			'szaqal21',
			'szepeviktor',
			'tabrisrp',
			'tacitonic',
			'talldanwp',
			'tangrufus',
			'targz-1',
			'tellyworth',
			'tessawatkinsllc',
			'tferry',
			'tfrommen',
			'themiked',
			'theolg',
			'thimalw',
			'thrijith',
			'tiagohillebrandt',
			'tillkruess',
			'timothyblynjacobs',
			'tkama',
			'tmdesigned',
			'tmoore41',
			'tobiasbg',
			'tobifjellner',
			'tofandel',
			'tollmanz',
			'tomdude',
			'toro_unit',
			'torres126',
			'toru',
			'travisnorthcutt',
			'treecutter',
			'trepmal',
			'truchot',
			'truongwp',
			'tsimmons',
			'tw2113',
			'tweetythierry',
			'twentyzerotwo',
			'utz119',
			'vabrashev',
			'vadimnicolai',
			'vagios',
			'valchovski',
			'valentinbora',
			'vayu',
			'veraxus',
			'veromary',
			'vimes1984',
			'vinayakanivase',
			'vindl',
			'vinkla',
			'virginienacci',
			'vjik',
			'vortfu',
			'voyager131',
			'vtieu',
			'webaware',
			'webcommsat',
			'webdevmattcrom',
			'webzunft',
			'welcher',
			'westi',
			'westonruter',
			'whyisjake',
			'wido',
			'wildworks',
			'williampatton',
			'wittich',
			'wonderboymusic',
			'wpamitkumar',
			'wpdesk',
			'wpdo5ea',
			'wpgurudev',
			'wppinar',
			'wpshades',
			'xknown',
			'xkon',
			'yahil',
			'yakimun',
			'yashrs',
			'yoancutillas',
			'yoavf',
			'yohannp',
			'youknowriad',
			'ysalame',
			'yuhin',
			'yvettesonneveld',
			'zaheerahmad',
			'zakkath',
			'zebulan',
			'zieladam',
			'zodiac1978',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'http://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'http://getid3.sourceforge.net/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ],
			[ 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'http://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'http://mediaelementjs.com/' ],
			[ 'Moment', 'http://momentjs.com/' ],
			[ 'PclZip', 'http://www.phpconcept.net/pclzip/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'http://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'http://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'http://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'http://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'http://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'http://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

