<?php

class WP_51_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'             => [ 'Matt Mullenweg', 'Release Lead' ],
					'pento'            => [ 'Gary Pendergast', 'Release Lead' ],
					'SergeyBiryukov'   => [ 'Sergey Biryukov', 'Core Developer' ],
					'azaozz'           => [ 'Andrew Ozz', 'Core Developer' ],
					'flixos90'         => [ 'Felix Arntz', 'Core Developer' ],
					'johnbillion'      => [ 'John Blackbourn', 'Core Developer' ],
					'peterwilsoncc'    => [ 'Peter Wilson', 'Core Developer' ],
					'jrf'              => [ 'Juliette Reinders Folmer', 'Core Developer' ],
					'desrosj'          => [ 'Jonathan Desrosiers', 'Core Developer' ],
					'melchoyce'        => 'Mel Choyce',
					'schlessera'       => 'Alain Schlesser',
					'soulseekah'       => 'Gennady Kovshenin',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'ryelle'            => 'Kelly Dwan',
					'chetan200891'      => 'Chetan Prajapati',
					'mukesh27'          => 'Mukesh Panchal',
					'birgire'           => 'Birgir Erlendsson',
					'netweb'            => 'Stephen Edgar',
					'afercia'           => 'Andrea Fercia',
					'atimmer'           => 'Anton Timmermans',
					'herregroen'        => 'Herre Groen',
					'jorbin'            => 'Aaron Jorbin',
					'kadamwhite'        => 'K.Adam White',
					'ocean90'           => 'Dominik Schilling',
					'DrewAPicture'      => 'Drew Jaynes',
					'boonebgorges'      => 'Boone Gorges',
					'joemcgill'         => 'Joe McGill',
					'subrataemfluence'  => 'Subrata Sarkar',
					'ireneyoast'        => 'Irene Strikkers',
					'audrasjb'          => 'Jb Audras',
					'Rarst'             => 'Andrey Savchenko',
					'omarreiss'         => 'Omar Reiss',
					'mcsf'              => 'Miguel Fonseca',
					'gziolo'            => 'Grzegorz Ziółkowski',
					'youknowriad'       => 'Riad Benguella',
					'iseulde'           => 'Ella Van Durpe',
					'aduth'             => 'Andrew Duthie',
					'jorgefilipecosta'  => 'Jorge Costa',
					'mkaz'              => 'Marcus Kazmierczak',
					'kjellr'            => 'Kjell Reigstad',
					'nosolosw'          => 'Andrés Maneiro',
					'TimothyBlynJacobs' => 'Timothy Jacobs',
					'nerrad'            => 'Darren Ethier',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0x6f0',
			'1265578519-1',
			'1naveengiri',
			'360zen',
			'aardrian',
			'abdullahramzan',
			'abhayvishwakarma',
			'abhijitrakas',
			'achbed',
			'acirujano',
			'adamsilverstein',
			'aduth',
			'afercia',
			'afragen',
			'ajitbohra',
			'aldavigdis',
			'alejandroxlopez',
			'alexgso',
			'alexstine',
			'alexvorn2',
			'allancole',
			'allendav',
			'alvarogois',
			'anantajitjg',
			'andg',
			'andizer',
			'andreamiddleton',
			'andrei0x309',
			'andreiglingeanu',
			'andrewza',
			'anevins',
			'antaltettinger',
			'antipole',
			'antonioeatgoat',
			'aranwer104',
			'aryamaaru',
			'ashokrd2013',
			'atimmer',
			'audrasjb',
			'avillegasn',
			'ayeshrajans',
			'ayubadiputra',
			'azaozz',
			'bamadesigner',
			'bandonrandon',
			'barryceelen',
			'behzod',
			'benhuberman',
			'benoitchantre',
			'benvaassen',
			'bhargavmehta',
			'bikecrazyy',
			'birgire',
			'bjornw',
			'blair-jersyer',
			'blobfolio',
			'bobbingwide',
			'boblinthorst',
			'boda1982',
			'boemedia',
			'boonebgorges',
			'bor0',
			'bpayton',
			'bradleyt',
			'bradparbs',
			'bramheijmink',
			'brentswisher',
			'bridgetwillard',
			'bruceallen',
			'bulletdigital',
			'burhandodhy',
			'burlingtonbytes',
			'calin',
			'campusboy1987',
			'carolinegeven',
			'casiepa',
			'ccismaru',
			'celloexpressions',
			'chasewg',
			'cheffheid',
			'chetan200891',
			'chouby',
			'chrico',
			'chriscct7',
			'clarinetlord',
			'claudiu',
			'cliffpaulick',
			'clorith',
			'codegrau',
			'codestor',
			'coffee2code',
			'coleh',
			'conner_bw',
			'coreymckrill',
			'croce',
			'cthreelabs',
			'daniel-koskinen',
			'danielbachhuber',
			'danieltj',
			'danimalbrown',
			'dannycooper',
			'dannydehaan',
			'darko-a7',
			'davepullig',
			'davidakennedy',
			'davidanderson',
			'davidbinda',
			'dd32',
			'dekervit',
			'denisco',
			'desertsnowman',
			'designsimply',
			'desrosj',
			'dfangstrom',
			'dglingren',
			'dhanendran',
			'dharm1025',
			'dhavalkasvala',
			'dhruvin',
			'diedeexterkate',
			'dilipbheda',
			'dimadin',
			'dingo_d',
			'dipeshkakadiya',
			'dlh',
			'dmsnell',
			'donncha',
			'dontstealmyfish',
			'drewapicture',
			'drivingralle',
			'drywallbmb',
			'dschalk',
			'dshanske',
			'dsifford',
			'dyrer',
			'eamax',
			'earnjam',
			'eartboard',
			'edo888',
			'edocev',
			'electricfeet',
			'ericdaams',
			'erich_k4wp',
			'ericlewis',
			'ericmeyer',
			'ethitter',
			'etoledom',
			'evansolomon',
			'faisal03',
			'fclaussen',
			'felipeelia',
			'fierevere',
			'flipkeijzer',
			'flixos90',
			'fpcsjames',
			'frank-klein',
			'fuchsws',
			'fullyint',
			'garetharnold',
			'garrett-eclipse',
			'garyj',
			'girishpanchal',
			'gm_alex',
			'gma992',
			'gnif',
			'grapplerulrich',
			'graymouser',
			'greatislander',
			'greenshady',
			'greg',
			'guido07111975',
			'gutendev',
			'gziolo',
			'hafiz',
			'hailite',
			'hansjovisyoast',
			'hardeepasrani',
			'hardik-amipara',
			'harsh175',
			'haruharuharuby',
			'hedgefield',
			'helen',
			'henrywright',
			'herregroen',
			'hitendra-chopda',
			'iamfriendly',
			'ianbelanger',
			'iandunn',
			'ibachal',
			'ibantxillo',
			'ibenic',
			'icaleb',
			'iceable',
			'idea15',
			'igmoweb',
			'igorsch',
			'imath',
			'ionvv',
			'ireneyoast',
			'isabel104',
			'iseulde',
			'ishitaka',
			'itowhid06',
			'ixkaito',
			'j-falk',
			'jackreichert',
			'jainnidhi',
			'jakept',
			'jamosova',
			'janak007',
			'janalwin',
			'jankimoradiya',
			'janthiel',
			'jaswrks',
			'javorszky',
			'jaydeep-rami',
			'jaymanpandya',
			'jdgrimes',
			'jeffpaul',
			'jeherve',
			'jeremeylduvall',
			'jeremyescott',
			'jeremyfelt',
			'jesperher',
			'jfarthing84',
			'jipmoors',
			'jirihon',
			'jjcomack',
			'jmdodd',
			'jnylen0',
			'joanrho',
			'jobthomas',
			'joedolson',
			'joehoyle',
			'joelcj91',
			'joemcgill',
			'joen',
			'johnalarcon',
			'johnbillion',
			'johnjamesjacoby',
			'johnny5',
			'johnpgreen',
			'johnschulz',
			'joneiseman',
			'joostdevalk',
			'jorbin',
			'jorgefilipecosta',
			'josephscott',
			'joshuawold',
			'joyously',
			'jpry',
			'jpurdy647',
			'jrchamp',
			'jrdelarosa',
			'jrf',
			'jryancard',
			'jtsternberg',
			'juiiee8487',
			'juliemoynat',
			'junaidkbr',
			'justinsainton',
			'kadamwhite',
			'kapteinbluf',
			'karmatosed',
			'keesiemeijer',
			'kelvink',
			'khaihong',
			'kiranpotphode',
			'kirasong',
			'kjellr',
			'kkarpieszuk',
			'kloon',
			'kmeze',
			'knutsp',
			'konainm',
			'kraftbj',
			'kristastevens',
			'krutidugade',
			'kwonye',
			'la-geek',
			'laghee',
			'lakenh',
			'lancewillett',
			'lanche86',
			'larrach',
			'laurelfulford',
			'lbenicio',
			'leanderiversen',
			'leemon',
			'lenasterg',
			'lisannekluitmans',
			'littlebigthing',
			'littlerchicken',
			'lizkarkoski',
			'lonelyvegan',
			'lorenzone92',
			'lucagrandicelli',
			'lucasrolff',
			'luciano-croce',
			'lukecarbis',
			'luminus',
			'maartenleenders',
			'macbookandrew',
			'mako09',
			'manikmist09',
			'manuel_84',
			'manuelaugustin',
			'marcelo2605',
			'marcomarsala',
			'marcomartins',
			'marcwieland95',
			'mariovalney',
			'mariusvw',
			'markjaquith',
			'mathieuhays',
			'mattyrob',
			'mbelchev',
			'mboynes',
			'mcmwebsol',
			'mcsf',
			'meatman89fs',
			'melchoyce',
			'mensmaximus',
			'mermel',
			'metalandcoffee',
			'metodiew',
			'mgibbs189',
			'michielatyoast',
			'mihaiiceyro',
			'mihdan',
			'mikegillihan',
			'mikejolley',
			'milana_cap',
			'milindmore22',
			'mirkoschubert',
			'mirucon',
			'miss_jwo',
			'mista-flo',
			'miyauchi',
			'mkaz',
			'mmaumio',
			'mmtr86',
			'mnelson4',
			'monikarao',
			'mrasharirfan',
			'mrmadhat',
			'mrtortai',
			'mt8biz',
			'mte90',
			'mukesh27',
			'munklefish',
			'munyagu',
			'mythemeshop',
			'mzorz',
			'nacin',
			'nadim0988',
			'nahuelmahe',
			'nandorsky',
			'nao',
			'naoki0h',
			'natacado',
			'nataliashitova',
			'nateallen',
			'nathanatmoz',
			'ndavison',
			'ndiego',
			'nerrad',
			'netweb',
			'nextendweb',
			'nick_thegeek',
			'nickmomrik',
			'nicollle',
			'nielslange',
			'nikeo',
			'nikschavan',
			'noisysocks',
			'nosolosw',
			'notnownikki',
			'obenland',
			'ocean90',
			'odysseygate',
			'omarreiss',
			'othellobloke',
			'otto42',
			'ov3rfly',
			'paaljoachim',
			'palmiak',
			'panchen',
			'parbaugh',
			'paulschreiber',
			'pbearne',
			'pbiron',
			'pento',
			'peterwilsoncc',
			'piewp',
			'piyush9100',
			'pmbaldha',
			'poena',
			'pputzer',
			'pratikkry',
			'pratikthink',
			'precies',
			'presskopp',
			'presslabs',
			'presstigers',
			'professor44',
			'programmin',
			'promz',
			'pross',
			'pskli',
			'punit5658',
			'purnendu',
			'qcmiao',
			'rabmalin',
			'rachelbaker',
			'rafsuntaskin',
			'rahulsprajapati',
			'ramiy',
			'ramizmanked',
			'ramonopoly',
			'rarst',
			'ravanh',
			'redcastor',
			'remyvv',
			'rensw90',
			'rhetorical',
			'rianrietveld',
			'rickalee',
			'rinkuyadav999',
			'rishishah',
			'rmccue',
			'robbie505',
			'robdxw',
			'robinvandervliet',
			'ryelle',
			'ryotsun',
			'rzen',
			'sagarnasit',
			'samikeijonen',
			'sasiddiqui',
			'sayedwp',
			'schlessera',
			'scottlee',
			'seanchayes',
			'sebakurzyn',
			'sebastianpisula',
			'sebastienserre',
			'sebastienthivinfocom',
			'sephsekla',
			'sergeybiryukov',
			'shamim51',
			'shaneeckert',
			'sharaz',
			'shashwatmittal',
			'sherwood',
			'shital-patel',
			'shivapoudel',
			'shooper',
			'sivel',
			'sjardo',
			'skoldin',
			'skostadinov',
			'slilley',
			'slushman',
			'soean',
			'sonjaleix',
			'sonjanyc',
			'soulseekah',
			'spacedmonkey',
			'spartank',
			'spyderbytes',
			'sstoqnov',
			'stazdotio',
			'stephenharris',
			'stevenlinx',
			'stodorovic',
			'stormrockwell',
			'strategio',
			'subrataemfluence',
			'superdav42',
			'superpoincare',
			'swift',
			'swissspidy',
			'takahashi_fumiki',
			'talldanwp',
			'teddytime',
			'tellyworth',
			'terriann',
			'terwdan',
			'tferry',
			'tfrommen',
			'tharsheblows',
			'themezee',
			'thomas-vitale',
			'thomasplevy',
			'thomaswm',
			'thrijith',
			'tiagohillebrandt',
			'tigertech',
			'timhavinga',
			'timmydcrawford',
			'timothyblynjacobs',
			'tinkerbelly',
			'titodevera',
			'tjnowell',
			'tkama',
			'tlovett1',
			'tobifjellner',
			'tomdxw',
			'tomharrigan',
			'tonybogdanov',
			'torontodigits',
			'transl8or',
			'travel_girl',
			'tz-media',
			'upadalavipul',
			'usmankhalid',
			'utsav72640',
			'uttam007',
			'vaishalipanchal',
			'valchovski',
			'valer1e',
			'vanyukov',
			'vishaldodiya',
			'vnsavage',
			'voneff',
			'vortfu',
			'walbo',
			'warmlaundry',
			'wbrubaker',
			'webdevmattcrom',
			'welcher',
			'westonruter',
			'whyisjake',
			'williampatton',
			'wizzard_',
			'wpscholar',
			'wpzinc',
			'xhezairi',
			'xknown',
			'xkon',
			'xparham',
			'xpertone',
			'xyfi',
			'yahil',
			'yoavf',
			'youknowriad',
			'yuriv',
			'zanematthew',
			'zebulan',
			'zottto',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'http://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'http://getid3.sourceforge.net/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ],
			[ 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'http://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'http://mediaelementjs.com/' ],
			[ 'Moment', 'http://momentjs.com/' ],
			[ 'PclZip', 'http://www.phpconcept.net/pclzip/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'http://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'http://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'http://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'http://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'http://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'http://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

