<?php

class WP_59_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                => [ 'Matt Mullenweg', 'Release Lead' ],
					'hellofromTonya'      => [ 'Tonya Mork', 'Release Lead' ],
					'noisysocks'          => [ 'Robert Anderson', 'Release Lead' ],
					'Mamaduka'            => [ 'George Mamadashvili', 'Release Lead' ],
					'audrasjb'            => 'Jean-Baptiste Audras',
 					'mkaz'                => 'Marcus Kazmierczak',
					'kjellr'              => 'Kjell Reigstad',
					'jffng'               => 'Jeff Ong',
					'chanthaboune'        => 'Josepha Haden',
					'marybaum'            => 'Mary Baum',
					'webcommsat'          => 'Abha Thakor',
					'annezazu'            => 'Anne McCarthy',
					'Boniu91'             => 'Piotrek Boniu',
					'psykro'              => 'Jonathan Bossenger',
					'chaion07'            => 'Ahmed Chaion',
					'milana_cap'          => 'Milana Cap',
					'matveb'              => 'Matias Ventura',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'jrf'                 => 'Juliette Reinders Folmer',
					'desrosj'             => 'Jonathan Desrosiers',
					'youknowriad'         => 'Riad Benguella',
					'ntsekouras'          => 'Nik Tsekouras',
 					'Joen'                => 'Joen Asmussen',
					'sabernhardt'         => 'Stephen Bernhardt',
					'mciampini'           => 'Marco Ciampini',
					'peterwilsoncc'       => 'Peter Wilson',
					'costdev'             => 'Colin Stewart',
					'spacedmonkey'        => 'Jonny Harris',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'oandregal'           => 'André',
					'ellatrix'            => 'Ella van Durpe',
					'johnbillion'         => 'John Blackbourn',
					'talldanwp'           => 'Daniel Richards',
					'get_dave'            => 'David Smith',
					'jorgefilipecosta'    => 'Jorge Costa',
					'glendaviesnz'        => 'Glen Davies',
					'kevinfodness'        => 'Kevin Fodness',
					'zieladam'            => 'Adam Zielinski',
					'aristath'            => 'Ari Stathopoulos',
					'kevin940726'         => 'Kai Hao',
					'carlosgprim'         => 'Carlos Garcia',
					'azaozz'              => 'Andrew Ozz',
					'isabel_brison'       => 'Isabel Brison',
					'poena'               => 'Carolina Nymark',
					'mukesh27'            => 'Mukesh Panchal',
					'geriux'              => 'Gerardo Pacheco',
					'beafialho'           => 'Beatriz Fialho',
					'pablohoneyhoney'     => 'Pablo Honey',
					'nalininonstopnewsuk' => 'Nalini Thakor',
					'kellychoffman'       => 'Kelly Hoffman',
					'joedolson'           => 'Joe Dolson',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'dpcalhoun'           => 'David Calhoun',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'2linctools',
			'aadilali',
			'aaroncampbell',
			'aaronrobertshaw',
			'abesell132',
			'acosmin',
			'adam3128',
			'adamsilverstein',
			'addiestavlo',
			'aduth',
			'aetherunbound',
			'aezazshekh',
			'afercia',
			'afragen',
			'ajlende',
			'ajotka',
			'akabarikalpesh',
			'alanjacobmathew',
			'alexeydemidov',
			'alexislloyd',
			'alexstine',
			'alexvorn2',
			'algala',
			'aliakseyenkaihar',
			'aljullu',
			'allerune',
			'almendron',
			'alshakero',
			'amandariu',
			'amethystanswers',
			'amieiro',
			'amustaque97',
			'anandau14',
			'andraganescu',
			'andrewserong',
			'andy-schmidt',
			'andynick',
			'anevins',
			'anjanavasan',
			'ankit-k-gupta',
			'ankitmaru',
			'annezazu',
			'anthonyeden',
			'antonisme',
			'antonvlasenko',
			'antonynz',
			'antpb',
			'apeatling',
			'arena',
			'aristath',
			'arthur791004',
			'ashfame',
			'asif2bd',
			'assassinateur',
			'atachibana',
			'audrasjb',
			'ayeshrajans',
			'azaozz',
			'azhiyadev',
			'azouamauriac',
			'baelx',
			'bartoszgrzesik',
			'beafialho',
			'beaulebens',
			'bedas',
			'benitolopez',
			'benjaminanakena',
			'benjamingosset',
			'bernhard-reiter',
			'bgardner',
			'bgoewert',
			'bijayyadav',
			'binarykitten',
			'binarymoon',
			'birgire',
			'bjorsch',
			'blogaid',
			'bobbingwide',
			'boniu91',
			'boonebgorges',
			'bosconiandynamics',
			'bph',
			'bradleyt',
			'bradparbs',
			'bravokeyl',
			'briceduclos',
			'bronsonquick',
			'brylie',
			'calebwoodbridge',
			'callye',
			'carepsules',
			'carike',
			'carlosgprim',
			'cbravobernal',
			'cbringmann',
			'cdyerkes',
			'celloexpressions',
			'ceyhun0',
			'chaion07',
			'chanthaboune',
			'chiaki',
			'chintan1896',
			'chipsnyder',
			'chouby',
			'chriscct7',
			'christianztamayo',
			'chrisvanpatten',
			'chthnc',
			'circlecube',
			'cklosows',
			'clorith',
			'clucasrowlands',
			'codezen8',
			'collizo4sky',
			'colorful-tones',
			'computerguru',
			'copons',
			'coreyw',
			'costdev',
			'courane01',
			'cr0ybot',
			'craigfrancis',
			'critterverse',
			'cybr',
			'czapla',
			'daisyo',
			'danfarrow',
			'danielbachhuber',
			'danieldudzic',
			'danielpost',
			'dansoschin',
			'darerodz',
			'dariak',
			'daschmi',
			'datagutten',
			'datainterlock',
			'davecpage',
			'davidanderson',
			'davidbaumwald',
			'davidbinda',
			'davidkryzaniak',
			'davidmosterd',
			'davidszabo',
			'davidwebca',
			'daviedr',
			'dd32',
			'deepaklalwani',
			'denisco',
			'desaiuditd',
			'desrosj',
			'devnel',
			'devutpol',
			'dgwyer',
			'dhanendran',
			'dhusakovic',
			'diedeexterkate',
			'dilipbheda',
			'dimadin',
			'dingo_d',
			'dinhtungdu',
			'dkarfa',
			'dlh',
			'dlt101',
			'dmsnell',
			'dolphingg',
			'domainsupport',
			'donmhico',
			'dontgo2sleep',
			'dougwollison',
			'dpcalhoun',
			'dpegasusm',
			'dratwas',
			'drewapicture',
			'drosmog',
			'dryanpress',
			'dufresnesteven',
			'dustinrue',
			'earnjam',
			'eddystile',
			'ehtis',
			'eidolonnight',
			'ekojr',
			'ellatrix',
			'ellenbauer',
			'empatogen',
			'enchiridion',
			'enej',
			'engelen',
			'erayalakese',
			'ethitter',
			'etoledo',
			'evermail',
			'fabiankaegy',
			'faisal03',
			'fcolombo',
			'fedepia',
			'felipeelia',
			'felipeloureirosantos',
			'fierevere',
			'firewatch',
			'flixos90',
			'fpcsjames',
			'francina',
			'fullofcaffeine',
			'gaambo',
			'gadhiyaravi',
			'galbaras',
			'garrett-eclipse',
			'garyj',
			'gazchap',
			'generosus',
			'georgestephanis',
			'geriux',
			'get_dave',
			'gilbitron',
			'gkloveweb',
			'glendaviesnz',
			'goldsounds',
			'gorby31',
			'grantmkin',
			'greatislander',
			'greenshady',
			'gregrickaby',
			'guillaumeturpin',
			'gwwar',
			'gziolo',
			'h71',
			'hansjovisyoast',
			'haosun',
			'hareesh-pillai',
			'hasanuzzamanshamim',
			'hazdiego',
			'hellofromtonya',
			'henrywright',
			'herbmiller',
			'hermpheus',
			'herregroen',
			'hilayt24',
			'hirofumi2012',
			'hitendra-chopda',
			'hlashbrooke',
			'htmgarcia',
			'hudson-atwell',
			'hugod',
			'hypest',
			'iaaxpage',
			'ianatkins',
			'ianbelanger',
			'iandunn',
			'ianhayes94',
			'ianmjones',
			'ibenic',
			'icaleb',
			'ignatggeorgiev',
			'ilovecats7',
			'iluy',
			'infected',
			'ipstenu',
			'ironprogrammer',
			'isabel_brison',
			'ismaeld',
			'itsamoreh',
			'iulia-cazan',
			'jackreichert',
			'jainnidhi',
			'jakubtyrcha',
			'jameskoster',
			'janthiel',
			'janwoostendorp',
			'javiarce',
			'javiercasares',
			'jayupadhyay01',
			'jblz',
			'jdgrimes',
			'jdy68',
			'jeffpaul',
			'jeherve',
			'jeremyescott',
			'jeremyfelt',
			'jeremyyip',
			'jffng',
			'jigneshnakrani',
			'joedolson',
			'joegasper',
			'joelcj91',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnillo',
			'johnjamesjacoby',
			'johnny5',
			'johnstonphilip',
			'jonoaldersonwp',
			'joostdevalk',
			'jorbin',
			'jorgefilipecosta',
			'josephdickson',
			'josklever',
			'joyously',
			'jrf',
			'jsnajdr',
			'jsnjohnston',
			'juanmaguitar',
			'juanruitina',
			'juhise',
			'junaidbhura',
			'justinahinon',
			'justindocanto',
			'kadamwhite',
			'kafleg',
			'kallookoo',
			'kaneva',
			'kapilpaul',
			'karmatosed',
			'karpstrucking',
			'kebbet',
			'kellychoffman',
			'keoshi',
			'kevin940726',
			'kevinfodness',
			'keyur5',
			'kharisblank',
			'kingkero',
			'kirasong',
			'kjellr',
			'knutsp',
			'kraftbj',
			'kreppar',
			'kurudrive',
			'kwisatz',
			'kzeni',
			'la-geek',
			'lalitjalandhar',
			'laurelfulford',
			'laxman-prajapati',
			'leemon',
			'leogermani',
			'lgladdy',
			'liammitchell',
			'linux4me2',
			'littlebigthing',
			'loranrendel',
			'lucasw89',
			'lucatume',
			'lukecarbis',
			'lukecavanagh',
			'luminuu',
			'luovalabs',
			'lwangaman',
			'lynk',
			'macmanx',
			'madeinua',
			'mahype',
			'mai21',
			'malae',
			'malinevskiy',
			'malthert',
			'mamaduka',
			'manfcarlo',
			'manishamakhija',
			'manooweb',
			'manzoorwanijk',
			'marekhrabe',
			'mark-k',
			'marybaum',
			'mattchowning',
			'mattoakley',
			'mattwiebe',
			'matveb',
			'max-dayala',
			'maximeculea',
			'mburridge',
			'mciampini',
			'mcjambi',
			'mclaurent',
			'mcsf',
			'mdawaffe',
			'medusor',
			'megphillips91',
			'meher',
			'melchoyce',
			'mgol',
			'mhuntdesign',
			'michelwppi',
			'mikachan',
			'mikaelmayer',
			'mikejolley',
			'milana_cap',
			'mista-flo',
			'mitogh',
			'mjaschen',
			'mjulian7',
			'mkaz',
			'mmxxi',
			'mnelson4',
			'moch11',
			'monikarao',
			'mreishus',
			'mrjoeldean',
			'mt8biz',
			'mte90',
			'mtoensing',
			'muhammadfaizanhaidar',
			'mukesh27',
			'multidots1896',
			'musabshakeel',
			'nacin',
			'nalininonstopnewsuk',
			'namithjawahar',
			'nao',
			'natewr',
			'ndiego',
			'nekojonez',
			'nettsite',
			'netweb',
			'nickcernis',
			'nico23',
			'nidhidhandhukiya',
			'nielslange',
			'nikschavan',
			'nlpro',
			'noisysocks',
			'nomnom99',
			'nosolosw',
			'nrqsnchz',
			'ntsekouras',
			'nukaga',
			'oandregal',
			'obenland',
			'ocean90',
			'ockham',
			'oglekler',
			'omaeyusuke',
			'omarreiss',
			'onemaggie',
			'opr18',
			'opurockey',
			'otto42',
			'ov3rfly',
			'ovann86',
			'ovidiul',
			'paaljoachim',
			'pabline',
			'palmiak',
			'pankajmohale',
			'paranoia1906',
			'patrick-b',
			'paulschreiber',
			'pbearne',
			'pbiron',
			'pbking',
			'pedromendonca',
			'pento',
			'petaryoast',
			'peterwilsoncc',
			'pgpagely',
			'philipmjackson',
			'pierlo',
			'piewp',
			'pls78',
			'poena',
			'powerbuoy',
			'pputzer',
			'praem90',
			'presskopp',
			'presstoke',
			'priethor',
			'procodewp',
			'promz',
			'pschrottky',
			'psealock',
			'psmits1567',
			'psrpinto',
			'psufan',
			'pwtyler',
			'pyrobd',
			'rachelbaker',
			'radixweb',
			'rafiahmedd',
			'rahmohn',
			'rainbowgeek',
			'ralucastn',
			'ramonopoly',
			'raubvogel',
			'ravipatel',
			'rbrishabh',
			'rehanali',
			'renathoc',
			'retrofox',
			'revgeorge',
			'rhnsharma',
			'rianrietveld',
			'ribaricplusplus',
			'richardfoley',
			'richards1052',
			'richtabor',
			'richybkreckel',
			'rickcurran',
			'rixeo',
			'rkohilakis',
			'rmartinezduque',
			'robertghetau',
			'robtarr',
			'rohan013',
			'rolfsiebers',
			'ronakganatra',
			'rsiddharth',
			'rtm909',
			'rudlinkon',
			'rufus87',
			'russhylov',
			'rviscomi',
			'ryelle',
			'ryokuhi',
			'rzen',
			'sabbirshouvo',
			'sabernhardt',
			'sabrib',
			'saju4wordpress',
			'sandipmondal',
			'sanketchodavadiya',
			'sarayourfriend',
			'sathyapulse',
			'savicmarko1985',
			'sayedulsayem',
			'schlessera',
			'scribu',
			'scruffian',
			'seanmcmillan',
			'sebastianpisula',
			'sebastienserre',
			'seedsca',
			'sergeybiryukov',
			'sergiocinos',
			'sergioestevao',
			'shaharyar10',
			'shaunandrews',
			'shimon246',
			'shimotomoki',
			'shireling',
			'shital-patel',
			'shivapoudel',
			'shohag121',
			'sierratr',
			'siliconforks',
			'simonhammes',
			'siobhan',
			'siobhyb',
			'sirreal',
			'sjlevy',
			'skierpage',
			'skorasaurus',
			'skunkbad',
			'smit08',
			'snapfractalpop',
			'soean',
			'solarissmoke',
			'soniakash',
			'soulseekah',
			'sourav926',
			'sourovroy',
			'spacedmonkey',
			'sparklingrobots',
			'spytzo',
			'ssergei',
			'staatic',
			'stacimc',
			'starbuck',
			'stevegs',
			'stevehenty',
			'stormrockwell',
			'strider72',
			'swb1192',
			'swissspidy',
			'synchro',
			'szaqal21',
			'szepeviktor',
			'tacoverdo',
			'takahashi_fumiki',
			'talldanwp',
			'tareiking',
			'teachlynx',
			'tellyworth',
			'terraling',
			'terriann',
			'teucrium',
			'themiked',
			'thimalw',
			'thisiswilliam',
			'thomasplevy',
			'thulshof',
			'timlappe',
			'timothyblynjacobs',
			'titsmaker',
			'tjcafferkey',
			'tmatsuur',
			'tnolte',
			'tobiasbg',
			'tobifjellner',
			'tomalec',
			'toro_unit',
			'travisnorthcutt',
			'ttahmouch',
			'tubys',
			'tw2113',
			'tweetythierry',
			'twstokes',
			'tyxla',
			'umesh84',
			'utz119',
			'vcanales',
			'vdwijngaert',
			'versusbassz',
			'vimes1984',
			'vishitshah',
			'vladytimy',
			'vondelphia',
			'vortfu',
			'walbo',
			'wb1234',
			'webaxones',
			'webcommsat',
			'webmandesign',
			'webtechpooja',
			'webulous',
			'welcher',
			'west7',
			'westonruter',
			'wetah',
			'wfmattr',
			'whyisjake',
			'wildworks',
			'williampatton',
			'wojsmol',
			'woodyhayday',
			'wp_kc',
			'wparslan',
			'wpmudev-support8',
			'wpnomad',
			'wppunk',
			'wpscholar',
			'wpsoul',
			'wpweaver',
			'xknown',
			'xkon',
			'yagniksangani',
			'youknowriad',
			'yvettesonneveld',
			'zaguiini',
			'zebulan',
			'zenithcity',
			'zeo',
			'zieladam',
			'zodiac1978',
			'zoiec',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'http://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'http://getid3.sourceforge.net/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ],
			[ 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'http://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'http://mediaelementjs.com/' ],
			[ 'Moment', 'http://momentjs.com/' ],
			[ 'PclZip', 'http://www.phpconcept.net/pclzip/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'http://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'http://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'http://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'http://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'http://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'http://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

