<?php

class WP_50_Credits extends WP_Credits {

    function groups() {
        $groups = array(
            'core-developers' => array(
                'name'    => 'Noteworthy Contributors',
                'type'    => 'titles',
                'shuffle' => false,
                'data'    => array(
                    'matt'             => array( 'Matt Mullenweg',           'Release Lead' ),
                    'allancole'        => array( 'Allan Cole',               'Release Lead' ),
                    'antpb'            => array( 'Anthony Burcell',          'Release Lead' ),
                    'pento'            => array( 'Gary Pendergast',          'Release Lead' ),
                    'chanthaboune'     => array( 'Josepha Haden Chomphosy',  'Release Lead' ),
                    'laurelfulford'    => array( 'Laurel Fulford',           'Release Lead' ),
                    'omarreiss'        => array( 'Omar Reiss',               'Release Lead' ),
                    'danielbachhuber'  => array( 'Daniel Bachhuber',         'Release Lead' ),
                    'matveb'           => array( 'Matías Ventura',           'Release Lead' ),
                    'mcsf'             => array( 'Miguel Fonseca',           'Release Lead' ),
                    'karmatosed'       => array( 'Tammie Lister',            'Release Lead' ),
                    'lonelyvegan'      => array( 'Matthew Riley MacPherson', 'Release Lead' ),
                    'adamsilverstein'  => array( 'Adam Silverstein',       'Core Developer' ),
                    'aduth'            => array( 'Andrew Duthie',          'Core Developer' ),
                    'bpayton'          => array( 'Brandon Payton',         'Core Developer' ),
                    'gziolo'           => array( 'Grzegorz Ziółkowski',    'Core Developer' ),
                    'iseulde'          => array( 'Ella Iseulde Van Dorpe', 'Core Developer' ),
                    'joen'             => array( 'Joen Asmussen',          'Core Developer' ),
                    'jorgefilipecosta' => array( 'Jorge Costa',            'Core Developer' ),
                    'talldan'          => array( 'Daniel Richards',        'Core Developer' ),
                    'youknowriad'      => array( 'Riad Benguella',         'Core Developer' ),
                    'alexislloyd'      => 'Alexis Lloyd',
                    'kjellr'           => 'Kjell Reigstad',
                    'netweb'           => 'Stephen Edgar',
                ),
            ),
             'contributing-developers' => array(
                'name'    => false,
                'type'    => 'titles',
                'shuffle' => true,
                'data'    => array(
                    'davidakennedy' => 'David Kennedy',
                    'atimmer'       => 'Anton Timmer',
                    'melchoyce'     => 'Mel Choyce',
                    'herregroen'    => 'Herre Groen',
                    'peterwilsoncc' => 'Peter Wilson',
                    'jorbin'        => 'Aaron Jorbin',
                    'kadamwhite'    => 'K.Adam White',
                    'ocean90'       => 'Dominik Schilling',
                    'drewapicture'  => 'Drew Jaynes',
                    'flixos90'      => 'Felix Arntz',
                    'johnbillion'   => 'John Blackbourn',
                    'boonebgorges'  => 'Boone Gorges',
                ),
            ),
        );

        return $groups;
    }

    function props() {
        return array(
            '0mirka00',
            'abdullahramzan',
            'abdulwahab610',
            'abhijitrakas',
            'adamsilverstein',
            'aduth',
            'afercia',
            'afraithe',
            'ahmadawais',
            'airathalitov',
            'ajitbohra',
            'albertomedina',
            'aldavigdis',
            'alexis',
            'alexislloyd',
            'alexsanford1',
            'allancole',
            'amedina',
            'ameeker',
            'andreamiddleton',
            'andreiglingeanu',
            'andrewserong',
            'andrewtaylor-1',
            'androb',
            'anevins',
            'annaharrison',
            'antpb',
            'apeatling',
            'aprakasa',
            'arnaudban',
            'arshidkv12',
            'artisticasad',
            'arush',
            'asvinballoo',
            'atanasangelovdev',
            'atimmer',
            'audrasjb',
            'azaozz',
            'azchughtai',
            'b-07',
            'babbardel',
            'bandonrandon',
            'bcolumbia',
            'belcherj',
            'benjamin_zekavica',
            'benlk',
            'bernhard-reiter',
            'betsela',
            'bhargavmehta',
            'birgire',
            'blowery',
            'bobbingwide',
            'boblinthorst',
            'boemedia',
            'boonebgorges',
            'bordoni',
            'bpayton',
            'bph',
            'bradyvercher',
            'brentswisher',
            'briannaorg',
            'bronsonquick',
            'burhandodhy',
            'butimnoexpert',
            'buzztone',
            'cantothemes',
            'cathibosco',
            'caxco93',
            'chanthaboune',
            'charlestonsw',
            'chetan200891',
            'chetansatasiya',
            'chopinbach',
            'chouby',
            'chriskmnds',
            'chrisl27',
            'christophherr',
            'chrisvanpatten',
            'circlecube',
            'claudiosanches',
            'clorith',
            'codebykat',
            'coderkevin',
            'copons',
            'courtney0burton',
            'crunnells',
            'csabotta',
            'danielbachhuber',
            'danielhw',
            'danieltj',
            'daniloercoli',
            'dannycooper',
            'davemoran118',
            'davidakennedy',
            'davidherrera',
            'davidsword',
            'davisshaver',
            'dcavins',
            'dciso',
            'dd32',
            'delawski',
            'dency',
            'desideveloper',
            'designsimply',
            'desrosj',
            'deviodigital',
            'dfangstrom',
            'dhanendran',
            'diegoliv',
            'diegoreymendez',
            'dimadin',
            'dingo_bastard',
            'dixitadusara',
            'dlh',
            'dlocc',
            'dmsnell',
            'donnapep',
            'doomwaxer',
            'drewapicture',
            'dryanpress',
            'dsawardekar',
            'dsifford',
            'dsmart',
            'duanestorey',
            'earnjam',
            'ehg',
            'electricfeet',
            'eliorivero',
            'elrae',
            'enodekciw',
            'ephoxjames',
            'ephoxmogran',
            'epointal',
            'ericnmurphy',
            'etoledom',
            'euthelup',
            'fabiankaegy',
            'fabs_pim',
            'faishal',
            'flixos90',
            'floriansimeth',
            'folletto',
            'foobar4u',
            'foreverpinetree',
            'frank-klein',
            'fuyuko',
            'garrett-eclipse',
            'garyj',
            'garyjones',
            'georgeh',
            'georgestephanis',
            'giventofly76',
            'gma992',
            'gnif',
            'goldsounds',
            'gonzomir',
            'grappler',
            'grapplerulrich',
            'greatislander',
            'gwwar',
            'gziolo',
            'hardeepasrani',
            'hblackett',
            'hedgefield',
            'helen',
            'herbmiller',
            'herregroen',
            'hideokamoto',
            'hugobaeta',
            'hypest',
            'ianbelanger',
            'iandunn',
            'ianstewart',
            'icaleb',
            'idpokute',
            'ieatwebsites',
            'igorsch',
            'imath',
            'imonly_ik',
            'intronic',
            'ipstenu',
            'ireneyoast',
            'iseulde',
            'ismailelkorchi',
            'israelshmueli',
            'itowhid06',
            'ixkaito',
            'j-falk',
            'jagnew',
            'jahvi',
            'jakept',
            'jamestryon',
            'jamiehalvorson',
            'janalwin',
            'jaswrks',
            'jblz',
            'jbpaul17',
            'jd55',
            'jdembowski',
            'jdgrimes',
            'jeffpaul',
            'jeremyfelt',
            'jhoffm34',
            'jipmoors',
            'jnylen0',
            'joedolson',
            'joehoyle',
            'joemaller',
            'joemcgill',
            'joen',
            'johnbillion',
            'johndyer',
            'johnjamesjacoby',
            'johnny5',
            'johnpixle',
            'johnwatkins0',
            'jomurgel',
            'jonsurrell',
            'joostdevalk',
            'jorbin',
            'jorgefilipecosta',
            'joyously',
            'jrf',
            'jryancard',
            'jsnajdr',
            'julienmelissas',
            'jvisick77',
            'kadamwhite',
            'kallehauge',
            'kalpshit',
            'karmatosed',
            'kau-boy',
            'ketuchetan',
            'kevinwhoffman',
            'khleomix',
            'kjellr',
            'kluny',
            'koke',
            'kopepasah',
            'kraftbj',
            'krutidugade',
            'lamosty',
            'lancewillett',
            'laurelfulford',
            'leahkoerper',
            'littlebigthing',
            'lloyd',
            'loicblascos',
            'lonelyvegan',
            'lucaskowalski',
            'lucasrolff',
            'lucasstark',
            'luehrsen',
            'luigipulcini',
            'lukecavanagh',
            'lukepettway',
            'luminus',
            'lynneux',
            'm-e-h',
            'macbookandrew',
            'maedahbatool',
            'magicroundabout',
            'mahdiyazdani',
            'mahmoudsaeed',
            'mapk',
            'marina_wp',
            'mariusvw',
            'markjaquith',
            'martinlugton',
            'mathiu',
            'matt',
            'mattgeri',
            'mattheu',
            'matveb',
            'maurobringolf',
            'maximebj',
            'mayukojpn',
            'mboynes',
            'mcsf',
            'mdawaffe',
            'meetjey',
            'melchoyce',
            'mendezcode',
            'michaelhull',
            'mihai2u',
            'mike-haydon-swo',
            'mikehaydon',
            'mikeschroder',
            'mikeyarce',
            'milana_cap',
            'milesdelliott',
            'mimo84',
            'mirucon',
            'mitogh',
            'mizejewski',
            'mkaz',
            'mmaumio',
            'mmtr86',
            'mnelson4',
            'mor10',
            'mostafas1990',
            'motleydev',
            'mpheasant',
            'mrahmadawais',
            'mrasharirfan',
            'mrmadhat',
            'mrwweb',
            'msdesign21',
            'mtias',
            'mukesh27',
            'munirkamal',
            'mzorz',
            'nagayama',
            'nao',
            'napy84',
            'nateconley',
            'nativeinside',
            'nbachiyski',
            'nerrad',
            'netweb',
            'nfmohit',
            'nicbertino',
            'nielslange',
            'nikschavan',
            'nitrajka',
            'njpanderson',
            'noisysocks',
            'nosolosw',
            'notlaura',
            'notnownikki',
            'nshki',
            'obenland',
            'ocean90',
            'octalmage',
            'omarreiss',
            'oskosk',
            'otto42',
            'pareshradadiya-1',
            'pauldechov',
            'paulstonier',
            'paulwilde',
            'pbearne',
            'pedromendonca',
            'pento',
            'peterwilsoncc',
            'pglewis',
            'piersb',
            'pilou69',
            'pixelverbieger',
            'poena',
            'postphotos',
            'potbot',
            'pratikthink',
            'presskopp',
            'pross',
            'prtksxna',
            'psealock',
            'ptasker',
            'rachelbaker',
            'rachelmcr',
            'rahmohn',
            'rahmon',
            'rahulsprajapati',
            'rakshans1',
            'ramonopoly',
            'revgeorge',
            'rianrietveld',
            'richsalvucci',
            'riddhiehta02',
            'rileybrook',
            'rmccue',
            'robertsky',
            'rohittm',
            'ryelle',
            'ryo511',
            'sagarprajapati',
            'samikeijonen',
            'sanchothefat',
            'schlessera',
            'scottmweaver',
            'sephsekla',
            'sergeybiryukov',
            'sergioestevao',
            'sewmyheadon',
            'shaileesheth',
            'sharaz',
            'shaunandrews',
            'shelob9',
            'shenkj',
            'shooper',
            'sikander',
            'simison',
            'siriokun',
            'sirjonathan',
            'sirreal',
            'sisanu',
            'skorasaurus',
            'smyoon315',
            'soean',
            'somtijds',
            'soulseekah',
            'spacedmonkey',
            'spocke',
            'ssousa',
            'sstoqnov',
            'stagger-lee',
            'stevehenty',
            'strategio',
            'stuartfeldt',
            'stubgo',
            'sumobi',
            'swissspidy',
            'tacrapo',
            'talldan',
            'tammie_l',
            'technosiren',
            'tfrommen',
            'themeroots',
            'thrijith',
            'timgardner',
            'timmydcrawford',
            'timothyblynjacobs',
            'tinkerbelly',
            'tjfunke001',
            'tjnowell',
            'tlxo',
            'tobifjellner',
            'toro_unit',
            'travel_girl',
            'travislopes',
            'truongwp',
            'twoelevenjay',
            'tyrannous',
            'tyxla',
            'vengisss',
            'vindl',
            'vishalkakadiya',
            'vtrpldn',
            'walterebert',
            'warmarks',
            'webdevmattcrom',
            'webmandesign',
            'websupporter',
            'welcher',
            'westonruter',
            'williampatton',
            'willybahuaud',
            'wizzard_',
            'woodent',
            'wpscholar',
            'xkon',
            'xyfi',
            'yahil',
            'yingles',
            'yingling017',
            'yoavf',
            'youknowriad',
            'youthkee',
            'zebulan',
            'ziyaddin',
            '_dorsvenabili',
        );
    }

    function external_libraries() {
        return array(
            array( 'Backbone.js', 'http://backbonejs.org/' ),
            array( 'Class POP3', 'https://squirrelmail.org/' ),
            array( 'CodeMirror', 'https://codemirror.net/' ),
            array( 'Color Animations', 'https://plugins.jquery.com/color/' ),
            array( 'getID3()', 'http://getid3.sourceforge.net/' ),
            array( 'Horde Text Diff', 'https://pear.horde.org/' ),
            array( 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ),
            array( 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ),
            array( 'Iris', 'https://github.com/Automattic/Iris' ),
            array( 'jQuery', 'https://jquery.com/' ),
            array( 'jQuery UI', 'https://jqueryui.com/' ),
            array( 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ),
            array( 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ),
            array( 'jQuery.query', 'https://plugins.jquery.com/query-object/' ),
            array( 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ),
            array( 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ),
            array( 'json2', 'https://github.com/douglascrockford/JSON-js' ),
            array( 'Masonry', 'http://masonry.desandro.com/' ),
            array( 'MediaElement.js', 'http://mediaelementjs.com/' ),
            array( 'PclZip', 'http://www.phpconcept.net/pclzip/' ),
            array( 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ),
            array( 'phpass', 'http://www.openwall.com/phpass/' ),
            array( 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ),
            array( 'Plupload', 'http://www.plupload.com/' ),
            array( 'random_compat', 'https://github.com/paragonie/random_compat' ),
            array( 'Requests', 'http://requests.ryanmccue.info/' ),
            array( 'SimplePie', 'http://simplepie.org/' ),
            array( 'The Incutio XML-RPC Library', 'http://scripts.incutio.com/xmlrpc/' ),
            array( 'Thickbox', 'http://codylindley.com/thickbox/' ),
            array( 'TinyMCE', 'https://www.tinymce.com/' ),
            array( 'Twemoji', 'https://github.com/twitter/twemoji' ),
            array( 'Underscore.js', 'http://underscorejs.org/' ),
            array( 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ),
        );
    }
}

