<?php

class WP_68_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                         => [ 'Matt Mullenweg', 'Release Lead' ],
					'JeffPaul'                     => [ 'Jeff Paul', 'Release Coordination' ],
					'michelleames'                 => [ 'Michelle Frechette', 'Release Coordination' ],
					'Mamaduka'                     => [ 'George Mamadashvili', 'Tech Lead' ],
					'joemcgill'                    => [ 'Joe McGill', 'Tech Lead' ],
					'desrosj'                      => [ 'Jonathan Desrosiers', 'Tech Lead' ],
					'audrasjb'                     => [ 'Jean-Baptiste Audras', 'Triage Lead' ],
					'karmatosed'                   => [ 'Tammie Lister', 'Design Lead' ],
					'flixos90'                     => [ 'Felix Arntz', 'Performance Lead' ],
					'krupajnanda'                  => [ 'Krupa Nanda', 'Test Lead' ],
					'wildworks'                    => 'Aki Hamano',
					'tyxla'                        => 'Marin Atanasov',
					'SergeyBiryukov'               => 'Sergey Biryukov',
					'youknowriad'                  => 'Riad Benguella',
					'afercia'                      => 'Andrea Fercia',
					'mciampini'                    => 'Marco Ciampini',
					'0mirka00'                     => 'Lena Morita',
					'poena'                        => 'Carolina Nymark',
					'ramonopoly'                   => 'Ramon James',
					'gziolo'                       => 'Greg Ziółkowski',
					'westonruter'                  => 'Weston Ruter',
					'calvinalkan'                  => 'Calvin Alkan',
					'dd32'                         => 'Dion Hulse',
					'paragoninitiativeenterprises' => 'Scott Arciszewski',
					'johnbillion'                  => 'John Blackbourn',
					'im3dabasia1'                  => 'Eshaan Dabasiya',
					'yogeshbhutkar'                => 'Yogesh Bhutkar',
					'krupaly2k'                    => 'Krupal Lakhia',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'swissspidy'          => 'Pascal Birchler',
					'ntsekouras'          => 'Nik Tsekouras',
					'peterwilsoncc'       => 'Peter Wilson',
					'joedolson'           => 'Joe Dolson',
 					'Joen'                => 'Joen Asmussen',
					'jameskoster'         => 'James Koster',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'fabiankaegy'         => 'Fabian Kägy',
					'get_dave'            => 'David Smith',
					'ellatrix'            => 'Ella van Durpe',
					'shailu25'            => 'Shail Mehta',
					'oandregal'           => 'André Maneiro',
					'jonsurrell'          => 'Jon Surrell',
					'mukesh27'            => 'Mukesh Panchal',
					'nikunj8866'          => 'Nikunj Hatkar',
					'karthickmurugan'     => 'Karthick Murugan',
					'marybaum'            => 'Mary Baum',
					'ryelle'              => 'Kelly Choyce-Dwan',
					'sabernhardt'         => 'Stephen Bernhardt',
					'paulkevan'           => 'Paul Kevan',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'369work',
			'4thhubbard',
			'aaronrobertshaw',
			'abcd95',
			'abhi3315',
			'aboelfotoh',
			'acketon',
			'adakaleh',
			'adamsilverstein',
			'adhun',
			'adityab98',
			'aduth',
			'afercia',
			'afmarchetti',
			'afragen',
			'ahmarzaidi',
			'ahortin',
			'ahsankhan316',
			'aishwarryapande',
			'ajayghaghretiya1',
			'ajitbohra',
			'ajlende',
			'ajmaurya',
			'akanshusingh',
			'akrocks',
			'aks30498',
			'akshat2802',
			'akshaydhere',
			'albatross10',
			'albigdd',
			'alexandrebuffet',
			'alexflorisca',
			'alexschmitz',
			'alexstine',
			'alexus450',
			'alh0319',
			'alireyad',
			'aljullu',
			'alpipego',
			'amimulihsanmahdi',
			'amin7',
			'amincharoliya',
			'amitbhosale',
			'amitraj2203',
			'ammarmassoud',
			'amolebonde',
			'anandraj346',
			'andraganescu',
			'andrewserong',
			'andrewssanya',
			'ankit-k-gupta',
			'ankitkumarshah',
			'ankitmaru',
			'ankitpatel1578',
			'anlino',
			'anmolverma404',
			'annchichi',
			'annebovelett',
			'annezazu',
			'antonvlasenko',
			'antpb',
			'antwortzeit',
			'anujrathore24',
			'anveshika',
			'apermo',
			'areziaal',
			'arielmaidana',
			'aristath',
			'arnaudbroes',
			'arnoutblueshell',
			'arrcorona',
			'artemiosans',
			'arzola',
			'assassinateur',
			'atachibana',
			'auareyou',
			'audrasjb',
			'autotutorial',
			'awetz583',
			'ayeshrajans',
			'azaozz',
			'azharderaiya',
			'azouamauriac',
			'back2backdvm',
			'bacoords',
			'balub',
			'barry',
			'bayejid00',
			'bbpaule',
			'beafialho',
			'benazeer',
			'benharri',
			'benjamin_zekavica',
			'benniledl',
			'benoitchantre',
			'berislavgrgicak',
			'bernhard-reiter',
			'beryldlg',
			'bgermann',
			'bhubbard',
			'bijit027',
			'birgire',
			'bjornw',
			'bjorsch',
			'blogitsolutions',
			'bluantinoo',
			'bogdanungureanu',
			'boogah',
			'bookdude13',
			'bor0',
			'bowedk',
			'bpayton',
			'bph',
			'bradleyt',
			'brettsmason',
			'brevilo',
			'bronsonquick',
			'bschneidewind',
			'bsutcliffe',
			'burakkaptan',
			'burnuser',
			'cais',
			'calvinalkan',
			'casiepa',
			'cbirdsong',
			'cbravobernal',
			'cbusquets1989',
			'cgastrell',
			'chaion07',
			'charleslf',
			'chintanmachhi207',
			'chrico',
			'chriscct7',
			'chrisdotdotdot',
			'claimableperch',
			'claudiulodro',
			'clorith',
			'codeamp',
			'codebymikey',
			'codekraft',
			'codersantosh',
			'codex-m',
			'codexdemon',
			'coffee2code',
			'colind',
			'colinleroy',
			'colorful-tones',
			'contactprashantpp',
			'coquardcyr',
			'coreyw',
			'costdev',
			'courane01',
			'creadordev',
			'csesumonpro',
			'css31',
			'ctienshi',
			'cweiske',
			'cybr',
			'czapla',
			'daedalon',
			'dafargier',
			'dalleyne',
			'danht',
			'danielbachhuber',
			'danielpataki',
			'danielpost',
			'danielvann',
			'daniguardiola',
			'darerodz',
			'darnado',
			'davelo',
			'david-innes',
			'davidabowman',
			'davidbaumwald',
			'davidbinda',
			'daviedr',
			'davilera',
			'daymobrew',
			'dd32',
			'deadduck169',
			'debarghyabanerjee',
			'deepakrohilla',
			'deeppatel8950',
			'densinakum',
			'designsimply',
			'desrosj',
			'devansh2002',
			'devmuhib',
			'devtanbir',
			'dhananjaykuber',
			'dharm1025',
			'dhavalkapadane',
			'dheeraj2995',
			'dhewercorus',
			'dhrumilk',
			'dhruvang21',
			'dhruvik18',
			'dhruvishah2203',
			'didierjm',
			'digitalpritam',
			'diguj',
			'dilip2615',
			'dilipbheda',
			'diliphingarajiya',
			'dilipom13',
			'dingguodong',
			'dinhtungdu',
			'divyeshk71',
			'djcowan',
			'dkarfa',
			'dkotter',
			'dlh',
			'dmsnell',
			'dnnsjsk',
			'doekenorg',
			'dogee',
			'domainsupport',
			'domenicdenicola',
			'donalirl',
			'dontfeedthecode',
			'dooperweb',
			'dougwollison',
			'dparthj',
			'dpcalhoun',
			'dpknauss',
			'dreadlox',
			'dretzlaff',
			'drewapicture',
			'drivingralle',
			'dsas',
			'dsawyers',
			'dshanske',
			'dufresnesteven',
			'dwainm',
			'eartboard',
			'earthman100',
			'eatse',
			'eboxnet',
			'eceleste',
			'ecgan',
			'eclev91',
			'eddystile',
			'eduwass',
			'eherman24',
			'elizaan36',
			'ellatrix',
			'emlebrun',
			'engahmeds3ed',
			'ericdye',
			'estelaris',
			'ethitter',
			'etobiesen',
			'euthelup',
			'fabiankaegy',
			'faisal03',
			'faisalahammad',
			'faithcoder',
			'fazyshah',
			'fcoveram',
			'ffffelix',
			'fierevere',
			'finalwebsites',
			'finntown',
			'firewatch',
			'firoz2456',
			'flixos90',
			'francina',
			'franciscabusas22',
			'frank-klein',
			'frankbiganski',
			'franz00',
			'frkly',
			'fullofcaffeine',
			'fushar',
			'fxbenard',
			'fylgjur',
			'gaambo',
			'gadelhas',
			'gaellebesson',
			'gajendrasingh',
			'galibh',
			'garrett-eclipse',
			'garyj',
			'geekofshire',
			'gencmedya',
			'geriux',
			'get_dave',
			'ghinamt',
			'gigitux',
			'girishpanchal',
			'giuriani',
			'glendaviesnz',
			'glynnquelch',
			'gonom9',
			'grantmkin',
			'greatislander',
			'greenshady',
			'gregbenz',
			'grgarside',
			'groenroos',
			'growwbuddy',
			'guido07111975',
			'guillaumeturpin',
			'gulamdastgir04',
			'gvgvgvijayan',
			'gziolo',
			'hage',
			'hameem1102',
			'hanneslsm',
			'haozi',
			'hardipparmar',
			'hareesh-pillai',
			'harishanker',
			'harmr',
			'harrym',
			'harshalkadu',
			'hazdiego',
			'hbhalodia',
			'hdkothari81',
			'hekuranredev',
			'helen',
			'hellofromtonya',
			'hemant-ahir',
			'henrywright',
			'hiabhaykulkarni',
			'hideishi',
			'hilayt24',
			'hitendra-chopda',
			'hiteshhuptechweb',
			'hmbashar',
			'hovhanneshovakimyan',
			'hueitan',
			'humanify',
			'hussain896',
			'huubl',
			'huzaifaalmesbah',
			'iamarinoh',
			'iamkingsleyf',
			'iammattthomas',
			'iamshubhamsp',
			'iamtakashi',
			'iandunn',
			'ikamal',
			'ilovecats7',
			'im3dabasia1',
			'imaginarymedia',
			'immasud',
			'imranh920',
			'imranhasanraaz',
			'imrraaj',
			'inc2734',
			'indirabiswas27',
			'indithemes',
			'infosatech',
			'ingeniumed',
			'ironprogrammer',
			'isabel_brison',
			'isaeedam',
			'iseulde',
			'isuke01',
			'itsjonq',
			'itsmhrahman',
			'ivankristianto',
			'jagirbahesh',
			'jainil07',
			'jameskoster',
			'jamieblomerus',
			'jammycakes',
			'janak007',
			'janusdev',
			'jarekmorawski',
			'jartes',
			'jasonsa19',
			'javiercasares',
			'jbkkd',
			'jdahir0789',
			'jdnd',
			'jdy68',
			'jeffpaul',
			'jeffr0',
			'jeflopodev',
			'jepperask',
			'jeremy80',
			'jeremyfelt',
			'jeremyroman',
			'jeryj',
			'jessedyck',
			'jffng',
			'jhmonroe',
			'jigar-bhanushali',
			'jigar9998',
			'jnweaver',
			'jodamo5',
			'joecsmalley',
			'joedolson',
			'joehoyle',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnregan3',
			'jokanane',
			'jomonthomaslobo1',
			'jongycastillo',
			'jonnyauk',
			'jonsurrell',
			'joomskys',
			'joostdevalk',
			'jopdop30',
			'jorbin',
			'jordesign',
			'jorgefilipecosta',
			'josephscott',
			'josevarghese',
			'joshuawold',
			'josvelasco',
			'jottevanger',
			'joyously',
			'jrf',
			'jsnajdr',
			'juanbuis',
			'juanfra',
			'juanmaguitar',
			'juanwp22',
			'jucaduca',
			'jules-colle',
			'julianmar',
			'juliemoynat',
			'juliobox',
			'justlevine',
			'juzar',
			'kabir93',
			'kadamwhite',
			'kafleg',
			'kaitohm',
			'kapasias',
			'kapilpaul',
			'karlgroves',
			'karmatosed',
			'karolmanijak',
			'karthickmurugan',
			'karthikeya01',
			'kasparsd',
			'kausaralm',
			'kawsar007',
			'kebbet',
			'keithdevon',
			'kel-dc',
			'keoshi',
			'ketanniruke',
			'kevin940726',
			'kevinlearynet',
			'kharisblank',
			'kinggmobb',
			'kirasong',
			'kjroelke',
			'kkmuffme',
			'kmgalanakis',
			'knutsp',
			'kohheepeace',
			'kreppar',
			'kristastevens',
			'krokodok',
			'krstarica',
			'krupajnanda',
			'krupaly2k',
			'kurudrive',
			'lakshmananphp',
			'laurelfulford',
			'laxman-prajapati',
			'lcarevic',
			'leecollings',
			'leedxw',
			'leeseoftbc',
			'leewillis77',
			'lenasterg',
			'leszeks',
			'leup',
			'lev0',
			'levskipg',
			'lgladdy',
			'lilgames',
			'looswebstudio',
			'lopo',
			'louislaugesen',
			'louwie17',
			'lovesoni1999',
			'lovewpmu',
			'lovor',
			'ltrihan',
			'luisherranz',
			'lukecavanagh',
			'lumiblog',
			'luminuu',
			'lysyjan87',
			'maciejmackowiak',
			'madhudollu',
			'madpeter',
			'madtownlems',
			'magdarogier',
			'mai21',
			'maikelraow',
			'mamaduka',
			'manfcarlo',
			'manojmaharrshi',
			'manzoorwanijk',
			'mapk',
			'marchalyoan',
			'marian1',
			'mariayohana',
			'marineevain',
			'mark-k',
			'markhowellsmead',
			'marktimemedia',
			'martinkrcho',
			'marybaum',
			'masteradhoc',
			'matteoenna',
			'mattryanwalker',
			'mattwest',
			'mattyrob',
			'matveb',
			'maverick3x6',
			'maximebj',
			'maximemeganck',
			'mayanktripathi32',
			'mayur8991',
			'mbijon',
			'mboynes',
			'mburridge',
			'mciampini',
			'mcqueen22',
			'mcsf',
			'mdawaffe',
			'mdibrahimk48',
			'mdviralsampat',
			'mdxfr',
			'mediaformat',
			'megane9988',
			'mehdi01',
			'mehedi_csit',
			'mel_cha',
			'metropolis_john',
			'mi5t4n',
			'michaelarestad',
			'michelleames',
			'micromadness',
			'mijotj',
			'mikachan',
			'mikinc860',
			'milana_cap',
			'milindmore22',
			'mimitips',
			'miqrogroove',
			'mitogh',
			'mkrndmane',
			'mmaattiiaass',
			'mmtr86',
			'modi2918',
			'mohitdadhich10',
			'mohonchandra',
			'mojorob',
			'mosescursor',
			'mosne',
			'moxie',
			'mp518',
			'mr660',
			'mrashishjain',
			'mreishus',
			'mrfoxtalbot',
			'mrtortai',
			'mrunalkulkarni',
			'mrwweb',
			'mslavco',
			'mtdkei',
			'mte90',
			'muddassirnasim',
			'mujuonly',
			'mukesh27',
			'mukulsingh27',
			'my1xt',
			'n2erjo00',
			'n8finch',
			'nacin',
			'najmulsaju',
			'nandow',
			'nanisamireddy',
			'narenin',
			'nareshbheda',
			'nataliat2004',
			'nathanatmoz',
			'nathkrill',
			'navi161',
			'navneet',
			'ndiego',
			'neo2k23',
			'neotrope',
			'netweb',
			'nhrrob',
			'nickgalvez',
			'nickwilmot',
			'nicolasleroy',
			'nidhidhandhukiya',
			'nikitasolanki1812',
			'nikunj8866',
			'nirajgirixd',
			'nithins53',
			'nofearinc',
			'noisysocks',
			'nomnom99',
			'noruzzaman',
			'nosilver4u',
			'ntsekouras',
			'nuryko',
			'oandregal',
			'obenland',
			'ocean90',
			'oceantober',
			'oglekler',
			'okvee',
			'omaeyusuke',
			'onemaggie',
			'ooraiser69',
			'othernoel',
			'otto42',
			'ov3rfly',
			'paaljoachim',
			'paapst',
			'pampfelimetten',
			'panchalhimani711',
			'paragoninitiativeenterprises',
			'parinpanjari',
			'parthvataliya',
			'pateljaymin',
			'patelketan',
			'patricia70',
			'paulkevan',
			'paullb',
			'paulopmt1',
			'pavanpatil1',
			'pbearne',
			'pbiron',
			'pctevree',
			'pedromendonca',
			'pento',
			'peter8nss',
			'peterdavehello',
			'peterwilsoncc',
			'petitphp',
			'philliproth',
			'philwebs',
			'pitamdey',
			'pixlpirate',
			'pkbhatt',
			'plari',
			'pmbaldha',
			'podpirate',
			'poena',
			'pooja1210',
			'pooja9712',
			'poojabhimani',
			'praful2111',
			'prasadkarmalkar',
			'prashant',
			'prathamesh24',
			'prathameshbhagat1511',
			'pratikgandhi',
			'pratiklondhe',
			'presskopp',
			'presstoke',
			'priethor',
			'priyank9033',
			'provenself',
			'psrpinto',
			'psykro',
			'pushpenderindia',
			'q0rban',
			'qhaensler',
			'rahmohn',
			'rahulsprajapati',
			'rainynewt',
			'raj198',
			'rajat1192',
			'rajendrapatilraj',
			'rajeshrathodwp',
			'rajinsharwar',
			'ralessio',
			'ramonopoly',
			'ranafge',
			'rarst',
			'ravigadhiyawp',
			'rcorrales',
			'rcreators',
			'realloc',
			'redkite',
			'rehanali',
			'rejaulalomkhan',
			'rembem',
			'renathoc',
			'rfischmann',
			'richtabor',
			'riddhidave',
			'rilwis',
			'rinkalpagdar',
			'rishavdutta',
			'rishishah',
			'rishit30g',
			'ritterml',
			'rkradadiya',
			'rkyburz',
			'rmccue',
			'robertghetau',
			'robertstaddon',
			'robinmartijn',
			'rodrigosprimo',
			'rogierlankhorst',
			'rohitmathur7',
			'rohjay',
			'room34',
			'rotemg',
			'roybellingan',
			'roytanck',
			'ruchirj',
			'rudrakshigupta',
			'rupesh5438',
			'rupw',
			'ruturajraval2305',
			'rvoigt',
			'rvouill',
			'ryanhellyer',
			'ryelle',
			'ryokuhi',
			'sabbir1991',
			'sabernhardt',
			'sabrineg',
			'sagarlakhani',
			'sagarprajapati',
			'sailpete',
			'sainathpoojary',
			'sajjad67',
			'sallyruchman',
			'samiamnot',
			'santosguillamot',
			'sarathar',
			'sarthaknagoshe2002',
			'sathyapulse',
			'saurabhdhariwal',
			'saxonafletcher',
			'sayedulsayem',
			'sbathompson',
			'sc0ttkclark',
			'scribu',
			'scruffian',
			'sean212',
			'seanlanglands',
			'sebastianpisula',
			'sebastienserre',
			'seifradwane',
			'sergeybiryukov',
			'sergiogutierrez',
			'sergiomdgomes',
			'severinepozzo',
			'sfougnier',
			'sh4lin',
			'shadialaghbari',
			'shailu25',
			'shanemuir',
			'shimotomoki',
			'shovan_jaya',
			'shraddhagore',
			'shreyashd21',
			'shub07',
			'shulard',
			'shyamkariya',
			'siliconforks',
			'simison',
			'simo_m',
			'sippis',
			'sirlouen',
			'sjefen6',
			'sketchboy',
			'skithund',
			'skorasaurus',
			'slaffik',
			'smerriman',
			'smrubenstein',
			'smushytaco',
			'snehal5774',
			'snehapatil02',
			'snicco',
			'snilesh',
			'soean',
			'sohamjoshi8275',
			'soulseekah',
			'sourabhjain',
			'sourav08',
			'soyebsalar',
			'spacedmonkey',
			'spaceshipone',
			'spdft',
			'spencerfinnell',
			'spenserhale',
			'spmultidots',
			'spncr',
			'sppramodh',
			'srikat',
			'stefahn',
			'stein2nd',
			'stimul',
			'strarsis',
			'stromhalm',
			'stuartmcalpine',
			'subodhrajpopat',
			'subrataemfluence',
			'sukhendu2002',
			'sumitbagthariya16',
			'sumitsingh',
			'sunil25393',
			'surajswalstar',
			'swalkinshaw',
			'swissspidy',
			'synchro',
			'szepeviktor',
			'tacoverdo',
			'takayukister',
			'takuword',
			'talksina',
			'talldanwp',
			'tb1909',
			'tgsrvrs',
			'th23',
			'thakordarshil',
			'thehercules',
			'thekt12',
			'thelmachido',
			'thelovekesh',
			'themebeans',
			'thomaswm',
			'threadi',
			'thrijith',
			'tiagogoncalves',
			'tigriweb',
			'tillkruess',
			'timothyblynjacobs',
			'timse201',
			'timwhitlock',
			'tinypixel',
			'tirth03',
			'tjarrett',
			'tkama',
			'tobiasbg',
			'tobifjellner',
			'tomdxw',
			'tommusrhodus',
			'toro_unit',
			'travel_girl',
			'tropicalista',
			'truptikanzariya',
			'trushaamin',
			'tschwarz-1',
			'tunetheweb',
			'tusharaddweb',
			'twvania',
			'tyb',
			'tysonlmao',
			'tyxla',
			'ugyensupport',
			'umeshsinghin',
			'undefinedfr',
			'unsalkorkmaz',
			'up1512001',
			'upadalavipul',
			'utrenkner',
			'vaibhav2527',
			'vaibhavsweb',
			'valer1e',
			'vcanales',
			'veryard',
			'verygoode',
			'vevas',
			'vgnavada',
			'vijaysinh9094',
			'vikrampm',
			'vineet2003',
			'vipulgupta003',
			'vipulpatil',
			'viralsampat',
			'virgar',
			'virgildia',
			'virginienacci',
			'vishy-moghan',
			'vivekawsm',
			'voboghure',
			'vrishabhsk',
			'vykesmac',
			'wadowad',
			'webcommsat',
			'webmandesign',
			'websiteredev',
			'welcher',
			'west7',
			'westi',
			'westonruter',
			'whaze',
			'whyisjake',
			'wildworks',
			'williampatton',
			'wongjn',
			'worldweb',
			'wpfed',
			'wpgerd',
			'wpgurudev',
			'wplmillet',
			'wprockstar2',
			'wwdes',
			'xate',
			'xavilc',
			'xknown',
			'xkon',
			'xpurichan',
			'yahaly',
			'yahil',
			'yaniiliev',
			'yashrocz',
			'yellowafterlife',
			'yogeshbhutkar',
			'youknowriad',
			'yudhisthirnahar',
			'yuliyan',
			'zaguiini',
			'zaoyao',
			'zargarov',
			'zebulan',
			'zeelthakkar',
			'zieladam',
			'zodiac1978',
			'zoonini',
			'zunaid321',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/jdecked/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

