<?php

class WP_66_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                => [ 'Matt Mullenweg', 'Release Lead' ],
					'meher'               => [ 'Meher Bala', 'Release Lead' ],
					'audrasjb'            => [ 'Jean-Baptiste Audras', 'Release Lead' ],
					'ellatrix'            => [ 'Ella van Durpe', 'Release Lead' ],
					'vcanales'            => 'Vicente Canales',
					'oglekler'            => 'Olga Gleckler',
					'nhrrob'              => 'Nazmul Hasan Robin',
					'fabiankaegy'         => 'Fabian Kägy',
					'colorful tones'      => 'Damon Cook',
					'marybaum'            => 'Mary Baum',
					'annezazu'            => 'Anne McCarthy',
					'richtabor'           => 'Rich Tabor',
					'adamsilverstein'     => 'Adam Silverstein',
					'juanmaguitar'        => 'JuanMa Garrido',
					'jdy68'               => 'Jenny Dupuy',
					'josepmoran'          => 'Josep Morán',
					'youknowriad'         => 'Riad Benguella',
					'wildworks'           => 'Aki Hamano',
					'Mamaduka'            => 'George Mamadashvili',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'jameskoster'         => 'James Koster',
 					'Joen'                => 'Joen Asmussen',
					'swissspidy'          => 'Pascal Birchler',
					'ntsekouras'          => 'Nik Tsekouras',
					'andrewserong'        => 'Andrew Serong',
					'ramonopoly'          => 'Ramon James',
					'tyxla'               => 'Marin Atanasov',
					'isabel_brison'       => 'Isabel Brison',
					'oandregal'           => 'André Maneiro',
					'poena'               => 'Carolina Nymark',
					'jorgefilipecosta'    => 'Jorge Costa',
					'talldanwp'           => 'Daniel Richards',
					'jonsurrell'          => 'Jon Surrell',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'gziolo'              => 'Greg Ziółkowski',
					'afercia'             => 'Andrea Fercia',
					'scruffian'           => 'Ben Dwyer',
					'cbravobernal'        => 'Carlos Bravo',
					'sabernhardt'         => 'Stephen Bernhardt',
					'desrosj'             => 'Jonathan Desrosiers',
					'0mirka00'            => 'Lena Morita',
					'peterwilsoncc'       => 'Peter Wilson',
					'matveb'              => 'Matias Ventura',
					'andraganescu'        => 'Andrei Draganescu',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'dmsnell'             => 'Dennis Snell',
					'joedolson'           => 'Joe Dolson',
					'mukesh27'            => 'Mukesh Panchal',
					'jsnajdr'             => 'Jarda Snajdr',
					'karmatosed'          => 'Tammie Lister',
					'shailu25'            => 'Shail Mehta',
					'noisysocks'          => 'Robert Anderson',
					'jorbin'              => 'Aaron Jorbin',
					'get_dave'            => 'David Smith',
					'johnbillion'         => 'John Blackbourn',
					'joemcgill'           => 'Joe McGill',
					'jeryj'               => 'Jerry Jones',
					'kevin940726'         => 'Kai Hao',
					'pablohoneyhoney'     => 'Pablo Honey',
					'szopserwis'          => 'Jarek Mazurczak',
					'saxonfletcher'       => 'Saxon Fletcher',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'1naveengiri',
			'aaronrobertshaw',
			'aatanasov',
			'abditsori',
			'abhi3315',
			'abhijitrakas',
			'abitofmind',
			'adamsilverstein',
			'adeltahri',
			'adrianduffell',
			'aezazshekh',
			'afercia',
			'afragen',
			'ajfleming',
			'ajitbohra',
			'ajlende',
			'akashdhawade',
			'akmelias',
			'alanfuller',
			'alesflex',
			'alexandrebuffet',
			'alexminza',
			'alexstine',
			'alh0319',
			'alisongodar',
			'aljullu',
			'alshakero',
			'amanias1977',
			'amieiro',
			'amirthepiper',
			'amisiewicz',
			'amitraj2203',
			'amustaque97',
			'anamarijapapic',
			'andr3ribeiro',
			'andraganescu',
			'andrewhayward',
			'andrewserong',
			'aneeshd16',
			'angelasjin',
			'anilvaza',
			'ankit-k-gupta',
			'ankitmaru',
			'anlino',
			'annezazu',
			'antonvlasenko',
			'antpb',
			'aristath',
			'artemiosans',
			'arthur791004',
			'artpi',
			'asheshmagar',
			'ashokrane',
			'aslamdoctor',
			'assassinateur',
			'atachibana',
			'audrasjb',
			'aurooba',
			'awetz583',
			'ayeshrajans',
			'azaozz',
			'bacoords',
			'balub',
			'bangank36',
			'bartkalisz',
			'beafialho',
			'beaulebens',
			'benjamin_zekavica',
			'benjaminpick',
			'benjpw',
			'benlk',
			'benniledl',
			'bernhard-reiter',
			'bgardner',
			'bgnicolepaschen',
			'bgoewert',
			'bgosnell',
			'bissy',
			'bitmachina',
			'bjorsch',
			'blackbam',
			'blepoxp',
			'blockify',
			'bnewboldbsky',
			'bph',
			'bridgetwillard',
			'britner',
			'brookemk',
			'burnuser',
			'caercam',
			'cafenoirdesign',
			'carlosgprim',
			'cawa-93',
			'cbirdsong',
			'cbravobernal',
			'cbringmann',
			'chaion07',
			'chaton666',
			'chouby',
			'chrisdotdotdot',
			'christopherplus',
			'clorith',
			'colind',
			'colle',
			'collet',
			'colorful-tones',
			'comecaramelos',
			'cookiesfordevo',
			'coreymckrill',
			'costdev',
			'cotobago',
			'craigfrancis',
			'crazytonyli',
			'curdin',
			'cwhitmore',
			'cybr',
			'cyrus11',
			'czapla',
			'daledupreez',
			'daniguardiola',
			'dansoschin',
			'darerodz',
			'dargus',
			'darshitrajyaguru97',
			'dav4',
			'davecpage',
			'davidabowman',
			'davidakennedy',
			'davidbaumwald',
			'davidbinda',
			'davideferre',
			'daviedr',
			'dd32',
			'deepakvijayan',
			'deeppatel8950',
			'defries',
			'derekblank',
			'dernin',
			'desrosj',
			'devmuhib',
			'devsahadat',
			'dextorlobo',
			'dharm1025',
			'dhrumilk',
			'dhruval04',
			'dhruvang21',
			'dhruvkb',
			'diedeexterkate',
			'diggeddy',
			'dilipbheda',
			'dingo_d',
			'djzone',
			'dkjensen',
			'dlh',
			'dmsnell',
			'domainsupport',
			'dpcalhoun',
			'drewapicture',
			'drrxbracho',
			'dsas',
			'earnjam',
			'edent',
			'ellatrix',
			'elrae',
			'enej',
			'enodekciw',
			'enricosorcinelli',
			'estelaris',
			'euthelup',
			'evanltd',
			'f-j-kaiser',
			'fabiankaegy',
			'faisal03',
			'fanly',
			'fierevere',
			'firewatch',
			'flabernardez',
			'flexseth',
			'flixos90',
			'freewebmentor',
			'freibergergarcia',
			'fullofcaffeine',
			'gaambo',
			'galbaras',
			'garridinsi',
			'garyj',
			'georgestephanis',
			'geriux',
			'get_dave',
			'gigitux',
			'glendaviesnz',
			'grantmkin',
			'greenshady',
			'gziolo',
			'hage',
			'hakre',
			'hanneslsm',
			'haritpanchal',
			'harshgajipara',
			'hazdiego',
			'hbhalodia',
			'heinperu',
			'helgatheviking',
			'hellofromtonya',
			'hinnerk',
			'hitendra-chopda',
			'hmbashar',
			'hrkhal',
			'humanify',
			'huubl',
			'huzaifaalmesbah',
			'iamfarhan09',
			'iamtakashi',
			'ianbelanger',
			'icaleb',
			'ideag',
			'ignatiusjeroe',
			'illuminea',
			'imasikur22',
			'imath',
			'immeet94',
			'imranhasanraaz',
			'inc2734',
			'interdevel',
			'inwerpsel',
			'ipstenu',
			'ironprogrammer',
			'isabel_brison',
			'itpathsolutions',
			'itsjustdj',
			'ivanottinger',
			'ixkaito',
			'jaclync',
			'jameskoster',
			'janboddez',
			'janthiel',
			'jaruzek',
			'jason_the_adams',
			'javiercasares',
			'jayanthparthsarathy',
			'jazzs3quence',
			'jdekhtiar',
			'jdy68',
			'jeffpaul',
			'jeflopodev',
			'jeherve',
			'jeremyfelt',
			'jeryj',
			'jffng',
			'jhned',
			'jigar-bhanushali',
			'jipmoors',
			'jivedig',
			'joedolson',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnillo',
			'johnjamesjacoby',
			'johnny5',
			'jon092',
			'jonsurrell',
			'jorbin',
			'jordesign',
			'jorgefilipecosta',
			'josephscott',
			'josevarghese',
			'jossnaz',
			'jpolakovic',
			'jpry',
			'jpstevens',
			'jrf',
			'jsnajdr',
			'jsnjohnston',
			'jtolleouw',
			'juanfra',
			'juanmaguitar',
			'jucaduca',
			'jules',
			'juliemoynat',
			'juliobox',
			'justlevine',
			'justnorris',
			'jwgoedert',
			'jyolsna',
			'kadamwhite',
			'kafleg',
			'kajalgohel',
			'kamran8176',
			'kapilpaul',
			'karlijnbk',
			'karmatosed',
			'karolmanijak',
			'kawauso',
			'kebbet',
			'kellenmace',
			'keoshi',
			'kevin940726',
			'kevinwhoffman',
			'khokansardar',
			'killua99',
			'kim88',
			'kirasong',
			'kitchin',
			'kjellr',
			'kkmuffme',
			'kmvan',
			'kovshenin',
			'kraftner',
			'kreppar',
			'kristastevens',
			'kristenfisher427',
			'krokodok',
			'krupajnanda',
			'krupalpanchal',
			'kushang78',
			'kyleak',
			'l1nuxjedi',
			'lamarajan',
			'lanresmith',
			'lardsax',
			'laurelfulford',
			'laurlittle',
			'leemon',
			'leonidasmilossis',
			'lgersman',
			'littlerchicken',
			'liviopv',
			'lopo',
			'louiswol94',
			'luboslives',
			'luisherranz',
			'luminuu',
			'lunule',
			'lyonmuller',
			'madhudollu',
			'madtownlems',
			'mai21',
			'makdiahussain',
			'mamaduka',
			'manfcarlo',
			'manojmaharrshi',
			'manooweb',
			'mapk',
			'marc4',
			'marherumr',
			'markhowellsmead',
			'markjaquith',
			'markjszymanski',
			'marybaum',
			'masteradhoc',
			'mat-lipe',
			'mattmm',
			'mattormeeple',
			'matveb',
			'mciampini',
			'mcsf',
			'mdnesarmridha',
			'mdxfr',
			'meetmehta1205',
			'megane9988',
			'mhkuu',
			'miguelsansegundo',
			'miikkamakela',
			'mikachan',
			'mikehend',
			'mikeybinns',
			'mista-flo',
			'misulicus',
			'mkismy',
			'mlaetitia',
			'mmaattiiaass',
			'mmcalister',
			'mohitdadhich10',
			'mohonchandra',
			'monzuralam',
			'mr2p',
			'mrfoxtalbot',
			'mrwweb',
			'mujuonly',
			'mukesh27',
			'multidots1896',
			'musannifzahir',
			'myhro',
			'mykolashlyakhtun',
			'n2erjo00',
			'nacin',
			'naeemhaque',
			'namithjawahar',
			'narenin',
			'nareshbheda',
			'nateinaction',
			'nazmul111',
			'ndiego',
			'nekojonez',
			'nerrad',
			'nestea29950',
			'netweb',
			'newyorkerlaura',
			'nhrrob',
			'nicmare',
			'nico23',
			'nicolefurlan',
			'nicomollet',
			'nidhidhandhukiya',
			'nielslange',
			'nihar007',
			'niktat',
			'nilovelez',
			'niravsherasiya7707',
			'nithi22',
			'nithins53',
			'nkeller15',
			'noisysocks',
			'nomnom99',
			'nosilver4u',
			'nsinelnikov',
			'ntsekouras',
			'oandregal',
			'obliviousharmony',
			'ocean90',
			'oglekler',
			'ohia',
			'okat',
			'oldrup',
			'olliejones',
			'oncecoupled',
			'onemaggie',
			'onmauitime',
			'paaljoachim',
			'pablohoneyhoney',
			'pagelab',
			'patricia70',
			'pauldewouters',
			'paulkevan',
			'paulwilde',
			'pavanpatil1',
			'pavelevap',
			'pbearne',
			'pbking',
			'pedromendonca',
			'peexy',
			'peiche',
			'pereirinha',
			'perryrylance',
			'pers',
			'peterwilsoncc',
			'petitphp',
			'pitamdey',
			'pkuliga',
			'pls78',
			'pmbaldha',
			'poena',
			'pooja1210',
			'povilasstaskus',
			'praful2111',
			'pranitdugad',
			'prasadkarmalkar',
			'pratiklondhe',
			'presents111',
			'presskopp',
			'presstoke',
			'priethor',
			'printsachen1',
			'priyanshii5',
			'prottoysarkar',
			'provenself',
			'psykro',
			'quietnoise',
			'rachelbaker',
			'rafaelgalani',
			'rafaucau',
			'rahmohn',
			'rajinsharwar',
			'ramonopoly',
			'ravinderk',
			'ravipatel',
			'rcorrales',
			'rcreators',
			'rdcoll',
			'rejaulalomkhan',
			'renishsurani',
			'retrofox',
			'richardevs',
			'richtabor',
			'rmccue',
			'robertghetau',
			'rockfire',
			'rodionov201',
			'rodrigosprimo',
			'rogermedia',
			'rolfsiebers',
			'roytanck',
			'rxnlabs',
			'ryancurban',
			'rudlinkon',
			'ryelle',
			'ryokuhi',
			's0what',
			'sabernhardt',
			'sagarprajapati',
			'sahilthakur02',
			'sakibmd',
			'salcode',
			'samanthaxmunoz',
			'samiamnot',
			'samuelsidler',
			'sannevndrmeulen',
			'santosguillamot',
			'sarkarripon',
			'sauliusv',
			'saxonafletcher',
			'scribu',
			'script2see',
			'scruffian',
			'sean212',
			'sebastienserre',
			'sergeybiryukov',
			'sergiomdgomes',
			'sh4lin',
			'shailu25',
			'shaunandrews',
			'sheulyshila',
			'shimotomoki',
			'shireling',
			'shital-patel',
			'shivapoudel',
			'shivashankerbhatta',
			'shreyash3087',
			'shub07',
			'shuvomohajan',
			'siliconforks',
			'simison',
			'simo_m',
			'siobhyb',
			'sirzooro',
			'sjnbham',
			'skithund',
			'skorasaurus',
			'smetzdev',
			'smrubenstein',
			'smub',
			'snehapatil02',
			'soean',
			'spacedmonkey',
			'spencerfinnell',
			'starbuck',
			'stephenbrook',
			'stephenmiracle',
			'steveblum',
			'stevejonesdev',
			'strangehill',
			'strarsis',
			'stringpiggy',
			'suascat_wp',
			'sudipatel007',
			'sumitbagthariya16',
			'sumitsingh',
			'sunil25393',
			'swissspidy',
			'syamraj24',
			'szepeviktor',
			'tabrisrp',
			'tahmidulkarim',
			'talksina',
			'talldanwp',
			'taylorgorman',
			'tb1909',
			'teresagobble',
			'thakordarshil',
			'thekt12',
			'thelmachido',
			'thelovekesh',
			'thijso',
			'thirumani02',
			'tillkruess',
			'timnicholson',
			'timothyblynjacobs',
			'timotijhof',
			'timse201',
			'tmatsuur',
			'tnolte',
			'tobiasbg',
			'tobifjellner',
			'tofajjal02',
			'tomalec',
			'tomepajk',
			'tomjcafferkey',
			'tomxygen',
			'toro_unit',
			'truptikanzariya',
			'tunetheweb',
			'twstokes',
			'tybor',
			'tyxla',
			'ugyensupport',
			'umesh84',
			'up1512001',
			'vcanales',
			'verygoode',
			'vineet2003',
			'vinita29',
			'vipulgupta003',
			'viralsampat',
			'vivekawsm',
			'voldemortensen',
			'webcommsat',
			'webdevmattcrom',
			'webgarten',
			'webmandesign',
			'websitegenii',
			'weijland',
			'welcher',
			'wesatintellitonic',
			'westonruter',
			'whaze',
			'wido',
			'wildworks',
			'wojtekn',
			'wppinar',
			'xhemals',
			'xknown',
			'xronn',
			'yagniksangani',
			'yankiara',
			'yguyon',
			'youknowriad',
			'yukinobu',
			'yuvrajsinh2211',
			'zackkrida',
			'zafarkamal',
			'zieladam',
			'zkarj',
			'zodiac1978',
			'zoonini',
			'zunaid321',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

