<?php

class WP_69_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                => [ 'Matt Mullenweg', 'Release Lead' ],
					'akshayar'            => [ 'Akshaya Rane', 'Release Coordination' ],
					'amykamala'           => [ 'Amy Kamala', 'Release Coordination' ],
					'davidbaumwald'       => [ 'David Baumwald', 'Tech Lead' ],
					'ellatrix'            => [ 'Ella van Durpe', 'Tech Lead' ],
					'priethor'            => [ 'Héctor Prieto', 'Tech Lead' ],
					'fcoveram'            => [ 'Francisco Vera', 'Design Lead' ],
					'wildworks'           => [ 'Aki Hamano', 'Triage Lead' ],
					'welcher'             => [ 'Ryan Welcher', 'Triage Lead' ],
					'psykro'              => [ 'Jonathan Bossenger', 'Test Lead' ],
					'krupajnanda'         => [ 'Krupa Nanda', 'Test Lead' ],
					'Mamaduka'            => 'George Mamadashvili',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'westonruter'         => 'Weston Ruter',
					'desrosj'             => 'Jonathan Desrosiers',
					'joedolson'           => 'Joe Dolson',
					'mukesh27'            => 'Mukesh Panchal',
					'johnbillion'         => 'John Blackbourn',
					'peterwilsoncc'       => 'Peter Wilson',
					'youknowriad'         => 'Riad Benguella',
					'sabernhardt'         => 'Stephen Bernhardt',
					'dmsnell'             => 'Dennis Snell',
					'audrasjb'            => 'Jean-Baptiste Audras',
					'SirLouen'            => 'Manuel Camargo',
					'jonsurrell'          => 'Jon Surrell',
					'jorbin'              => 'Aaron Jorbin',
					'adamsilverstein'     => 'Adam Silverstein',
					'swissspidy'          => 'Pascal Birchler',
					'JeffPaul'            => 'Jeff Paul',
					'gziolo'              => 'Greg Ziółkowski',
 					'Joen'                => 'Joen Asmussen',
					'matveb'              => 'Matias Ventura',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'annezazu'            => 'Anne McCarthy',
					'poena'               => 'Carolina Nymark',
					'oandregal'           => 'André Maneiro',
					'yogeshbhutkar'       => 'Yogesh Bhutkar',
					'Bernhard Reiter'     => 'Bernhard Reiter',
					'ramonopoly'          => 'Ramon James',
					'talldanwp'           => 'Daniel Richards',
					'fabiankaegy'         => 'Fabian Kägy',
					'shailu25'            => 'Shail Mehta',
					'andrewserong'        => 'Andrew Serong',
					'ntsekouras'          => 'Nik Tsekouras',
					'jorgefilipecosta'    => 'Jorge Costa',
					'justlevine'          => 'David Levine',
					'abcd95'              => 'Himanshu Pathak',
					'afercia'             => 'Andrea Fercia',
					'im3dabasia1'         => 'Eshaan Dabasiya',
					'get_dave'            => 'David Smith',
					'karthickmurugan'     => 'Karthick Murugan',
					'tyxla'               => 'Marin Atanasov',
					'ankitkumarshah'      => 'Ankit Kumar Shah',
					'isabel_brison'       => 'Isabel Brison',
					'mikachan'            => 'Sarah Norris',
					'scruffian'           => 'Ben Dwyer',
					'cbravobernal'        => 'Carlos Bravo',
					'shimotomoki'         => 'Tomoki Shimomura',
					'0mirka00'            => 'Lena Morita',
					'jameskoster'         => 'James Koster',
					'ryelle'              => 'Kelly Choyce-Dwan',
					'mcsf'                => 'Miguel Fonseca',
					'kadamwhite'          => 'K. Adam White',
					'poojabhimani'        => 'Pooja Bhimani',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'369work',
			'4thhubbard',
			'aakashverma1',
			'aaronrobertshaw',
			'aarti1318',
			'aatospaja',
			'abcd95',
			'abduremon',
			'acketon',
			'adamsilverstein',
			'adityab98',
			'adityashah2411',
			'adrock42',
			'aduth',
			'afercia',
			'afragen',
			'agulbra',
			'aialvi',
			'ajaxstardust',
			'ajitbohra',
			'ajlende',
			'akanshusingh',
			'akashdev',
			'akeda',
			'akshat2802',
			'akshayar',
			'akshaydhere',
			'aksl95',
			'alejandrogonzalvo',
			'alexandrebuffet',
			'alexclassroom',
			'alexcu21',
			'alexius08',
			'alexstine',
			'alexus450',
			'alh0319',
			'aljullu',
			'alordiel',
			'alshakero',
			'amin7',
			'amitbhosale',
			'amykamala',
			'anatolbroder',
			'andraganescu',
			'andrewhoyer',
			'andrewserong',
			'ankit-k-gupta',
			'ankitkumarshah',
			'ankitmaru',
			'anlino',
			'annebovelett',
			'annezazu',
			'antoniosejas',
			'antonvlasenko',
			'anujrathore24',
			'anveshika',
			'apermo',
			'apmeyer',
			'areziaal',
			'aristath',
			'armandovias',
			'artemiosans',
			'arthur791004',
			'artpi',
			'artz91',
			'asafm7',
			'asdofindia',
			'ashfame',
			'askapache',
			'aslamdoctor',
			'atachibana',
			'audrasjb',
			'aurooba',
			'aut0poietic',
			'awetz583',
			'ayeshrajans',
			'azaozz',
			'azharderaiya',
			'b1ink0',
			'bacoords',
			'bartnv',
			'bchecketts',
			'beee',
			'benazeer',
			'benjamin_zekavica',
			'benoitchantre',
			'bernhard-reiter',
			'beryldlg',
			'bgardner',
			'bgermann',
			'bgoewert',
			'bhattaganesh',
			'bhaveshdesai',
			'bhubbard',
			'bidbmak',
			'birgire',
			'bjorsch',
			'bobbyleenoblestudios',
			'bogdanungureanu',
			'bor0',
			'bozzmedia',
			'bph',
			'bradley2083',
			'bradshawtm',
			'brandbrilliance',
			'brhodes',
			'brumack',
			'bschneidewind',
			'bshuchter',
			'bugnumber9',
			'burlesonbrad',
			'burnuser',
			'butterflymedia',
			'bvl',
			'byteninjaa0',
			'callumbw95',
			'carlosgprim',
			'carlsteffen',
			'catgofire',
			'cbirdsong',
			'cbravobernal',
			'cbutlerjr',
			'ccharel',
			'cedche99',
			'celloexpressions',
			'cheffheid',
			'cherrygot',
			'chihsuan',
			'chillifish',
			'chloed',
			'chouby',
			'chriscct7',
			'chrisdotdotdot',
			'chrismattix',
			'christinecooper',
			'chrisvendiadvertisingcom',
			'cikrimcin',
			'ciobanucatalin',
			'circlecube',
			'ckoerner',
			'claimableperch',
			'codeamp',
			'codebuddy',
			'codebykat',
			'codente',
			'codex-m',
			'coleatkinson1',
			'colind',
			'colorful-tones',
			'coralietixeront',
			'corazondejaguar',
			'coreyw',
			'cornwell',
			'costasovo',
			'costdev',
			'courane01',
			'cr0ybot',
			'cucocreative',
			'cwhitmore',
			'cybr',
			'cyrille37',
			'czapla',
			'czarate',
			'daanvandenbergh',
			'damchtlv',
			'damir-webthemer',
			'dancameron',
			'danielbachhuber',
			'danieliser',
			'daniellacatus',
			'danielmorell',
			'danielpw',
			'dannyreaktiv',
			'darerodz',
			'darshitrajyaguru97',
			'dartiss',
			'daveguitaruno',
			'davidb',
			'davidbaumwald',
			'davidperez',
			'davilera',
			'dawidadach',
			'dd32',
			'debarghyabanerjee',
			'denis-de-bernardy',
			'dennysdionigi',
			'densinakum',
			'derekherman',
			'designsimply',
			'desrosj',
			'devasheeshkaul',
			'devrito',
			'devsabbirahmed',
			'dhananjaykuber',
			'dhrumilk',
			'dhruval04',
			'dhruvang21',
			'dhruvik18',
			'diebombe',
			'dilip2615',
			'dilipbheda',
			'dingo_d',
			'dinhtungdu',
			'divinenephron',
			'djcowan',
			'djivad',
			'dkarfa',
			'dlh',
			'dmsnell',
			'domainsupport',
			'dominiquepijnenburg',
			'donalirl',
			'dontfeedthecode',
			'doughamlin',
			'dougmelvin',
			'dpcalhoun',
			'drawcard',
			'dretzlaff',
			'drewapicture',
			'drivingralle',
			'dryanpress',
			'dsas',
			'dsawyers',
			'dscqbus',
			'dufresnesteven',
			'dustintechsmith',
			'ecgan',
			'eclev91',
			'eduwass',
			'ehti',
			'ejoling',
			'ekazda',
			'elazzabi',
			'elialum',
			'eliezerspp',
			'ellatrix',
			'elvismdev',
			'emaildano',
			'emlebrun',
			'emranahmed',
			'enaanfarhan',
			'epeicher',
			'ericlewis',
			'espellcaste',
			'ethanscorey',
			'ethitter',
			'etobiesen',
			'fabiankaegy',
			'faguni22',
			'faisal03',
			'faisalahammad',
			'faithcoder',
			'fakhriaz',
			'falgunihdesai',
			'fcoveram',
			'fellyph',
			'ffffelix',
			'fierevere',
			'firestar300',
			'fliespl',
			'flixos90',
			'frogdesk',
			'gaambo',
			'gabertronic',
			'gaeldenysiak',
			'gajendrasingh',
			'garrett-eclipse',
			'garyj',
			'gautam23',
			'georgestephanis',
			'gernberg',
			'get_dave',
			'getsyash',
			'ghorivipul97',
			'gigitux',
			'gitlost',
			'giuliorubelli',
			'glendaviesnz',
			'grantmkin',
			'greatislander',
			'greenshady',
			'guddu1315',
			'guido07111975',
			'guillaumeturpin',
			'gulamdastgir04',
			'gwwar',
			'gziolo',
			'hage',
			'hanimbarek',
			'hanneslsm',
			'haozi',
			'hardik2221',
			'hareesh-pillai',
			'harshalkadu',
			'harshbhonsle08',
			'harshdeepgill',
			'harshgajipara',
			'haruncpi',
			'hbhalodia',
			'helen',
			'helgatheviking',
			'hellofromtonya',
			'heybran',
			'hideishi',
			'hilayt24',
			'hiroshisato',
			'hitendra-chopda',
			'hiteshtalpada',
			'hmbashar',
			'hozefasmile',
			'hrohh',
			'hubersen',
			'hugod',
			'hugosolar',
			'humanify',
			'hurayraiit',
			'huubl',
			'huzaifaalmesbah',
			'iamadisingh',
			'iamkingsleyf',
			'iamshashank',
			'iamshubhamsp',
			'iamtakashi',
			'iandunn',
			'ignatiusjeroe',
			'igorradovanov',
			'ikriv',
			'im3dabasia1',
			'immeet94',
			'imokweb',
			'imranhasanraaz',
			'indirabiswas27',
			'ingeniumed',
			'ipstenu',
			'iqbal1hossain',
			'ironprogrammer',
			'isabel_brison',
			'ishikaatxecurify',
			'ismail0071',
			'isotropic',
			'itsroy69',
			'ivanottinger',
			'jabe',
			'jacobcassidy',
			'jagirbahesh',
			'jaiminp',
			'jakariaistauk',
			'jakeparis',
			'jameskoster',
			'jamesmarsland',
			'jamestitus299',
			'jamieburchell',
			'janthiel',
			'jarekmorawski',
			'jasalt',
			'jason_the_adams',
			'jasonsa19',
			'javiercasares',
			'jdahir0789',
			'jdy68',
			'jeffmatson',
			'jeffpaul',
			'jeffr0',
			'jeflopodev',
			'jeremiahbratton',
			'jeremyfelt',
			'jeryj',
			'jesin',
			'jessedyck',
			'jffng',
			'jhabdas',
			'jhmonroe',
			'jigar-bhanushali',
			'jigar9998',
			'jikamens',
			'jkmassel',
			'jnweaver',
			'jobata',
			'jochent',
			'jodamo5',
			'joedolson',
			'joehoyle',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnny5',
			'johnregan3',
			'johnvieth',
			'jojo256',
			'jonmcpartland',
			'jonoaldersonwp',
			'jonsurrell',
			'jorbin',
			'jordesign',
			'jorgefilipecosta',
			'josephscott',
			'josvelasco',
			'jrchamp',
			'jrf',
			'jrmd',
			'jsnajdr',
			'juampick',
			'juanfra',
			'juanmaguitar',
			'juliengardair',
			'justinahinon',
			'justlevine',
			'kabir93',
			'kadamwhite',
			'kaitohm',
			'kakomap',
			'kalpeshh',
			'karinchristen',
			'karl94',
			'karmatosed',
			'karolmanijak',
			'karthickmurugan',
			'karthikeya01',
			'kasparsd',
			'katinthehatsite',
			'katrinadtl',
			'kau-boy',
			'kausaralm',
			'kawauso',
			'kawsar007',
			'kaygee79',
			'kebbet',
			'kellychoffman',
			'kerfred',
			'kesselb',
			'kevin940726',
			'kevinlearynet',
			'kgagne',
			'khoipro',
			'khushdoms',
			'khushipatel15',
			'killerbishop',
			'kirasong',
			'kishanjasani',
			'kitchin',
			'kjellr',
			'kkmuffme',
			'kleor',
			'knutsp',
			'kpapazov',
			'kprocyszyn',
			'kraftbj',
			'kraftner',
			'krishaamer',
			'krokodok',
			'krunal265',
			'krupajnanda',
			'kshaner',
			'kub1x',
			'kubiq',
			'kunalpuri123',
			'kush123',
			'kushsharma',
			'lakrisgubben',
			'lakshyajeet',
			'lalitkumawat',
			'lancewillett',
			'laurisaarni',
			'ldanielgiuliani',
			'leadclown',
			'leedxw',
			'leemon',
			'leewillis77',
			'leonidasmilossis',
			'levinbaria',
			'lgadzhev',
			'lgseo',
			'lilgames',
			'liviopv',
			'logiclink',
			'logicrays',
			'lopo',
			'lordandy1984',
			'lordspace',
			'lovor',
			'lstraczynski',
			'lucasms',
			'luisherranz',
			'lukasfritzedev',
			'lukecavanagh',
			'lumiblog',
			'luminuu',
			'mabfahad',
			'maccyd',
			'madhavishah01',
			'madhudollu',
			'madtownlems',
			'maia12345',
			'maikuolan',
			'mamaduka',
			'manfcarlo',
			'manhatthien98',
			'manzoorwanijk',
			'maorb',
			'marc4',
			'marian1',
			'mariohamann',
			'marius84',
			'marktimemedia',
			'martythornley',
			'marybaum',
			'masteradhoc',
			'masummollaalhaz',
			'mat-lipe',
			'mathiscode',
			'matt',
			'matteoenna',
			'mattryanwalker',
			'mattwest',
			'mattyrob',
			'matveb',
			'maxpertici',
			'maxschmeling',
			'mayanktripathi32',
			'mayur8991',
			'mbigul',
			'mburridge',
			'mciampini',
			'mcsf',
			'mdmoreau',
			'mdviralsampat',
			'mdxfr',
			'mecaota',
			'megane9988',
			'mehedi_csit',
			'meher',
			'melchoyce',
			'metodiew',
			'mfgmicha',
			'michaelkeck',
			'michaelreetz',
			'migueluy',
			'mikachan',
			'mikefitzman',
			'mikehansenme',
			'mikejolley',
			'mikinc860',
			'mindctrl',
			'miqrogroove',
			'missveronicatv',
			'mista-flo',
			'mkaz',
			'mkeck',
			'mlaetitia1986',
			'mleray',
			'mleraygp',
			'mmaattiiaass',
			'mmcalister',
			'mnelson4',
			'mobarak',
			'mobius5150',
			'mohkatz',
			'mosescursor',
			'mrfoxtalbot',
			'mrwweb',
			'mt8biz',
			'mte90',
			'mtg169',
			'muddassirnasim',
			'mujuonly',
			'mukesh27',
			'mukulsingh27',
			'multidots1896',
			'mymothersdaughter',
			'n2erjo00',
			'n8finch',
			'nacin',
			'najmulsaju',
			'nanisamireddy',
			'narenin',
			'nareshbheda',
			'naveendwivedi',
			'navi161',
			'nazmul111',
			'ndiego',
			'nerrad',
			'newyorkerlaura',
			'nexbridge',
			'nextendweb',
			'neychok',
			'nickbrazilian',
			'nickchomey',
			'nickjbedford',
			'nickpagz',
			'nickstarkloff',
			'nickwilmot',
			'nico23',
			'nidhidhandhukiya',
			'nielslange',
			'nigelnelles',
			'nikunj8866',
			'nimeshatxecurify',
			'ninomiho',
			'ninos-ego',
			'noahtallen',
			'noisysocks',
			'noruzzaman',
			'nosilver4u',
			'nrqsnchz',
			'ntsekouras',
			'nyiriland',
			'o-o',
			'oandregal',
			'obenland',
			'obiplabon',
			'ocean90',
			'oceantober',
			'oferlaor',
			'oglekler',
			'ogrecooper',
			'okat',
			'onemaggie',
			'onlykawshar',
			'optimizingmatters',
			'opurockey',
			'othernoel',
			'otto42',
			'ourvalley',
			'owi',
			'paaljoachim',
			'pablohoneyhoney',
			'pagelab',
			'palak678',
			'panchalhimani711',
			'paragoninitiativeenterprises',
			'parinpanjari',
			'parthvataliya',
			'pateljaymin',
			'patpiwo',
			'patricia70',
			'paulbonneau',
			'paulkevan',
			'paulopmt1',
			'paulstanos',
			'pbearne',
			'pbiron',
			'pcarvalho',
			'pedrofigueroa1989',
			'pento',
			'peroks',
			'peteringersoll',
			'peterwilsoncc',
			'petitphp',
			'pfefferle',
			'philipjohn',
			'phillsav',
			'philsola',
			'piskvorky',
			'plari',
			'pmbaldha',
			'poena',
			'poojabhimani',
			'poojapadamad',
			'porg',
			'prab18hat',
			'praful2111',
			'pranjalpratapsingh',
			'prasadgupte',
			'prasadkarmalkar',
			'pratiklondhe',
			'presskopp',
			'presstoke',
			'prettyboymp',
			'priethor',
			'pryley',
			'psykro',
			'puggan',
			'q0rban',
			'quentinr64600',
			'rachelbaker',
			'rafiq91',
			'rahmohn',
			'rainbowgeek',
			'rainynewt',
			'ralucastn',
			'ramiy',
			'ramonopoly',
			'ravichudasama01',
			'ravigadhiyawp',
			'rayhatron',
			'rcorrales',
			'rcrdortiz',
			'realloc',
			'rehanali',
			'rejaulalomkhan',
			'renishsurani',
			'retrofox',
			'rezwanshiblu1952',
			'riadev',
			'richtabor',
			'riddhidave',
			'rinatkhaziev',
			'rinkalpagdar',
			'rishabhwp',
			'rishavdutta',
			'rishit30g',
			'ristojovanovic',
			'ritterml',
			'rmccue',
			'robertghetau',
			'robmcclel',
			'rockfire',
			'rodrigosprimo',
			'roelof',
			'rollybueno',
			'ronak44',
			'room34',
			'rotemg',
			'rutvikbhambhi2004',
			'ryan_b',
			'ryelle',
			'sabbir1991',
			'sabbir20',
			'sabernhardt',
			'sachinrajcp123',
			'sahiljadhav1617',
			'sainathpoojary',
			'sajib1223',
			'sajjad67',
			'sakibmoon',
			'salzano',
			'sam_a',
			'samirmalpande',
			'samueljseay',
			'sanchothefat',
			'sandeepdahiya',
			'sandipsinh007',
			'santosguillamot',
			'sarthaknagoshe2002',
			'satishprajapati',
			'saurabhdhariwal',
			'saxonafletcher',
			'sc0ttkclark',
			'scholdstrom',
			'schwipps',
			'scribu',
			'scruffian',
			'sebastianpisula',
			'sedmikrasky',
			'seifradwane',
			'sergeybiryukov',
			'sh4lin',
			'shadialaghbari',
			'shailu25',
			'shanemuir',
			'shekh0109',
			'sheldorofazeroth',
			'shilpaashokan94',
			'shimotomoki',
			'shiponkarmakar',
			'shireling',
			'shovan_jaya',
			'shreya0shrivastava',
			'shsajalchowdhury',
			'shyamgadde',
			'sidharthpandita',
			'siliconforks',
			'simison',
			'simonefontana',
			'sirlouen',
			'sjapaget',
			'skierpage',
			'skithund',
			'skorasaurus',
			'slaffik',
			'slimndap',
			'sllimrovert',
			'smerriman',
			'smrubenstein',
			'smushytaco',
			'snehapatil02',
			'snicco',
			'soean',
			'soulseekah',
			'sourabhjain',
			'sourav08',
			'soyebsalar01',
			'spacedmonkey',
			'spaceshipone',
			'spenserhale',
			'spstrap',
			'srikat',
			'stankea',
			'staurand',
			'stefanvelthuys',
			'stephenharris',
			'stoyanovgs',
			'strarsis',
			'subrataemfluence',
			'sudipatel007',
			'sujansarkar',
			'sukhendu2002',
			'sumitbagthariya16',
			'sunil25393',
			'sunnykasera',
			'sunyatasattva',
			'supernovia',
			'superpoincare',
			'suzukube',
			'svedish',
			'swb1192',
			'swissspidy',
			'syhussaini',
			'szepeviktor',
			'tabrisrp',
			'tacoverdo',
			'takahashi_fumiki',
			'takuword',
			'talldanwp',
			'tatof',
			'techpartho',
			'tecnogaming',
			'tfrommen',
			'tharsheblows',
			'theaminuldev',
			'thehercules',
			'thelmachido',
			'themiked',
			'tillkruess',
			'timhavinga',
			'timotheemoulin',
			'timothyblynjacobs',
			'timotijhof',
			'timse201',
			'tinkerbelly',
			'tinypixel',
			'tjarrett',
			'tjnowell',
			'tobiasbg',
			'tobifjellner',
			'tomdevisser',
			'toro_unit',
			'traxus',
			'trepmal',
			'tristanleboss',
			'truptikanzariya',
			'tsimshatsui',
			'tsquez',
			'tsteel',
			'tusharaddweb',
			'tusharbharti',
			'tussendoor',
			'tyrannous',
			'tyxla',
			'tz-media',
			'ugyensupport',
			'umeshnevase',
			'umeshsinghin',
			'unsalkorkmaz',
			'upadalavipul',
			'utsav72640',
			'utsavladani',
			'valentingrenier',
			'vbbp',
			'vcanales',
			'verygoode',
			'vevas',
			'vgnavada',
			'vidugupta',
			'vijendrajat',
			'vineet2003',
			'vipulgupta003',
			'vipulpatil',
			'viralsampat',
			'vishitshah',
			'vladimiraus',
			'vortfu',
			'vrishabhsk',
			'vyasnaman',
			'walterebert',
			'webmandesign',
			'websupporter',
			'webwrotter',
			'welcher',
			'westi',
			'westonruter',
			'whaze',
			'whyisjake',
			'widhy980',
			'wido',
			'wildworks',
			'wonderboymusic',
			'wpfed',
			'wpfy',
			'wplmillet',
			'wprashed',
			'wpsmith',
			'xate',
			'xavilc',
			'xerpa43',
			'xipasduarte',
			'xkon',
			'xmic',
			'yagniksangani',
			'yashjawale',
			'yashyadav247',
			'yasunocco',
			'yogeshbhutkar',
			'yogieanamcara',
			'youknowriad',
			'zebulan',
			'zeelthakkar',
			'zieladam',
			'zodiac1978',
			'zoonini',
			'zunaid321',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

