<?php

class WP_61_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matt'                => [ 'Matt Mullenweg', 'Release Lead' ],
					'desrosj'             => [ 'Jonathan Desrosiers', 'Release Lead' ],
					'priethor'            => [ 'Héctor Prieto', 'Release Lead' ],
					'davidbaumwald'       => 'David Baumwald',
					'JeffPaul'            => 'Jeff Paul',
					'kirasong'            => 'Kira Song',
					'cbravobernal'        => 'Carlos Bravo',
					'czapla'              => 'Michal Czaplinski',
					'Bernhard Reiter'     => 'Bernhard Reiter',
					'audrasjb'            => 'Jean-Baptiste Audras',
					'chaion07'            => 'Ahmed Chaion',
					'ndiego'              => 'Nick Diego',
					'annezazu'            => 'Anne McCarthy',
					'milana_cap'          => 'Milana Cap',
					'bph'                 => 'Birgit Pauli-Haack',
					'femkreations'        => 'Femy Praseeth',
					'jpantani'            => 'Jonathan Pantani',
					'dansoschin'          => 'Dan Soschin',
					'ironprogrammer'      => 'Brian Alexander',
					'richtabor'           => 'Rich Tabor',
					'beafialho'           => 'Beatriz Fialho',
					'mikachan'            => 'Sarah Norris',
					'matveb'              => 'Matias Ventura',
					'chanthaboune'        => 'Josepha Haden',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'tyxla'               => 'Marin Atanasov',
					'Mamaduka'            => 'George Mamadashvili',
					'costdev'             => 'Colin Stewart',
					'peterwilsoncc'       => 'Peter Wilson',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'gziolo'              => 'Greg Ziółkowski',
					'0mirka00'            => 'Lena Morita',
					'jrf'                 => 'Juliette Reinders Folmer',
					'ramonopoly'          => 'Ramon James',
					'hellofromTonya'      => 'Tonya Mork',
					'spacedmonkey'        => 'Jonny Harris',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'ntsekouras'          => 'Nik Tsekouras',
					'mciampini'           => 'Marco Ciampini',
					'mukesh27'            => 'Mukesh Panchal',
					'andrewserong'        => 'Andrew Serong',
					'glendaviesnz'        => 'Glen Davies',
					'scruffian'           => 'Ben Dwyer',
					'talldanwp'           => 'Daniel Richards',
					'sabernhardt'         => 'Stephen Bernhardt',
					'johnbillion'         => 'John Blackbourn',
					'wildworks'           => 'Aki Hamano',
					'zieladam'            => 'Adam Zielinski',
					'jorgefilipecosta'    => 'Jorge Costa',
					'aristath'            => 'Ari Stathopoulos',
 					'Joen'                => 'Joen Asmussen',
					'poena'               => 'Carolina Nymark',
					'webcommsat'          => 'Abha Thakor',
					'mburridge'           => 'Michael Burridge',
					'ellatrix'            => 'Ella van Durpe',
					'walbo'               => 'Petter Walbø Johnsgård',
					'oandregal'           => 'André',
					'noisysocks'          => 'Robert Anderson',
					'get_dave'            => 'David Smith',
					'javiarce'            => 'Javier Arce',
					'jameskoster'         => 'James Koster',
					'webtechpooja'        => 'Pooja Derashri',
					'nalininonstopnewsuk' => 'Nalini Thakor',
					'oglekler'            => 'Olga Gleckler',
					'courane01'           => 'Courtney Robertson',
					'marybaum'            => 'Mary Baum',
					'azhiyadev'           => 'Hauwa Abashiya',
					'zoonini'             => 'Kathryn Presner',
					'laurlittle'          => 'Lauren Stein',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'_smartik_',
			'0mirka00',
			'10upsimon',
			'1naveengiri',
			'5um17',
			'aaemnnosttv',
			'aaroncampbell',
			'aaronrobertshaw',
			'acoulombe',
			'adampickering',
			'adamsilverstein',
			'addiestavlo',
			'admwgn',
			'aduth',
			'aezazshekh',
			'afercia',
			'afragen',
			'afrid1719',
			'ajlende',
			'akabarikalpesh',
			'akshitsethi',
			'alaca',
			'alamgircsebd',
			'alanp57',
			'alansyue',
			'albatross10',
			'alberuni-azad',
			'alexstine',
			'aljullu',
			'allancole',
			'allisonplus',
			'amirkamizi',
			'amjadr360',
			'amustaque97',
			'anantajitjg',
			'andraganescu',
			'andrewnz',
			'andrewserong',
			'andrija',
			'andykeith',
			'aniketpatel',
			'anitanenova',
			'ankit-k-gupta',
			'annabansaghi',
			'annezazu',
			'antonvlasenko',
			'antpb',
			'apedog',
			'apermo',
			'apokalyptik',
			'arcangelini',
			'archon810',
			'aristath',
			'armondal',
			'arrasel403',
			'arturgrabo',
			'aspexi',
			'audrasjb',
			'aurooba',
			'ayeshrajans',
			'azaozz',
			'azouamauriac',
			'azurseisme',
			'baned',
			'barneydavey',
			'batmoo',
			'baxbridge',
			'bbobnis',
			'beafialho',
			'bengreeley',
			'benjgrolleau',
			'benoitchantre',
			'benouare',
			'bernhard-reiter',
			'bgardner',
			'bhrugesh12',
			'birgire',
			'bjorn2404',
			'bjorsch',
			'blackawxs',
			'bobbingwide',
			'boblindner',
			'boemedia',
			'boniu91',
			'boonebgorges',
			'bordoni',
			'bosconiandynamics',
			'bph',
			'burgiuk',
			'burhandodhy',
			'bwbama',
			'byohann6',
			'cadlec',
			'cagsmith',
			'camwynsp',
			'cantuaria',
			'carazo',
			'carlosgprim',
			'cavalierlife',
			'cbirdsong',
			'cbravobernal',
			'cbringmann',
			'cdbessig',
			'celloexpressions',
			'cfinke',
			'chaion07',
			'chanthaboune',
			'chaton666',
			'chesio',
			'chetan200891',
			'chintan1896',
			'chopinbach',
			'chouby',
			'chrisbudd1',
			'chriscct7',
			'chrisguitarguy',
			'chrishardie',
			'christinavoudouris',
			'chynnabenton',
			'circlecube',
			'ckanderson22',
			'clarkeemily',
			'claytoncollie',
			'clorith',
			'codekraft',
			'codesdnc',
			'codewhy',
			'collet',
			'colonelphantom',
			'colorful-tones',
			'costdev',
			'courane01',
			'craigfrancis',
			'crazycoders',
			'critterverse',
			'csesumonpro',
			'cu121',
			'curdin',
			'cwbudde',
			'cybr',
			'cyrillbolliger',
			'czapla',
			'czarate',
			'dainemawer',
			'daisyo',
			'daledupreez',
			'damonganto',
			'danfarrow',
			'danielbachhuber',
			'danieliser',
			'dansoschin',
			'darerodz',
			'dariak',
			'darkog',
			'darkskipper',
			'datainterlock',
			'dave1010',
			'davidanderson',
			'davidbaumwald',
			'davidbinda',
			'davidvongries',
			'daviedr',
			'daxelrod',
			'daymobrew',
			'dcowgill',
			'dd32',
			'deepakvijayan',
			'deksar',
			'denis-de-bernardy',
			'denishua',
			'dennisatyoast',
			'derekblank',
			'design_dolphin',
			'desmith',
			'desrosj',
			'devnel',
			'devtanbir',
			'dg12345',
			'dgwyer',
			'dharm1025',
			'dhilditch',
			'dhl',
			'dianeco',
			'dilipbheda',
			'dingdang',
			'dingo_d',
			'dinhtungdu',
			'dipakparmar443',
			'divyeshgodhani',
			'dkotter',
			'dlh',
			'dmsnell',
			'donmhico',
			'dougal',
			'dougwollison',
			'dovyp',
			'dpcalhoun',
			'drewapicture',
			'drivingralle',
			'drzraf',
			'dsas',
			'dwainm',
			'dxd5001',
			'earnjam',
			'eatingrules',
			'eboxnet',
			'eclev91',
			'edent',
			'eedee',
			'eherman24',
			'ehtis',
			'eidolonnight',
			'eliezerspp',
			'ellatrix',
			'elpanda13gmailcom',
			'elten',
			'enchiridion',
			'engahmeds3ed',
			'estelaris',
			'ethitter',
			'eugenemanuilov',
			'evildon',
			'fabiankaegy',
			'faisal03',
			'faison',
			'fcoveram',
			'felipeelia',
			'fellyph',
			'fierevere',
			'figureone',
			'filosofo',
			'flixos90',
			'flootr',
			'florianbrinkmann',
			'fpodhorsky',
			'franz00',
			'fuadragib',
			'fullofcaffeine',
			'furi3r',
			'gabertronic',
			'gabri3lmarques',
			'gamecreature',
			'garrett-eclipse',
			'garyj',
			'garymatthews919',
			'gdetassigny',
			'geekstreetwp',
			'georgestephanis',
			'geriux',
			'get_dave',
			'gigitux',
			'giox069',
			'gisgeo',
			'gitlost',
			'giuseppemazzapica',
			'glendaviesnz',
			'gmagicscott',
			'gmovr',
			'goldenapples',
			'graham73may',
			'grandeljay',
			'grantmkin',
			'grapplerulrich',
			'greenshady',
			'greg24',
			'greglone',
			'gregorlove',
			'griffinjt',
			'gunterer',
			'gvgvgvijayan',
			'gziolo',
			'h2ham',
			'hakanca',
			'hakre',
			'hansjovisyoast',
			'haritpanchal',
			'harshvaishnav',
			'hasanuzzamanshamim',
			'helen',
			'hellofromtonya',
			'henrywright',
			'here',
			'herregroen',
			'hilayt24',
			'hinjiriyo',
			'hiren1094',
			'hiyascout',
			'howdy_mcgee',
			'htdat',
			'hugodevos',
			'hurayraiit',
			'huubl',
			'hyperbrand',
			'hypest',
			'hztyfoon',
			'iamarinoh',
			'iamjaydip',
			'ianbelanger',
			'iandunn',
			'iansvo',
			'icaspar',
			'ideag',
			'igmoweb',
			'igorsch',
			'igrigorik',
			'ilovecats7',
			'ilunabar',
			'im_niloy',
			'imadarshakshat',
			'inc2734',
			'infolu',
			'innovext',
			'ipajen',
			'ipstenu',
			'irecinius',
			'ironprogrammer',
			'isabel_brison',
			'isaumya',
			'itsjonq',
			'iulia-cazan',
			'ivanjeronimo',
			'iviweb',
			'jakariaistauk',
			'jamesckemp',
			'jameskoster',
			'jamieburchell',
			'janthiel',
			'jarretc',
			'javiarce',
			'javiercasares',
			'jb510',
			'jchambo',
			'jdgrimes',
			'jeawhanlee',
			'jeffpaul',
			'jeherve',
			'jeremyfelt',
			'jeroenreumkens',
			'jffng',
			'jhabdas',
			'jhart35',
			'jhnstn',
			'jigar-bhanushali',
			'jnz31',
			'joedolson',
			'joegrainger',
			'joehoyle',
			'joelhardi',
			'joelmadigan',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnmark8080',
			'johnregan3',
			'johnstonphilip',
			'johnwatkins0',
			'jonmackintosh',
			'jonny-s',
			'jonoaldersonwp',
			'jonsurrell',
			'joostdevalk',
			'jorbin',
			'jorgefilipecosta',
			'joshuaabenazer',
			'jostnes',
			'josvelasco',
			'joyously',
			'jpantani',
			'jrbeilke',
			'jrf',
			'jsh4',
			'jsnajdr',
			'jsnjohnston',
			'juberstine',
			'juhise',
			'juliemoynat',
			'juliobox',
			'just0nequestion',
			'justinahinon',
			'justinsainton',
			'jyolsna',
			'kacper3355',
			'kadamwhite',
			'kafleg',
			'kajalgohel',
			'kamig478',
			'kanlukasz',
			'kapilpaul',
			'karinclimber',
			'karlgroves',
			'karlijnbk',
			'karmatosed',
			'kasparsd',
			'kbjohnson90',
			'kbrownkd',
			'kebbet',
			'kellychoffman',
			'kevin940726',
			'kevinb',
			'khag7',
			'khoipro',
			'khokansardar',
			'khromov',
			'killua99',
			'kirasong',
			'kishanjasani',
			'kitchin',
			'kjellr',
			'kkmuffme',
			'kkoppenhaver',
			'kmadhak',
			'knutsp',
			'konradyoast',
			'konyoldeath',
			'kovshenin',
			'kraftbj',
			'krishaweb',
			'krupalpanchal',
			'kucrut',
			'kurtpayne',
			'kwillmorth',
			'laboiteare',
			'larrach',
			'larsmqller',
			'laurelfulford',
			'laurent22777',
			'laurlittle',
			'lazam786',
			'leemon',
			'leewillis77',
			'leogermani',
			'leonidasmilossis',
			'lev0',
			'linsoftware',
			'lonnylot',
			'lopo',
			'lovor',
			'lozula',
			'lucasbustamante',
			'lucilastancato',
			'luigipulcini',
			'luisherranz',
			'lukecavanagh',
			'luminuu',
			'maahrokh',
			'maartenj',
			'maciejmackowiak',
			'madhudollu',
			'madpixels',
			'maksimkuzmin',
			'malthert',
			'mamaduka',
			'manfcarlo',
			'manishsongirkar36',
			'manooweb',
			'manuilov',
			'manzoorwanijk',
			'manzurahammed',
			'marcyoast',
			'marekdedic',
			'markbiek',
			'markhowellsmead',
			'markjaquith',
			'markoheijnen',
			'markparnell',
			'martinkrcho',
			'marybaum',
			'mashikag',
			'mashukushibiki',
			'masteradhoc',
			'mattchowning',
			'mattheweppelsheimer',
			'matthiaspabst',
			'matthiasreinholz',
			'mattkeys',
			'mattwondra',
			'mattyrob',
			'matveb',
			'maximej',
			'maximemeganck',
			'mayankmajeji',
			'maythamalsudany',
			'mayuge',
			'mboynes',
			'mburridge',
			'mciampini',
			'mcliwanow',
			'mcsf',
			'mdgl',
			'mdrago',
			'mehedi890',
			'meher',
			'mehulkaklotar',
			'melchoyce',
			'meloniq',
			'merkys',
			'meysamnorouzi',
			'mfgmicha',
			'mhkuu',
			'michaelbourne',
			'miguelaxcar',
			'mihai2u',
			'mihaidumitrascu',
			'mikachan',
			'mikehansenme',
			'mikejolley',
			'mikemanzo',
			'milana_cap',
			'milindmore22',
			'mimitips',
			'miqrogroove',
			'mitogh',
			'mitweka',
			'mjkhajeh',
			'mkaz',
			'mkox',
			'mlajo',
			'mmaattiiaass',
			'mmaumio',
			'mohitdadhich10',
			'monolithon',
			'mordauk',
			'mrdollu',
			'mreishus',
			'mrfoxtalbot',
			'mrobit',
			'msnewas',
			'msolution',
			'msurdi',
			'mt8biz',
			'mte90',
			'mtias',
			'mukesh27',
			'multidots1896',
			'mvraghavan',
			'mw108',
			'mweichert',
			'mxbclang',
			'n8finch',
			'nacin',
			'nalininonstopnewsuk',
			'namithjawahar',
			'nareshbheda',
			'nateallen',
			'nathanatmoz',
			'nathannoom',
			'navigatrum',
			'ndiego',
			'neffff',
			'nekojonez',
			'nendeb55',
			'netweb',
			'neychok',
			'nhadsall',
			'nhuja',
			'nico23',
			'nidhidhandhukiya',
			'nikeo',
			'nikkigagency',
			'ninos-ego',
			'nithi22',
			'nithins53',
			'nlpro',
			'noahtallen',
			'noisysocks',
			'nomnom99',
			'noplanman',
			'nouarah',
			'ntsekouras',
			'numidwasnotavailable',
			'nunomorgadinho',
			'nuryko',
			'nuvopoint',
			'nvartolomei',
			'oakesjosh',
			'oandregal',
			'obayedmamur',
			'obenland',
			'obliviousharmony',
			'ocean90',
			'ockham',
			'oglekler',
			'oguzkocer',
			'oliverstapelfeldt',
			'olliejones',
			'omaeyusuke',
			'oneearth27',
			'onemaggie',
			'onnimonni',
			'opr18',
			'otto42',
			'outrankjames',
			'ovidiul',
			'oztaser',
			'p_enrique',
			'paaljoachim',
			'pablohoney',
			'palmiak',
			'paragoninitiativeenterprises',
			'passoniate',
			'patrickgroot',
			'paulkevan',
			'paulohcruz',
			'paulopmt1',
			'pavanpatil1',
			'pavelschoffer',
			'pbearne',
			'pbiron',
			'pbking',
			'pcfreak30',
			'pedromendonca',
			'pento',
			'peterwilsoncc',
			'petitphp',
			'phillsav',
			'pkolenbr',
			'pls78',
			'poena',
			'poliuk',
			'pooja1210',
			'praful2111',
			'pratiweb',
			'presents111',
			'presskopp',
			'presstoke',
			'priethor',
			'primetimejas',
			'priyomukul',
			'prokium',
			'psykro',
			'pypwalters',
			'rachelbaker',
			'raduiason',
			'rafiahmedd',
			'rahmohn',
			'rajanpanchal2028',
			'rajeshraval786',
			'rakibwordpress',
			'ralucastn',
			'ramon-fincken',
			'ramonopoly',
			'randhirexpresstech',
			'rarst',
			'ravanh',
			'ravipatel',
			'rcanepa',
			'rcorrales',
			'rebasaurus',
			'rehanali',
			'renathoc',
			'renegeuze',
			'revgeorge',
			'rflw',
			'rherault',
			'ribaricplusplus',
			'richtabor',
			'rinatkhaziev',
			'rinkychowdhury9',
			'rishishah',
			'rjasdfiii',
			'rkaiser0324',
			'rmccue',
			'robertghetau',
			'robinwpdeveloper',
			'robmiller',
			'rodricus',
			'rodrigosevero',
			'rolfsiebers',
			'rollybueno',
			'romulodl',
			'ross_ritchey',
			'rsiddharth',
			'rudlinkon',
			'russel07',
			'ryan',
			'ryankienstra',
			'ryanmurphy',
			'ryelle',
			'ryno267',
			'ryokuhi',
			'sabbirmc',
			'sabernhardt',
			'saggre',
			'sajjad67',
			'samikeijonen',
			'sandipmondal',
			'sandrasanzdev',
			'santosguillamot',
			'sarahricker',
			'sathyapulse',
			'sc0ttkclark',
			'schlessera',
			'schutzsmith',
			'scofennellgmailcom',
			'scribu',
			'scruffian',
			'seakashdiu',
			'sean212',
			'sebastianpisula',
			'sebastienserre',
			'seedsca',
			'sergeybiryukov',
			'sergiomdgomes',
			'seriouslysenpai',
			'sethta',
			'shanjidah',
			'sharjeelkhanvmi',
			'shenyanzhi',
			'shimotomoki',
			'shireling',
			'shoaibkarimali',
			'shraboni',
			'shreyasikhar26',
			'shuvo586',
			'siobhyb',
			'sippis',
			'sirzooro',
			'skithund',
			'slaffik',
			'slobodanmanic',
			'smit08',
			'sobatkras',
			'soean',
			'spacedmonkey',
			'ste_95',
			'steelwagstaff',
			'stentibbing',
			'sterlo',
			'stevenlinx',
			'steveo2000',
			'strategio',
			'studiolxv',
			'subrataemfluence',
			'sumitbagthariya16',
			'sumitsingh',
			'sunil25393',
			'sunyatasattva',
			'superpoincare',
			'swissspidy',
			'synchro',
			'system909',
			'tabrisrp',
			'tahmidulkarim',
			'talldanwp',
			'tan007',
			'tanvirul',
			'targz',
			'taskotr',
			'tazotodua',
			'tbember',
			'tellyworth',
			'teunvgisteren',
			'thakkarhardik',
			'tharsheblows',
			'thelovekesh',
			'thijso',
			'threadi',
			'tillkruess',
			'timkersten655',
			'timothyblynjacobs',
			'tj692',
			'tjnowell',
			'tlovett1',
			'tmooredev',
			'tobiasbg',
			'tobifjellner',
			'tomasztunik',
			'tomepajk',
			'tomjdv',
			'tommusrhodus',
			'tonylocalword',
			'toro_unit',
			'transl8or',
			'trapsta',
			'tremidkhar',
			'trevorpfromsandee',
			'turtlepod',
			'tushar284',
			'tweetythierry',
			'tykoted',
			'tyxla',
			'ugyensupport',
			'umesh84',
			'uofaberdeendarren',
			'upadalavipul',
			'utsavmadaan823',
			'utz119',
			'vasartam',
			'vcanales',
			'vdankbaar',
			'vdwijngaert',
			'velochicdunord',
			'vikasprogrammer',
			'viper007bond',
			'viralsampat',
			'virgar',
			'vishalkakadiya',
			'voldemortensen',
			'vortfu',
			'vtad',
			'walbo',
			'webbeetle',
			'webcommsat',
			'webmandesign',
			'welcher',
			'welenofsky',
			'westi',
			'westonruter',
			'whaze',
			'whissi',
			'wildworks',
			'williampatton',
			'withinboredom',
			'woji29911',
			'wonderboymusic',
			'wparslan',
			'wpsmith',
			'xconsau',
			'xknown',
			'xparham',
			'xylocone',
			'yahil',
			'yannielsen',
			'yellyc',
			'yoavf',
			'youknowriad',
			'zaerl',
			'zaguiini',
			'zebulan',
			'zenaulislam',
			'zieladam',
			'zikubd',
			'ziposc',
			'zodiac1978',
			'zoonini',
			'zutigrm',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'http://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'http://getid3.sourceforge.net/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'http://cherne.net/brian/resources/jquery.hoverIntent.html' ],
			[ 'imgAreaSelect', 'http://odyniec.net/projects/imgareaselect/' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'http://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'http://touchpunch.furf.com/' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'http://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'http://mediaelementjs.com/' ],
			[ 'Moment', 'http://momentjs.com/' ],
			[ 'PclZip', 'http://www.phpconcept.net/pclzip/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'http://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'http://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'http://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'http://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'http://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'http://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

