<?php

class WP_64_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'chanthaboune'        => [ 'Josepha Haden', 'Release Lead' ],
					'cbringmann'          => [ 'Chloé Bringmann', 'Release Lead' ],
					'metalandcoffee'      => [ 'Ebonie Butler', 'Release Lead' ],
					'akshayar'            => [ 'Akshaya Rane', 'Release Lead' ],
					'kirasong'            => 'Kira Song',
					'hellofromTonya'      => 'Tonya Mork',
					'mikachan'            => 'Sarah Norris',
					'siobhyb'             => 'Siobhan Bamber',
					'karmatosed'          => 'Tammie Lister',
					'nicolefurlan'        => 'Nicole Furlan',
					'oglekler'            => 'Olga Gleckler',
					'annezazu'            => 'Anne McCarthy',
					'bph'                 => 'Birgit Pauli-Haack',
					'webcommsat'          => 'Abha Thakor',
					'femkreations'        => 'Femy Praseeth',
					'611shabnam'          => 'Mushrit Shabnam',
					'meher'               => 'Meher Bala',
					'rmartinezduque'      => 'Reyes Martínez',
					'SeReedMedia'         => 'Sé Reed',
					'webtechpooja'        => 'Pooja Derashri',
					'elmastudio'          => 'Ellen Bauer',
					'estelaris'           => 'Estela Rueda',
					'clarkeemily'         => 'Emily Clarke',
					'courtneypk'          => 'Courtney Patubo Kranzke',
					'courane01'           => 'Courtney Robertson',
					'luminuu'             => 'Jessica Lyschik',
					'onemaggie'           => 'Maggie Cabrera',
					'marybaum'            => 'Mary Baum',
					'ohia'                => 'Ohia',
					'nudge'               => 'Sonia Gaballa',
					'cathibosco1'         => 'Cathi Bosco',
					'matveb'              => 'Matias Ventura',
					'SergeyBiryukov'      => 'Sergey Biryukov',
					'mukesh27'            => 'Mukesh Panchal',
					'Mamaduka'            => 'George Mamadashvili',
					'costdev'             => 'Colin Stewart',
					'spacedmonkey'        => 'Jonny Harris',
					'flixos90'            => 'Felix Arntz',
					'wildworks'           => 'Aki Hamano',
					'ramonopoly'          => 'Ramon James',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'joedolson'           => 'Joe Dolson',
					'audrasjb'            => 'Jean-Baptiste Audras',
					'desrosj'             => 'Jonathan Desrosiers',
					'richtabor'           => 'Rich Tabor',
					'isabel_brison'       => 'Isabel Brison',
					'joemcgill'           => 'Joe McGill',
					'gziolo'              => 'Greg Ziółkowski',
					'tyxla'               => 'Marin Atanasov',
					'glendaviesnz'        => 'Glen Davies',
					'afercia'             => 'Andrea Fercia',
					'ellatrix'            => 'Ella van Durpe',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'jrf'                 => 'Juliette Reinders Folmer',
					'Bernhard Reiter'     => 'Bernhard Reiter',
					'poena'               => 'Carolina Nymark',
					'get_dave'            => 'David Smith',
					'swissspidy'          => 'Pascal Birchler',
					'jameskoster'         => 'James Koster',
					'youknowriad'         => 'Riad Benguella',
					'ntsekouras'          => 'Nik Tsekouras',
					'westonruter'         => 'Weston Ruter',
					'trynet'              => 'Bud Kraus',
					'andraganescu'        => 'Andrei Draganescu',
					'luisherranz'         => 'Luis Herranz',
					'jorbin'              => 'Aaron Jorbin',
					'scruffian'           => 'Ben Dwyer',
					'andrewserong'        => 'Andrew Serong',
					'rajinsharwar'        => 'Rajin Sharwar',
					'aristath'            => 'Ari Stathopoulos',
					'dpcalhoun'           => 'David Calhoun',
					'jsnajdr'             => 'Jarda Snajdr',
					'kevin940726'         => 'Kai Hao',
					'James Roberts'       => 'James Roberts',
					'nalininonstopnewsuk' => 'Nalini Thakor',
					'codente'             => 'Jamie VanRaalte',
					'sabernhardt'         => 'Stephen Bernhardt',
					'CoachBirgit'         => 'Birgit Olzem',
					'annebovelett'        => 'Anne-Mieke Bovelett',
					'huzaifaalmesbah'     => 'Huzaifa Al Mesbah',
					'francina'            => 'Francesca Marano',
					'peterwilsoncc'       => 'Peter Wilson',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'10upsimon',
			'1happyplace',
			'68kheart',
			'6adminit',
			'90lines',
			'aaroncampbell',
			'aaronrobertshaw',
			'aayusha',
			'acirujano',
			'adamsilverstein',
			'adhun',
			'adrianduffell',
			'aegkr',
			'afercia',
			'afragen',
			'ahardyjpl',
			'ahmedgeek',
			'ajakaroth',
			'ajlende',
			'ajmcfadyen',
			'akihiroharai',
			'alaminfirdows',
			'alexandrebuffet',
			'alexkingorg',
			'alexstine',
			'alishabajracharya27',
			'aljullu ',
			'allisonplus',
			'alvitazwar052',
			'amedv',
			'anandau14',
			'andraganescu',
			'andrewhayward',
			'andrewserong',
			'angelasjin',
			'ankit-k-gupta',
			'ankitmaru',
			'anlino',
			'annashopina',
			'annebovelett',
			'annezazu',
			'anphira',
			'antonvlasenko',
			'antpb',
			'anveshika',
			'apeatling',
			'aplauche',
			'archon810',
			'arena',
			'aristath',
			'armondal',
			'arnedb',
			'artemiosans',
			'arthur791004',
			'asafm7',
			'ashikur698',
			'askdesign',
			'aslamdoctor',
			'atachibana',
			'atimmer',
			'audrasjb',
			'aurooba',
			'austinginder',
			'ayeshrajans',
			'azaozz',
			'azharckra',
			'balub',
			'bangank36',
			'barbmiller',
			'barry',
			'bartkalisz',
			'basiliskan',
			'battelfred',
			'baxbridge',
			'beafialho',
			'behoney',
			'bengreeley',
			'benharri',
			'benimub',
			'benjamin_zekavica',
			'benjaminknox',
			'benoitchantre',
			'bernhard-reiter',
			'bfintal',
			'bgardner',
			'bhrugesh12',
			'bijayyadav',
			'binsaifullah',
			'bitmachina',
			'bjorsch',
			'bmalsht',
			'bobbingwide',
			'bonkerz',
			'boogah',
			'bookwyrm',
			'boonebgorges',
			'bor0',
			'bordoni',
			'bosskhj',
			'bph',
			'bplv',
			'bradley2083',
			'brookedot',
			'brookemk',
			'bvreeman22',
			'cais',
			'carlosgprim',
			'cathibosco1',
			'cbravobernal',
			'cbringmann',
			'ceer',
			'cenkdemir',
			'chaion07',
			'chasedsiedu',
			'chesio',
			'chintan1896',
			'chipbennett',
			'chriscct7',
			'chrisdesrochers',
			'clorith',
			'coachbirgit',
			'codente',
			'codersantosh',
			'codex-m',
			'coffee2code',
			'colorful-tones',
			'coreyw',
			'costdev',
			'courane01',
			'crazyjaco',
			'crstauf',
			'crunnells',
			'cu121',
			'cyberchicken',
			'cybr',
			'czapla',
			'dajeema',
			'damonsharp',
			'danielbachhuber',
			'danieldudzic',
			'danieltj',
			'dantovbein',
			'darerodz',
			'darkfate',
			'darshitrajyaguru97',
			'dasnitesh780',
			'dave03',
			'davelo',
			'davidbaumwald',
			'davidbinda',
			'dawidurbanski',
			'daxelrod',
			'dd32',
			'deepakvijayan',
			'derekblank',
			'desmith',
			'desrosj',
			'devmuhib',
			'dfavor',
			'dhamibirendra',
			'dharm1025',
			'dhrumilk',
			'dhruvishah2203',
			'dianeco',
			'didierjm',
			'dilipbheda',
			'dimitrism',
			'dingo_d',
			'djcowan',
			'dkotter',
			'dlh',
			'dmsnell',
			'domainsupport',
			'doughamlin',
			'dpcalhoun',
			'drewapicture',
			'dryanpress',
			'dsas',
			'duck_',
			'dunhakdis',
			'earnjam',
			'eatingrules',
			'ediamin',
			'ehtis',
			'ellatrix',
			'elmastudio',
			'elrae',
			'emailjoey',
			'emilyatmobtown',
			'emirpprime',
			'emrikol',
			'enodekciw',
			'esratpopy',
			'estelaris',
			'extendwings',
			'fabiankaegy',
			'fabiorubioglio',
			'faguni22',
			'faisal03',
			'felipeelia',
			'fierevere',
			'flixos90',
			'floydwilde',
			'foliovision',
			'francina',
			'fullofcaffeine',
			'fzhantw',
			'gaambo',
			'garrett-eclipse',
			'garyc40',
			'geriux',
			'get_dave',
			'gigitux',
			'gitlost',
			'glendaviesnz',
			'gnanasekaran',
			'gonzomir',
			'gpotter',
			'grantmkin',
			'grapplerulrich',
			'greenshady',
			'gregfuller',
			'gregross',
			'gungeekatx',
			'guss77',
			'gvgvgvijayan',
			'gziolo',
			'hanneslsm',
			'hareesh-pillai',
			'harshgajipara',
			'hasanuzzamanshamim',
			'hazdiego',
			'hbhalodia',
			'helen',
			'hellofromtonya',
			'hiyascout',
			'hlunter',
			'howdy_mcgee',
			'hrshahin',
			'huzaifaalmesbah',
			'hztyfoon',
			'iammehedi1',
			'iandunn',
			'icaleb',
			'incursadesigns',
			'ingeniumed',
			'ipajen',
			'ironprogrammer',
			'isabel_brison',
			'itecrs',
			'itsjustdj',
			'ivanzhuck',
			'jaimieolmstead',
			'jakariaistauk',
			'jakemgold',
			'james0r',
			'jameskoster',
			'jamiemchale',
			'jane',
			'jason_the_adams',
			'jastos',
			'jb510',
			'jblz',
			'jeffeverhart383',
			'jeffikus',
			'jeffpaul',
			'jeflopodev',
			'jeherve',
			'jeremyfelt',
			'jeremyyip',
			'jeryj',
			'jesin',
			'jessicagoddard',
			'jessplease',
			'jffng',
			'jick',
			'jipmoors',
			'jivygraphics',
			'joedolson',
			'joehoyle',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnregan3',
			'jonoaldersonwp',
			'joostdevalk',
			'joppuyo',
			'jorbin',
			'jordanpak',
			'jordesign',
			'jorgefilipecosta',
			'joshcanhelp',
			'joshuatf',
			'jrf',
			'jrtashjian',
			'jsnajdr',
			'juanfra',
			'juanmaguitar',
			'jyolsna',
			'kadamwhite',
			'kafleg',
			'kalmang',
			'kalpeshh',
			'karl94',
			'karlijnbk',
			'karmacharya50',
			'karmatosed',
			'karolmanijak',
			'kawsaralameven',
			'kdowns',
			'kebbet',
			'kevin940726',
			'kevinfodness',
			'khleomix',
			'kharisblank',
			'khokansardar',
			'kimannwall',
			'kirasong',
			'kishanjasani',
			'kkmuffme',
			'kkoppenhaver',
			'kopila47',
			'kovshenin',
			'kraftbj',
			'krokodok',
			'krupalpanchal',
			'ktaron',
			'l1nuxjedi',
			'labunchemjong',
			'lada7042',
			'lakshmananphp',
			'lancewillett',
			'lastsplash',
			'laumindproductscomau',
			'launchinteractive',
			'laurelfulford',
			'leewillis77',
			'letraceursnork',
			'lgladdy',
			'lhe2012',
			'linsoftware',
			'littlebigthing',
			'lloydbudd',
			'lopo',
			'luckybhumkar',
			'luisherranz',
			'lukecavanagh',
			'luminuu',
			'lunaluna',
			'lyndauwp',
			'maahrokh',
			'maciejmackowiak',
			'madejackson',
			'madhudollu',
			'mai21',
			'maltfield',
			'mamaduka',
			'maneshtimilsina',
			'manfcarlo',
			'manzoorwanijk',
			'mapumba',
			'marcelle42',
			'marcoevich',
			'margolisj',
			'markjaquith',
			'markoserb',
			'martatorre',
			'martinkrcho',
			'marybaum',
			'masoudnkh',
			'masteradhoc',
			'mathsgrinds',
			'mattheu',
			'mattheweppelsheimer',
			'matthewfarlymn',
			'matthewjho',
			'mattkeys',
			'matveb',
			'maurodf',
			'maxinacube',
			'maysi',
			'mburridge',
			'mciampini',
			'mcsf',
			'meaganhanes',
			'melchoyce',
			'mer00x',
			'merel1988',
			'meta4',
			'mhimon',
			'mhkuu',
			'mhshujon',
			'mi5t4n',
			'michael-arestad',
			'michalooki',
			'michelleames',
			'michelleblanchette',
			'michi91',
			'mikachan',
			'mikejolley',
			'mikeschinkel',
			'mikestraw',
			'mikinc860',
			'mimitips',
			'mintindeed',
			'mitchellaustin',
			'mitogh',
			'mklute101',
			'mmaattiiaass',
			'mmcalister',
			'mokagio',
			'mrdollu',
			'mrinal013',
			'mrwweb',
			'mshowes',
			'mte90',
			'mujuonly',
			'mukesh27',
			'mwtsn',
			'nacin',
			'nandhuraj',
			'nazgul',
			'nazsabuz',
			'ndiego',
			'neilorangepeel',
			'nekojonez',
			'nendeb55',
			'nerrad',
			'netweb',
			'newyorkerlaura',
			'nexflaszlo',
			'ngreennc',
			'nicolefurlan',
			'nicomollet',
			'nidhidhandhukiya',
			'nielslange',
			'nihar007',
			'nilovelez',
			'niravsherasiya7707',
			'nithi22',
			'nithins53',
			'noahtallen',
			'noisysocks',
			'ntsekouras',
			'nudge',
			'oandregal',
			'obenland',
			'ocean90',
			'ockham',
			'oglekler',
			'ohia',
			'ohryan',
			'okat',
			'olein',
			'olliejones',
			'omarabid',
			'oncecoupled',
			'onemaggie',
			'otto42',
			'p51labs',
			'paaljoachim',
			'pagelab',
			'pannelars',
			'partyfrikadelle',
			'paulkevan',
			'pauthake015',
			'pavelevap',
			'pbiron',
			'pbking',
			'pedromendonca',
			'pentatonicfunk',
			'pento',
			'pereirinha',
			'perrelet',
			'peterwilsoncc',
			'petitphp',
			'petrosparaskevopoulos',
			'phillsav',
			'piyushdeshmukh',
			'planningwrite',
			'plugindevs',
			'poena',
			'pooja1210',
			'poojabhimani',
			'poran766',
			'pranavjoshi',
			'prashantbhivsane',
			'presskopp',
			'priethor',
			'pypwalters',
			'queerdevperson',
			'rabmalin',
			'rahe',
			'rahmohn',
			'rajinsharwar',
			'ramonopoly',
			'ravanh',
			'rawrly',
			'rcorrales',
			'rebasaurus',
			'rebekowitz',
			'renathoc',
			'renehermi',
			'renyot',
			'revgeorge',
			'rianrietveld',
			'richtabor',
			'rilwis',
			'rlmc',
			'rmartinezduque',
			'rmccue',
			'robinwpdeveloper',
			'robpetrin',
			'rudlinkon',
			'ryanduff',
			'ryelle',
			'sabernhardt',
			'sajjad67',
			'sakibmd',
			'salcode',
			'samba45',
			'sanchothefat',
			'santosguillamot',
			'sarahwilliams889',
			'sarathar',
			'satishprajapati',
			'saulirajala',
			'saxonfletcher',
			'sc0ttkclark',
			'schlessera',
			'scribu',
			'scruffian',
			'seedsca',
			'sereedmedia',
			'sergeybiryukov',
			'sergiomdgomes',
			'shailu25',
			'shawfactor',
			'shiloey',
			'shimotomoki',
			'shireling',
			'shivashankerbhatta',
			'shooper',
			'shresthaaman',
			'shubhamsedani',
			'simison',
			'siobhan',
			'siobhyb',
			'skorasaurus',
			'smit08',
			'smrubenstein',
			'snicco',
			'soean',
			'sofiashendi',
			'soulseekah',
			'spacedmonkey',
			'spenserhale',
			'starbuck',
			'stephenerdelyi',
			'stevejonesdev',
			'subodhsun',
			'subrataemfluence',
			'sujichandran14',
			'sumisubedi',
			'sumitbagthariya16',
			'sumitsingh',
			'sunitarai',
			'suprsam',
			'swissspidy',
			'syamraj24',
			'synchro',
			'szepeviktor',
			'tabrisrp',
			'tacoverdo',
			'tahmidulkarim',
			'tahmina1du',
			'takayukister',
			'talldanwp',
			'tanvirul',
			'tejadev',
			'tejwanihemant',
			'tellthemachines',
			'thekt12',
			'thelovekesh',
			'thelovelist',
			'thewebprincess',
			'thinkluke',
			'thomashorta',
			'thomasplevy',
			'tibbsa',
			'timdix',
			'timothyblynjacobs',
			'tjnowell',
			'tmatsuur',
			'tnolte',
			'tobiasbg',
			'tobifjellner',
			'tomjcafferkey',
			'tomluckies',
			'tomsommer',
			'tomybyte',
			'toro_unit',
			'toscho',
			'travel_girl',
			'trinisha',
			'trishasalas',
			'tristanleboss',
			'tv-productions',
			'tykoted',
			'tyxla',
			'ubernaut',
			'ugyensupport',
			'upadalavipul',
			'utsav72640',
			'valentindu62',
			'valmedia2023',
			'varjodesigns',
			'vcanales',
			'vipuljnext',
			'viralsampat',
			'virtality-marketing-solutions',
			'vivekawsm',
			'vortfu',
			'vrajadas',
			'walbo',
			'webashrafians',
			'webcommsat',
			'webdev8800',
			'webmandesign',
			'webtechpooja',
			'welcher',
			'westonruter',
			'whsajid',
			'whyisjake',
			'wildworks',
			'winterstreet',
			'wonderboymusic',
			'wparslan',
			'wpgurudev',
			'wraithkenny',
			'wvega',
			'wyrfel',
			'xknown',
			'yari2u',
			'yosephtamang',
			'youknowriad',
			'zaguiini',
			'zieladam',
			'zodiac1978',
			'zunaid321',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/en/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/tzuryby/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'Preact', 'https://preactjs.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://reactjs.org/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tinymce.com/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/github/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}

