<?php

class WP_71_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'annezazu'            => [ 'Anne McCarthy', 'Release Lead' ],
					'benjamin_zekavica'   => [ 'Benjamin Zekavica', 'Release Coordination' ],
					'krupajnanda'         => [ 'Krupa Nanda', 'Release Coordination' ],
					'wildworks'           => [ 'Aki Hamano', 'Tech Lead' ],
					'joedolson'           => [ 'Joe Dolson', 'Tech Lead' ],
					'adrianduffell'       => [ 'Adrian Duffell', 'Triage Lead' ],
					'sajjad67'            => [ 'Sajjad Hossain Sagor', 'Triage Lead' ],
					'SergeyBiryukov'      => [ 'Sergey Biryukov', 'Triage Lead' ],
					'huzaifaalmesbah'     => [ 'Huzaifa Al Mesbah', 'Test Lead' ],
					'nikunj8866'          => [ 'Nikunj Hatkar', 'Test Lead' ],
					'Mamaduka'            => 'George Mamadashvili',
					'mciampini'           => 'Marco Ciampini',
					'0mirka00'            => 'Lena Morita',
					'ramonopoly'          => 'Ramon James',
					'andrewserong'        => 'Andrew Serong',
					'westonruter'         => 'Weston Ruter',
					'ntsekouras'          => 'Nik Tsekouras',
					'aduth'               => 'Andrew Duthie',
					'tyxla'               => 'Marin Atanasov',
					'adamsilverstein'     => 'Adam Silverstein',
					'desrosj'             => 'Jonathan Desrosiers',
					'talldanwp'           => 'Daniel Richards',
					'jsnajdr'             => 'Jarda Snajdr',
					'jameskoster'         => 'James Koster',
					'ellatrix'            => 'Ella van Durpe',
					'isabel_brison'       => 'Isabel Brison',
					'manzoorwani.jk'      => 'Manzoor Wani',
					'Joen'                => 'Joen Asmussen',
					'jorgefilipecosta'    => 'Jorge Costa',
					'gziolo'              => 'Greg Ziółkowski',
					'mukesh27'            => 'Mukesh Panchal',
					'oandregal'           => 'André Maneiro',
					'scruffian'           => 'Ben Dwyer',
					'kleisauke'           => 'Kleis Auke Wolthuizen',
					'lucasmdo'            => 'Lucas Mendes',
					'markoserb'           => 'Marko Ivanovic',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'youknowriad'         => 'Riad Benguella',
					'dmsnell'             => 'Dennis Snell',
					'jonsurrell'          => 'Jon Surrell',
					'jorbin'              => 'Aaron Jorbin',
					'audrasjb'            => 'Jean-Baptiste Audras',
					'peterwilsoncc'       => 'Peter Wilson',
					'afercia'             => 'Andrea Fercia',
					'alecgeatches'        => 'Alec Geatches',
					'sabernhardt'         => 'Stephen Bernhardt',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'simison'             => 'Mikael Korpela',
					'mcsf'                => 'Miguel Fonseca',
					'czarate'             => 'Chris Zarate',
					'johnbillion'         => 'John Blackbourn',
					'shailu25'            => 'Shail Mehta',
					'amykamala'           => 'Amy Kamala',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'369work',
			'4thhubbard',
			'aagam94',
			'aakashverma1',
			'aaroncampbell',
			'aaronrobertshaw',
			'abcd95',
			'abdalsalaam',
			'abdullahramzan',
			'abduremon',
			'abhishekfdd',
			'acketon',
			'adamsilverstein',
			'adamwood',
			'adithyanaik',
			'adrianduffell',
			'adrianmoldovanwp',
			'adrmf25',
			'adrock42',
			'aduth',
			'afercia',
			'afragen',
			'agulbra',
			'ahortin',
			'ahuseyn',
			'aialvi',
			'aion11',
			'akirk',
			'akshat2802',
			'alanjacobmathew',
			'alecgeatches',
			'alexcu21',
			'alexodiy',
			'alexstine',
			'alh0319',
			'alhrath',
			'aljullu',
			'alshakero',
			'amitjoel85',
			'amitraj2203',
			'amjadr360',
			'amykamala',
			'anastis',
			'andizer',
			'andraganescu',
			'andreasdl',
			'andrewserong',
			'andrewssanya',
			'angelulz',
			'ankit-k-gupta',
			'ankitkumarshah',
			'ankitmaru',
			'ankitpatel1578',
			'anlino',
			'annebovelett',
			'annezazu',
			'anukasha',
			'anupkankale',
			'anveshika',
			'apermo',
			'aperto',
			'arcangelini',
			'areziaal',
			'arisch24',
			'aristath',
			'arkaprabhachowdhury',
			'armandmatthey',
			'arshidkv12',
			'arthur791004',
			'artpi',
			'aslushnikov',
			'aswasif007',
			'atomiks',
			'audrasjb',
			'aurooba',
			'avcascade',
			'awetz583',
			'ayazahmed12',
			'ayushhoff',
			'azaozz',
			'azharderaiya',
			'azragh',
			'bacoords',
			'baikaresandeep007-1',
			'barry',
			'bartkalisz',
			'batmoo',
			'bayejid00',
			'bejignesh',
			'benjamin_zekavica',
			'benjgrolleau',
			'benniledl',
			'benoitchantre',
			'berislavgrgicak',
			'bernhard-reiter',
			'beryldlg',
			'bgardner',
			'bhubbard',
			'bigdigital',
			'birgire',
			'bitmachina',
			'bjorsch',
			'bluefuton',
			'bobbingwide',
			'bor0',
			'bosskhj',
			'bpayton',
			'bph',
			'bradley2083',
			'bradshawtm',
			'brajdas0022',
			'brbrr',
			'brianhenryie',
			'brianhogg',
			'bridgetwillard',
			'brnhrst',
			'burhandodhy',
			'burnuser',
			'butterflymedia',
			'cadeyrn',
			'cagrimmett',
			'catthetech',
			'cbirdsong',
			'cbravobernal',
			'cbusquets1989',
			'ccprog',
			'celloexpressions',
			'cgastrell',
			'chaion07',
			'cheffheid',
			'chillifish',
			'chiscoleiton',
			'chouby',
			'chriscct7',
			'chrisdavidmiles',
			'chrisgresh',
			'clementpolito',
			'clorith',
			'codeamp',
			'codesmith32',
			'codexdemon',
			'coffee2code',
			'cogdesign',
			'colind',
			'collinr3',
			'colorful-tones',
			'concept83',
			'coreyw',
			'courane01',
			'cpapazoglou',
			'crmv',
			'csabarakasz',
			'csmcneill',
			'cweiske',
			'cybr',
			'czarate',
			'danielbachhuber',
			'daniguardiola',
			'danluu',
			'dannyreaktiv',
			'darerodz',
			'darshitrajyaguru97',
			'davidabowman',
			'davidbaumwald',
			'davidbinda',
			'davidszabo',
			'davilera',
			'dcavins',
			'dd32',
			'deepakprajapati',
			'deepakrohilla',
			'dennisheiden',
			'deoladev',
			'dervishov',
			'deryck',
			'designsimply',
			'desrosj',
			'devanshijoshi',
			'devasheeshkaul',
			'devrito',
			'devsabbirhossain',
			'dharm1025',
			'dhavalkapadane',
			'dhrumilk',
			'dhrupo',
			'dhruvang21',
			'dhruvik18',
			'diegogarciarodrigues',
			'dingo_d',
			'dinhtungdu',
			'dkotter',
			'dlind1',
			'dmsnell',
			'drewapicture',
			'drivingralle',
			'drw158',
			'drwpcom',
			'dsas',
			'dshanske',
			'dufresnesteven',
			'eatse',
			'ecairol',
			'eclev91',
			'edent',
			'efc',
			'eherman24',
			'ehtis',
			'eishanoor',
			'ekamran',
			'ekaterina92',
			'ekla',
			'elazzabi',
			'elblakeo31',
			'elfu98',
			'elizaan36',
			'ellatrix',
			'elmastudio',
			'emptyopssphere',
			'enej',
			'epeicher',
			'estelaris',
			'eurello',
			'extrachill',
			'fabiankaegy',
			'faisalahammad',
			'fakhriaz',
			'fandevelop',
			'fcoveram',
			'fditrapani',
			'felipevelzani',
			'feperrella',
			'fernandot',
			'fierevere',
			'firdaus666',
			'firewatch',
			'flixos90',
			'freewebmentor',
			'fushar',
			'g4ll4is',
			'gaelbonithon',
			'gaisma22',
			'gajendrasingh',
			'galaxor',
			'galois44',
			'garethelwell',
			'garrett-eclipse',
			'garyj',
			'gasatrya',
			'gaurangsondagar',
			'gautam23',
			'gautammkgarg',
			'gazipress',
			'generosus',
			'germanfrelo',
			'get_dave',
			'gierand',
			'gigitux',
			'gilmoursa',
			'glendaviesnz',
			'greatislander',
			'greenshady',
			'gregbenz',
			'griffithchen',
			'gschoppe',
			'gulamdastgir04',
			'gusgomezpg',
			'gustavohappyeng',
			'gwwar',
			'gziolo',
			'habiburdev',
			'hage',
			'hanneslsm',
			'hareesh-pillai',
			'harishtewari',
			'harshbhonsle08',
			'hasnainashfaq',
			'hazdiego',
			'hbhalodia',
			'hellofromtonya',
			'hilayt24',
			'hmbashar',
			'hmrisad',
			'hrkhal',
			'hrohh',
			'hubersen',
			'hugod',
			'humanify',
			'huzaifaalmesbah',
			'iamadisingh',
			'iamarinoh',
			'iamchitti',
			'iamchughmayank',
			'iamjolly',
			'iamraju',
			'iamtakashi',
			'ianmjones',
			'ibachal',
			'ibrahimriaz',
			'iflairwebtechnologies',
			'im3dabasia1',
			'inc2734',
			'ingeniumed',
			'iqbal1hossain',
			'ironprogrammer',
			'irozum',
			'isabel_brison',
			'iseardmedia',
			'ishihara-takashi',
			'ishikaatxecurify',
			'ishitaj34',
			'ismail0071',
			'isotropic',
			'itsdavidmorgan',
			'itsjonq',
			'itzmekhokan',
			'jadavsanjay',
			'jakeparis',
			'jakub300',
			'jamesbregenzer',
			'jamesgiroux',
			'jameskoster',
			'jamieburchell',
			'janpaulkleijn',
			'jarekmorawski',
			'jarodortegaaraya',
			'jason_the_adams',
			'jasonkenison',
			'jasonkytros',
			'javiarce',
			'javiercasares',
			'javorszky',
			'jdahir0789',
			'jdwire',
			'jdy68',
			'jeffgreendesign',
			'jeffpaul',
			'jeflopodev',
			'jeherve',
			'jeremyfelt',
			'jeryj',
			'jhmonroe',
			'jigangz',
			'jigar-bhanushali',
			'jigar9998',
			'jigarkahar',
			'jillq',
			'jimgrey',
			'jivedig',
			'jjlmoya',
			'jmichaelward',
			'jnbg',
			'jns141191',
			'jobthomas',
			'joedolson',
			'joefusco',
			'joehoyle',
			'joemaller',
			'joemcgill',
			'joen',
			'johnbillion',
			'johnjamesjacoby',
			'johnstonphilip',
			'johnwatkins0',
			'jonmcpartland',
			'jonsurrell',
			'joostdevalk',
			'jorbin',
			'jordesign',
			'jorgefilipecosta',
			'josephscott',
			'josevarghese',
			'joshualipstone',
			'joshuawold',
			'josvelasco',
			'jrf',
			'jsmansart',
			'jsnajdr',
			'juanfra',
			'juanmaguitar',
			'juliemoynat',
			'justlevine',
			'kadamwhite',
			'kannanravi',
			'kapilpaul',
			'karmatosed',
			'karthickmurugan',
			'karthikeya01',
			'katag9k',
			'kausaralm',
			'kellychoffman',
			'keoshi',
			'kevinfodness',
			'kevinrobles',
			'khokansardar',
			'khushalsains',
			'khushdoms',
			'khushipatel15',
			'kimannwall',
			'kirasong',
			'kjellr',
			'kjroelke',
			'kleisauke',
			'knutsp',
			'kokkieh',
			'kosvrouvas',
			'kraftbj',
			'krokodok',
			'krupajnanda',
			'krysek76',
			'kuber8821',
			'kubiq',
			'kurudrive',
			'kush123',
			'lakshyajeet',
			'lancewillett',
			'landwire',
			'leemon',
			'levinmedia',
			'liaison',
			'linewebdigital',
			'lisacee',
			'lmartins',
			'lonesahilnazir',
			'looswebstudio',
			'louiswol94',
			'lschuyler',
			'lucasbustamante',
			'lucasmdo',
			'ludwigyou',
			'luisdavid01',
			'luisherranz',
			'luismulinari',
			'lukecarbis',
			'lumiblog',
			'luminuu',
			'lunule',
			'm-e-h',
			'm13v',
			'mabdelbari',
			'madhavishah01',
			'madhazelnut',
			'madhudollu',
			'madtownlems',
			'mahdiali',
			'maheshpatel',
			'makanikaran',
			'maksymmamontov',
			'malayladu',
			'mamaduka',
			'manfcarlo',
			'manhar',
			'manishxdp',
			'manzoorwanijk',
			'mapk',
			'markhowellsmead',
			'markoserb',
			'masteradhoc',
			'mathijsvdbeek',
			'matt',
			'mattbolt',
			'mattgaldino',
			'mattshaw',
			'matveb',
			'maximebj',
			'maxschmeling',
			'mayanktripathi32',
			'mazharulrobeen',
			'mbigul',
			'mboynes',
			'mciampini',
			'mcliwanow',
			'mcsf',
			'mdawaffe',
			'mdridipu',
			'mdviralsampat',
			'mdxfr',
			'meet_hasmukh',
			'mehrazmorshed',
			'mehtadev',
			'mehul0810',
			'mgol',
			'micahele',
			'michaldudak',
			'migueluy',
			'mikachan',
			'mikejolley',
			'mikeselander',
			'mikeybinns',
			'mikinc860',
			'milana_cap',
			'milindmore22',
			'mimitips',
			'mindctrl',
			'mirmpro',
			'miyarakira',
			'mkaz',
			'mkrndmane',
			'mmaattiiaass',
			'mmtr86',
			'mohamedahamed',
			'mohitbsf',
			'mohkatz',
			'mokshasharmila13',
			'monzuralam',
			'mosescursor',
			'motylanogha',
			'mrfoxtalbot',
			'mrwweb',
			'mukesh27',
			'mukeshparihar',
			'multidots1896',
			'muryam',
			'mustafabharmal',
			'mutuajose',
			'myththrazz',
			'mywp459',
			'n8finch',
			'nadabulija',
			'namankhare',
			'nanisamireddy',
			'nareshbheda',
			'nathanrbsf',
			'nazmul111',
			'nazmulasif',
			'ndiego',
			'nebojsajurcic',
			'nekojonez',
			'nendeb55',
			'neo2k23',
			'nerrad',
			'nickfmc',
			'nickpagz',
			'nickthegeek',
			'nicolasalarconrapela',
			'nicsevic',
			'nikunj8866',
			'nilambar',
			'nimeshatxecurify',
			'niravsherasiya7707',
			'noahtallen',
			'noellesteegs',
			'noisysocks',
			'noruzzaman',
			'notnownikki',
			'ntsekouras',
			'oandregal',
			'obenland',
			'obliviousharmony',
			'ocean90',
			'odkdn1',
			'oglekler',
			'oldenwilde',
			'olliejones',
			'onemaggie',
			'onetrev',
			'opurockey',
			'ov3rfly',
			'ozgursar',
			'paaljoachim',
			'pablohoneyhoney',
			'pamprn',
			'pankajsakaria',
			'parinpanjari',
			'parthvataliya',
			'patrickwclanden',
			'paulgibbs',
			'paulkevan',
			'paulopmt1',
			'pavanpatil1',
			'pavelevap',
			'pavloborysenko',
			'pbearne',
			'pbiron',
			'pedrofigueroa1989',
			'pento',
			'peterwilsoncc',
			'petitphp',
			'philhoyt',
			'phpbits',
			'physalis',
			'piyushpatel123',
			'pmbaldha',
			'poena',
			'poligilad',
			'pontocinza',
			'pooja-n',
			'porg',
			'postphotos',
			'power2009',
			'prachigarg19',
			'praful2111',
			'prajapatvishnu',
			'pranjal4804',
			'pranjalpratapsingh',
			'prasadkarmalkar',
			'prathameshbhagat1511',
			'pratik-jain',
			'pratiknawkar94',
			'pravin1996',
			'presskopp',
			'presstoke',
			'priethor',
			'priyankagusani',
			'projektisle',
			'properlypurple',
			'psykro',
			'r1k0',
			'r33d3m33r',
			'rachelmcr',
			'rafaeldella',
			'rafaelfunchal',
			'raftaar1191',
			'rahultank',
			'rajanarahul93',
			'rajdiptank111',
			'rajeshcp',
			'rajinsharwar',
			'rakeshfalke',
			'ramiy',
			'ramonopoly',
			'ravanh',
			'ravichudasama01',
			'ravigadhiyawp',
			'ravikhadka',
			'rcorrales',
			'realloc',
			'rejaulalomkhan',
			'renathoc',
			'reneyap',
			'retrofox',
			'rezwanshiblu1952',
			'rianrietveld',
			'richtabor',
			'rilwis',
			'rinkalpagdar',
			'rishabhwp',
			'rishit30g',
			'ritheshsatheesh',
			'rlucian',
			'robert681',
			'robertghetau',
			'rodrigosprimo',
			'rohitmathur7',
			'rolle',
			'rollybueno',
			'ronakganatra9',
			'roshniahuja14',
			'ruba1956',
			'rushikeshmore',
			'rutviksavsani',
			'ryanmoyer',
			'ryelle',
			's56bouya',
			'saadtajik',
			'sabbir1991',
			'sabernhardt',
			'sachinrajcp123',
			'sagardeshmukh',
			'sagarjadhav',
			'sainathpoojary',
			'sajib1223',
			'sajjad67',
			'sakshamsharma5',
			'salmanshafiq8630',
			'samvaidya',
			'sanayasir',
			'sandipmaurya2611',
			'sandipsinh007',
			'sanketparmar',
			'santosguillamot',
			'saratheonline',
			'saroshaga',
			'sarthaknagoshe2002',
			'saulirajala',
			'sauliusv',
			'saxonafletcher',
			'sc0ttkclark',
			'schlessera',
			'scruffian',
			'sdnunca',
			'sergeybiryukov',
			'sergiomdgomes',
			'sfougnier',
			'shailesh7714',
			'shailu25',
			'shamimmoeen',
			'shanemuir',
			'shatrumyatra',
			'shaunandrews',
			'shekh0109',
			'shekharnwagh',
			'sheldorofazeroth',
			'shimotomoki',
			'shireling',
			'shreya0shrivastava',
			'shreyasikhar26',
			'sidhanttomar',
			'siliconforks',
			'simison',
			'simondud',
			'simonhammes',
			'simonwammerfors',
			'sippis',
			'sirlouen',
			'skorasaurus',
			'slackticus',
			'slywy',
			'smerriman',
			'smithjw1',
			'smrubenstein',
			'snehal5774',
			'snehapatil02',
			'snilesh',
			'soean',
			'softglaze',
			'sohampate1',
			'sonaliprajapati',
			'sourav08',
			'soyebsalar01',
			'spacedmonkey',
			'spadilha',
			'speedwheel',
			'sruthi89',
			'steelwagstaff',
			'stefanvelthuys',
			'stevejonesdev',
			'stevenlinx',
			'strarsis',
			'styankov',
			'sukhendu2002',
			'sumitbagthariya16',
			'sumitsingh',
			'superdav42',
			'supernovia',
			'suryakantupadhyay',
			'swanandm',
			'swapnil1010',
			'swissspidy',
			'synchro',
			'szandman',
			'szepeviktor',
			'tacoverdo',
			'tainacan',
			'taisa1984',
			'takshil',
			'talldanwp',
			'tbclark3',
			'terragirl',
			'tfserwin',
			'thehenridev',
			'thelmachido',
			'thinkaquamarine',
			'thisismyurl',
			'threadi',
			'thriveteam',
			'tibibuzdugan',
			'tikifez',
			'timnicholson',
			'timothyblynjacobs',
			'timse201',
			'tobiasbg',
			'tobifjellner',
			'tommusrhodus',
			'toro_unit',
			'torontodigits',
			'tpaw',
			'tratnikm',
			'tresorama',
			'trickster301',
			'trivedikavit',
			'tusharaddweb',
			'tusharbharti',
			'tyxla',
			'tz-media',
			'ugyensupport',
			'umeshnevase',
			'up1512001',
			'upadalavipul',
			'utsavladani',
			'valani9099',
			'vcanales',
			'vdwijngaert',
			'vedantere',
			'vedantgandhi28',
			'vgnavada',
			'vincentbdrt',
			'vineet2003',
			'viralsampat',
			'vishitshah',
			'vishnuprajapat',
			'vivekawsm',
			'vortfu',
			'vrajadas',
			'vrishabhsk',
			'webmandesign',
			'webverts',
			'welcher',
			'westonruter',
			'wetah',
			'whaze',
			'wildworks',
			'williampatton',
			'wongjn',
			'wpdevsxyz',
			'wpeoin',
			'wpexplorer',
			'wpsoul',
			'wwahammy',
			'xate',
			'xavilc',
			'xerpa43',
			'xibe',
			'xknown',
			'xristos3490',
			'yankiara',
			'yashjawale',
			'yogeshbhutkar',
			'youknowriad',
			'ytfeldrawkcab',
			'yuliyan',
			'yusufmudagal',
			'zebulan',
			'zieladam',
			'znuff',
			'zoonini',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/mathusiast/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'Mediabunny', 'https://github.com/Vanilagy/mediabunny' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://react.dev/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tiny.cloud/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'wasm-vips', 'https://github.com/kleisauke/wasm-vips' ],
			[ 'whatwg-fetch', 'https://github.com/JakeChampion/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}
