<?php

class WP_70_Credits extends WP_Credits {

	public function groups() {
		$groups = [
			'core-developers'         => [
				'name'    => 'Noteworthy Contributors',
				'type'    => 'titles',
				'shuffle' => false,
				'data'    => [
					'matveb'              => [ 'Matias Ventura', 'Release Lead' ],
					'chaion07'            => [ 'Ahmed Kabir Chaion', 'Release Coordination' ],
					'amykamala'           => [ 'Amy Kamala', 'Release Coordination' ],
					'4thhubbard'          => [ 'Mary Hubbard', 'Release Coordination' ],
					'ellatrix'            => [ 'Ella van Durpe', 'Tech Lead' ],
					'mukesh27'            => [ 'Mukesh Panchal', 'Tech Lead' ],
					'SergeyBiryukov'      => [ 'Sergey Biryukov', 'Tech Lead' ],
					'audrasjb'            => [ 'Jean-Baptiste Audras', 'Triage Lead' ],
					'juanmaguitar'        => [ 'JuanMa Garrido', 'Triage Lead' ],
					'Ankit K Gupta'       => [ 'Ankit K. Gupta', 'Test Lead' ],
					'marybaum'            => [ 'Mary Baum', 'Test Lead' ],
					'wildworks'           => 'Aki Hamano',
					'Mamaduka'            => 'George Mamadashvili',
					'westonruter'         => 'Weston Ruter',
					'youknowriad'         => 'Riad Benguella',
					'ramonopoly'          => 'Ramon James',
					'jorgefilipecosta'    => 'Jorge Costa',
					'aduth'               => 'Andrew Duthie',
					'ntsekouras'          => 'Nik Tsekouras',
					'0mirka00'            => 'Lena Morita',
					'andrewserong'        => 'Andrew Serong',
					'talldanwp'           => 'Daniel Richards',
					'joedolson'           => 'Joe Dolson',
					'oandregal'           => 'André Maneiro',
					'desrosj'             => 'Jonathan Desrosiers',
					'Joen'                => 'Joen Asmussen',
					'isabel_brison'       => 'Isabel Brison',
					'peterwilsoncc'       => 'Peter Wilson',
					'adamsilverstein'     => 'Adam Silverstein',
					'griffbrad'           => 'Lynn Bradley Griffith',
					'annezazu'            => 'Anne McCarthy',
					'gziolo'              => 'Greg Ziółkowski',
					'fcoveram'            => 'Francisco Vera',
					'markoserb'           => 'Marko Ivanovic',
					'sfougnier'           => 'Saul Fougnier',
					'ryelle'              => 'Kelly Choyce-Dwan',
				],
			],
			'contributing-developers' => [
				'name'    => false,
				'type'    => 'titles',
				'shuffle' => true,
				'data'    => [
					'jameskoster'         => 'James Koster',
					'jsnajdr'             => 'Jarda Snajdr',
					'dmsnell'             => 'Dennis Snell',
					'mikachan'            => 'Sarah Norris',
					'mciampini'           => 'Marco Ciampini',
					'huzaifaalmesbah'     => 'Huzaifa Al Mesbah',
					'mcsf'                => 'Miguel Fonseca',
					'SirLouen'            => 'Manuel Camargo',
					'jonsurrell'          => 'Jon Surrell',
					'scruffian'           => 'Ben Dwyer',
					'sabernhardt'         => 'Stephen Bernhardt',
					'get_dave'            => 'David Smith',
					'czarate'             => 'Chris Zarate',
					'tyxla'               => 'Marin Atanasov',
					'shailu25'            => 'Shail Mehta',
					'johnbillion'         => 'John Blackbourn',
					'aaronrobertshaw'     => 'Aaron Robertshaw',
					'Bernhard Reiter'     => 'Bernie Reiter',
					'noruzzaman'          => 'Noruzzaman Rubel',
					'jorbin'              => 'Aaron Jorbin',
					'fabiankaegy'         => 'Fabian Kägy',
					'manzoorwani.jk'      => 'Manzoor Wani',
					'awetz583'            => 'Andrea Roenning',
					'maxschmeling'        => 'Max Schmeling',
					'JoeFusco'            => 'Joe Fusco',
					'jmdodd'              => 'Jennifer M. Dodd',
					'kjoyner'             => 'Kedar Joyner',
				],
			],
		];

		return $groups;
	}

	public function props() {
		return [
			'0mirka00',
			'1000camels',
			'369work',
			'4thhubbard',
			'aakashverma1',
			'aaronrobertshaw',
			'abcd95',
			'abdullah17',
			'abduremon',
			'abhishekfdd',
			'acmoifr',
			'adamsilverstein',
			'adithyanaik',
			'adnanhyder',
			'adnanlimdi',
			'adrianpiedra',
			'adrmf25',
			'adrock42',
			'aduth',
			'afercia',
			'afwebdev',
			'agnieszkaszuba',
			'ahortin',
			'aidvu',
			'aileenf',
			'aion11',
			'ajitbohra',
			'ajlende',
			'akirk',
			'akshat2802',
			'albigdd',
			'alecgeatches',
			'alecrust',
			'alerzhus',
			'alexodiy',
			'alexsanford1',
			'alexstine',
			'alh0319',
			'aliaghdam',
			'aljullu',
			'allanespinoza',
			'altf4falt',
			'alvitidiana',
			'amanandhishoe',
			'amesplant',
			'amibe',
			'amin7',
			'amitraj2203',
			'amykamala',
			'anastis',
			'andraganescu',
			'andrewryno',
			'andrewserong',
			'andrewssanya',
			'ankit-k-gupta',
			'ankitkumarshah',
			'ankitmaru',
			'anlino',
			'annebovelett',
			'annezazu',
			'ant1busted',
			'antoniosejas',
			'antonrinas',
			'antonvlasenko',
			'antpb',
			'anukasha',
			'anupkankale',
			'anveshika',
			'apedog',
			'apermo',
			'aquarius',
			'arcwp',
			'areziaal',
			'aristath',
			'arkaprabhachowdhury',
			'armandmatthey',
			'artemiosans',
			'arthur791004',
			'artpi',
			'artz91',
			'arunsathiya',
			'arunu1996',
			'asadowski10',
			'ashirhabib',
			'assassinateur',
			'atharvasagane',
			'audrasjb',
			'audunmb',
			'awardpress',
			'awetz583',
			'azaozz',
			'azharderaiya',
			'azora',
			'azragh',
			'bacoords',
			'badasswp',
			'bbpaule',
			'beaubhavik',
			'benjamin_zekavica',
			'benjamingosset',
			'benniledl',
			'benoitchantre',
			'benpinales',
			'berislavgrgicak',
			'bernattorras',
			'bernhard-reiter',
			'beryldlg',
			'bgardner',
			'bhubbard',
			'birgire',
			'bitmachina',
			'bjorsch',
			'blackstar1991',
			'bluefuton',
			'bobbingwide',
			'bor0',
			'bpayton',
			'bph',
			'bradley2083',
			'bradshawtm',
			'brajdas0022',
			'brbrr',
			'brianhogg',
			'bridgetwillard',
			'brumack',
			'burtrw',
			'butterflymedia',
			'buutqn',
			'cagrimmett',
			'calin',
			'cbirdsong',
			'cbravobernal',
			'celloexpressions',
			'cgastrell',
			'chaion07',
			'chauhanraj754',
			'chellycat',
			'chexee',
			'chihsuan',
			'chiscoleiton',
			'chrisdotdotdot',
			'chrismcelroyseo',
			'chrispecoraro',
			'ciorici',
			'claycarpenter',
			'clayray',
			'clementpolito',
			'clorith',
			'codex-m',
			'coffee2code',
			'cogdesign',
			'colorful-tones',
			'copons',
			'coreyw',
			'costdev',
			'courane01',
			'cr0ybot',
			'cris31',
			'crstauf',
			'cybr',
			'czarate',
			'czarflix',
			'daledupreez',
			'danielbachhuber',
			'danieltj',
			'danluu',
			'dannyreaktiv',
			'dannythedog',
			'darerodz',
			'darshitrajyaguru97',
			'davidabowman',
			'davidbaumwald',
			'davidborrink',
			'dd32',
			'debarghyabanerjee',
			'deborah86',
			'deepaklalwani',
			'deepakprajapati',
			'deepakrohilla',
			'deoladev',
			'dervishov',
			'desrosj',
			'devangvachheta137',
			'dhansondesigns',
			'dhavalkapadane',
			'dhiraj0901',
			'dhrumilk',
			'dhruval04',
			'dhruvang21',
			'dhruvik18',
			'dianeco',
			'digamberpradhan',
			'digitalblanket',
			'dilip2615',
			'dilipbheda',
			'dimitro',
			'dingo_d',
			'dinhtungdu',
			'divyeshpatel01',
			'djidjou',
			'djsuperfive',
			'dkotter',
			'dlh',
			'dmallory42',
			'dmsnell',
			'donmhico',
			'dpknauss',
			'drebbitsweb',
			'drewapicture',
			'drivingralle',
			'drw158',
			'dryanpress',
			'drysand',
			'dsas',
			'dufresnesteven',
			'eatingrules',
			'ecairol',
			'eclev91',
			'eddystile',
			'edent',
			'egill',
			'ehti',
			'ekla',
			'elazzabi',
			'elemrr',
			'ellatrix',
			'elrae',
			'emptyopssphere',
			'enravo',
			'ericmacknight',
			'estelaris',
			'ethitter',
			'euthelup',
			'evansolomon',
			'fabiankaegy',
			'faguni22',
			'faisal03',
			'faisalahammad',
			'fakhriaz',
			'fandevelop',
			'farhad0',
			'fcartin22',
			'fcoveram',
			'feli22',
			'felipevelzani',
			'fellyph',
			'ferdoused',
			'fernandot',
			'fierevere',
			'firoz2456',
			'fitehal',
			'flixos90',
			'florianbrinkmann',
			'franckmee',
			'franz00',
			'freibergergarcia',
			'from',
			'frozzare',
			'fushar',
			'gabertronic',
			'gaisma22',
			'gajendrasingh',
			'garrett-eclipse',
			'garyj',
			'gaurangsondagar',
			'gauri87',
			'gautam23',
			'gautammkgarg',
			'geekofshire',
			'geminorum',
			'generosus',
			'george9',
			'get_dave',
			'getsyash',
			'gierand',
			'gigitux',
			'giuliorubelli',
			'glendaviesnz',
			'gmjuhasz',
			'gohelkunjan',
			'govardhane',
			'grahamarmfield',
			'grantmkin',
			'grapplerulrich',
			'greenshady',
			'griffbrad',
			'guido07111975',
			'gulamdastgir04',
			'gustavohappyeng',
			'gwwar',
			'gyurmey',
			'gziolo',
			'hack_nug',
			'hage',
			'hanneslsm',
			'hardikhuptechdev',
			'hardipparmar',
			'harshalkadu',
			'harshbhonsle08',
			'hbhalodia',
			'helen',
			'hellofromtonya',
			'hiabhaykulkarni',
			'himshekhar07',
			'hiranimahaveer',
			'hiroshisato',
			'hiteshtalpada',
			'hmbashar',
			'hmrisad',
			'hozefasmile',
			'hrkhal',
			'hubersen',
			'hugod',
			'huubl',
			'huzaifaalmesbah',
			'iamadisingh',
			'iamasadpolash',
			'iamshubhamsp',
			'iamtakashi',
			'iandunn',
			'ibrahimriaz',
			'ierwira',
			'iflairwebtechnologies',
			'ignatiusjeroe',
			'illuminea',
			'im3dabasia1',
			'immeet94',
			'inc2734',
			'indirabiswas27',
			'ingeniumed',
			'ipstenu',
			'iqbal1hossain',
			'isabel_brison',
			'iseulde',
			'ismail0071',
			'isotropic',
			'itsroy69',
			'itsyash1421',
			'iulia-cazan',
			'ivanbachev',
			'iworks',
			'jabe',
			'jabir20',
			'jacobcassidy',
			'jadavsanjay',
			'james-roberts',
			'jamesbregenzer',
			'jamesgiroux',
			'jameskoster',
			'jarekmorawski',
			'jarodortegaaraya',
			'jason_the_adams',
			'jasonkytros',
			'jaspercck',
			'javiercasares',
			'jaz_on',
			'jcnetsys',
			'jdahir0789',
			'jdeep',
			'jdoubleu',
			'jdwire',
			'jdy68',
			'jeffpaul',
			'jeherve',
			'jeremyfelt',
			'jeryj',
			'jessedyck',
			'jf1994',
			'jfacemyer',
			'jhmonroe',
			'jhtjards',
			'jigar9998',
			'jigarkahar',
			'jillro',
			'jimnelin',
			'jmarx75',
			'jmdodd',
			'joedolson',
			'joefusco',
			'joehoyle',
			'joemcgill',
			'joen',
			'joezappie',
			'johnbillion',
			'johnjago',
			'johnjamesjacoby',
			'johnstonphilip',
			'johnwatkins0',
			'jojo256',
			'jomonthomaslobo1',
			'jonsurrell',
			'joppuyo',
			'jorbin',
			'jordesign',
			'jorge1017',
			'jorgefilipecosta',
			'josephscott',
			'josevarghese',
			'joshualipstone',
			'josvelasco',
			'joyously',
			'jrf',
			'jsmansart',
			'jsnajdr',
			'jtquip88',
			'juanfra',
			'juanmaguitar',
			'julianoe',
			'juliobox',
			'junaidkbr',
			'justlevine',
			'jyb1603',
			'kabir93',
			'kaelansmith',
			'kallyansin',
			'kapilpaul',
			'karinchristen',
			'karl94',
			'karmatosed',
			'karolmanijak',
			'karthickmurugan',
			'karthikeya01',
			'kasparsd',
			'kausaralm',
			'kbat82',
			'kelvinballoo',
			'keoshi',
			'khoipro',
			'khokansardar',
			'khushdoms',
			'khushi1501',
			'khushipatel15',
			'kirasong',
			'kittmedia',
			'kjellr',
			'kjoyner',
			'kkeerthiprabhu',
			'kkmuffme',
			'kmurphyzuora',
			'knutsp',
			'kpapazov',
			'kraftbj',
			'kraftner',
			'kristastevens',
			'krokodok',
			'krupajnanda',
			'krupalpanchal',
			'l0id',
			'lakshyajeet',
			'lancewillett',
			'landwire',
			'lapsrj',
			'lasacco',
			'laurisaarni',
			'lbones',
			'leaprvt',
			'leedxw',
			'leemon',
			'leogg',
			'levinbaria',
			'lgersman',
			'lidarroy',
			'liviopv',
			'lobsangw',
			'louischan',
			'louiswol94',
			'lsarsfield',
			'lstraczynski',
			'luigipulcini',
			'luisherranz',
			'luismulinari',
			'lukasfritzedev',
			'lukecarbis',
			'lumiblog',
			'luminuu',
			'm1r0',
			'mabfahad',
			'maccyd',
			'madhavishah01',
			'madhavraj',
			'madtownlems',
			'magaliechetrit',
			'mai21',
			'maksvi',
			'malayladu',
			'malgra',
			'malt3',
			'maltfield',
			'mamaduka',
			'man4toman',
			'manhar',
			'manhphucofficial',
			'manishxdp',
			'manzoorwanijk',
			'mapk',
			'marc4',
			'marian1',
			'marianne38',
			'marineevain',
			'markjaquith',
			'markoserb',
			'marybaum',
			'masteradhoc',
			'masum52',
			'mathiaspeguet',
			'mathijsvdbeek',
			'matt',
			'matteoenna',
			'mattmiklic',
			'mattshaw',
			'matveb',
			'maulikmakwana2008',
			'maverick3x6',
			'maximumsoftware',
			'maxschmeling',
			'mayanktripathi32',
			'mayur8991',
			'mbigul',
			'mciampini',
			'mcsf',
			'mdibrahimk48',
			'meher',
			'mehrazmorshed',
			'melchoyce',
			'metodiew',
			'migueluy',
			'mikachan',
			'mikejolley',
			'mikinc860',
			'mimitips',
			'mindctrl',
			'miqrogroove',
			'mirmpro',
			'mkrndmane',
			'mlaetitia',
			'mmaattiiaass',
			'mmcalister',
			'mmorris8',
			'mmtr86',
			'mobarak',
			'mohamedahamed',
			'mohitbsf',
			'mohitdadhich10',
			'mohkatz',
			'mokshasharmila13',
			'monarobase',
			'monzuralam',
			'mosescursor',
			'motylanogha',
			'mreishus',
			'mrfoxtalbot',
			'mrwweb',
			'mte90',
			'mtias',
			'muddassirnasim',
			'mukesh27',
			'multidots1896',
			'munirkamal',
			'muryam',
			'mustafabharmal',
			'mydesign78',
			'mywp459',
			'nacin',
			'naissvr',
			'namankhare',
			'nanisamireddy',
			'narenin',
			'nareshbheda',
			'nateallen',
			'navi161',
			'nazmul111',
			'ndiego',
			'nekojonez',
			'nendeb55',
			'neo2k23',
			'nerrad',
			'netweb',
			'nickfmc',
			'nicmare',
			'nidhidhandhukiya',
			'nikitasolanki1812',
			'nikunj8866',
			'nilambar',
			'nimeshatxecurify',
			'ninomiho',
			'ninos-ego',
			'niravsherasiya7707',
			'nishantkapadiya',
			'noahtallen',
			'noisysocks',
			'noruzzaman',
			'nrqsnchz',
			'ntsekouras',
			'nyiriland',
			'oandregal',
			'obenland',
			'obliviousharmony',
			'ocean90',
			'octotoot',
			'oglekler',
			'olmostblue',
			'onemaggie',
			'onuro',
			'opr18',
			'opurockey',
			'ottok',
			'ov3rfly',
			'ovidiu-galatan',
			'ovidiul',
			'owolter',
			'ozgursar',
			'oztaser',
			'paaljoachim',
			'pagelab',
			'palak678',
			'paragjethva',
			'paragoninitiativeenterprises',
			'parinpanjari',
			'parthvataliya',
			'patricedefago',
			'patricia70',
			'patrickwclanden',
			'paulkevan',
			'pavanpatil1',
			'pavelevap',
			'pbearne',
			'pbiron',
			'penelopeadrian',
			'pento',
			'pers',
			'peter8nss',
			'peterwilsoncc',
			'petitphp',
			'philhoyt',
			'philipmjackson',
			'phpbits',
			'pierrelannoy',
			'piyushpatel123',
			'plari',
			'pmbaldha',
			'pmbs',
			'poena',
			'poligilad',
			'pooja-n',
			'pooja1210',
			'poojapadamad',
			'porg',
			'power2009',
			'prajapatvishnu',
			'pranavyeole',
			'pranjalpratapsingh',
			'prasadkarmalkar',
			'prathameshbhagat1511',
			'pratik-jain',
			'pratiklondhe',
			'pratiknawkar94',
			'presskopp',
			'presstoke',
			'priethor',
			'priyankagusani',
			'provenself',
			'psorensen',
			'psykro',
			'qhaensler',
			'r1k0',
			'rachid84',
			'racinesdesign',
			'rafa8626',
			'rafaeldella',
			'rafaelkr',
			'raftaar1191',
			'rahan00123',
			'rahmohn',
			'rahulsprajapati',
			'rahultank',
			'rajanit2000',
			'rajdiptank111',
			'ralphonz',
			'ralucastn',
			'ramonopoly',
			'ravichudasama01',
			'ravigadhiyawp',
			'ravikhadka',
			'rcorrales',
			'rcrdortiz',
			'rcreators',
			'realloc',
			'rebeensarbast',
			'redsweater',
			'rejaulalomkhan',
			'renathoc',
			'retnonindya',
			'retrofox',
			'riadev',
			'rianrietveld',
			'richtabor',
			'ricjcs',
			'riko910',
			'rilwis',
			'rinkalpagdar',
			'rishabhwp',
			'rishavdutta',
			'rishit30g',
			'rlucian',
			'robinvandervliet',
			'rodrigosprimo',
			'rollybueno',
			'romainmrhenry',
			'ronya4927',
			'roshniahuja14',
			'royhridoy',
			'roytanck',
			'ruba1956',
			'rutujaparamane2004',
			'rutviksavsani',
			'ryelle',
			'ryokuhi',
			'sabernhardt',
			'sachinrajcp123',
			'safedawn',
			'sagardeshmukh',
			'sagarjadhav',
			'sagarladani',
			'sageth',
			'sainathpoojary',
			'sajib1223',
			'sajjad67',
			'sakshamsharma5',
			'salcode',
			'samiamnot',
			'samueljseay',
			'sanayasir',
			'sanchothefat',
			'sandeepdahiya',
			'sandipmaurya2611',
			'sandipsinh007',
			'sanketparmar',
			'santosguillamot',
			'saranshsinha',
			'saratheonline',
			'sarayourfriend',
			'sarthak8858',
			'saurabhdhariwal',
			'saxonafletcher',
			'sc0ttkclark',
			'scribu',
			'scruffian',
			'se02vas',
			'seanwei',
			'senadir',
			'sergeybiryukov',
			'sergiomdgomes',
			'sfougnier',
			'sh4lin',
			'shadyvb',
			'shailu25',
			'shanemac10',
			'shatrumyatra',
			'shaunandrews',
			'shekh0109',
			'shekharnwagh',
			'shibleemehdi',
			'shimotomoki',
			'showravhasan',
			'shraboni',
			'shreya0shrivastava',
			'shubhtoy',
			'shuvo586',
			'sidhanttomar',
			'sidharthpandita',
			'silaskoehler',
			'siliconforks',
			'silvanarnet',
			'simison',
			'sippis',
			'sirlouen',
			'skithund',
			'skorasaurus',
			'sky_76',
			'skylarkcob',
			'slieptsov',
			'slrslr',
			'smithjw1',
			'smrubenstein',
			'snilesh',
			'soean',
			'solankisoftware',
			'sonaliprajapati',
			'sophiecaperaa',
			'sourabhjain',
			'sourav08',
			'soyebsalar01',
			'spacedmonkey',
			'spencerfinnell',
			'spiraltee',
			'staggerlee',
			'stefanfisk',
			'stefanvelthuys',
			'stevejburge',
			'stoyangeorgiev',
			'strarsis',
			'studiomondiale',
			'styankov',
			'subrataemfluence',
			'suhan2411',
			'suhel5047',
			'sukhendu2002',
			'sumitbagthariya16',
			'sumitsingh',
			'sunilkumarthz',
			'sunyatasattva',
			'superdav42',
			'supernovia',
			'susiyanti',
			'swanandm',
			'swissspidy',
			'swoyamjeetcodes',
			'szepeviktor',
			'tainacan',
			'takshil',
			'talldanwp',
			'tanbirali',
			'tanvirul',
			'tfrommen',
			'thehenridev',
			'thejaymo',
			'thelmachido',
			'themearts',
			'themes-1',
			'themightymo',
			'threadi',
			'timhibberd',
			'timothyblynjacobs',
			'timse201',
			'timwright12',
			'tinkerbelly',
			'tobiasbg',
			'tomauger',
			'trickster301',
			'triple0t',
			'truptikanzariya',
			'tule',
			'tusharaddweb',
			'tusharbharti',
			'twvania',
			'tyxla',
			'ugyensupport',
			'umeshnevase',
			'umeshsinghin',
			'up1512001',
			'utsavladani',
			'vaibhavsweb',
			'valentingrenier',
			'valer1e',
			'vanhoucke',
			'vanonsopensource',
			'vascobaiao',
			'verygoode',
			'vgnavada',
			'vheemstra',
			'vietcgi',
			'vincentbreton',
			'vipulgupta003',
			'viralsampat',
			'vishalkakadiya',
			'vishitshah',
			'vishnuprajapat',
			'voboghure',
			'vrishabhsk',
			'vyatka',
			'vybiral',
			'waqassafdar',
			'webdados',
			'webmandesign',
			'wedgemaster',
			'welcher',
			'westonruter',
			'wfmattr',
			'whiteshadow01',
			'wilcosky',
			'wildworks',
			'winsleyj',
			'wiuempe',
			'wolf45',
			'wongjn',
			'wooxperto',
			'wpexplorer',
			'wplmillet',
			'wprashed',
			'wpsoul',
			'wraithkenny',
			'x-raym',
			'xate',
			'xavilc',
			'xknown',
			'xristos3490',
			'xwolf',
			'yagniksangani',
			'yashjawale',
			'yasunocco',
			'yguyon',
			'yogeshbhutkar',
			'youknowriad',
			'ytfeldrawkcab',
			'yusufmudagal',
			'zieladam',
			'zodiac1978',
			'zoe20',
			'zoonini',
			'zunaid321',
			'zuveria',
		];
	}

	public function external_libraries() {
		return [
			[ 'Babel Polyfill', 'https://babeljs.io/docs/babel-polyfill' ],
			[ 'Backbone.js', 'https://backbonejs.org/' ],
			[ 'Class POP3', 'https://squirrelmail.org/' ],
			[ 'clipboard.js', 'https://clipboardjs.com/' ],
			[ 'Closest', 'https://github.com/jonathantneal/closest' ],
			[ 'CodeMirror', 'https://codemirror.net/' ],
			[ 'Color Animations', 'https://plugins.jquery.com/color/' ],
			[ 'getID3()', 'https://www.getid3.org/' ],
			[ 'FormData', 'https://github.com/jimmywarting/FormData' ],
			[ 'Horde Text Diff', 'https://pear.horde.org/' ],
			[ 'hoverIntent', 'https://github.com/briancherne/jquery-hoverIntent' ],
			[ 'imgAreaSelect', 'https://github.com/odyniec/imgareaselect' ],
			[ 'Iris', 'https://github.com/Automattic/Iris' ],
			[ 'jQuery', 'https://jquery.com/' ],
			[ 'jQuery UI', 'https://jqueryui.com/' ],
			[ 'jQuery Hotkeys', 'https://github.com/mathusiast/jquery.hotkeys' ],
			[ 'jQuery serializeObject', 'https://benalman.com/projects/jquery-misc-plugins/' ],
			[ 'jQuery.query', 'https://plugins.jquery.com/query-object/' ],
			[ 'jQuery.suggest', 'https://github.com/pvulgaris/jquery.suggest' ],
			[ 'jQuery UI Touch Punch', 'https://github.com/furf/jquery-ui-touch-punch' ],
			[ 'json2', 'https://github.com/douglascrockford/JSON-js' ],
			[ 'Lodash', 'https://lodash.com/' ],
			[ 'Masonry', 'https://masonry.desandro.com/' ],
			[ 'MediaElement.js', 'https://www.mediaelementjs.com/' ],
			[ 'Moment', 'https://momentjs.com/' ],
			[ 'PclZip', 'https://www.phpconcept.net/' ],
			[ 'PemFTP', 'https://www.phpclasses.org/package/1743-PHP-FTP-client-in-pure-PHP.html' ],
			[ 'phpass', 'https://www.openwall.com/phpass/' ],
			[ 'PHPMailer', 'https://github.com/PHPMailer/PHPMailer' ],
			[ 'Plupload', 'https://www.plupload.com/' ],
			[ 'random_compat', 'https://github.com/paragonie/random_compat' ],
			[ 'React', 'https://react.dev/' ],
			[ 'Redux', 'https://redux.js.org/' ],
			[ 'Requests', 'https://requests.ryanmccue.info/' ],
			[ 'SimplePie', 'https://simplepie.org/' ],
			[ 'The Incutio XML-RPC Library', 'https://code.google.com/archive/p/php-ixr/' ],
			[ 'Thickbox', 'https://codylindley.com/thickbox/' ],
			[ 'TinyMCE', 'https://www.tiny.cloud/' ],
			[ 'Twemoji', 'https://github.com/twitter/twemoji' ],
			[ 'Underscore.js', 'https://underscorejs.org/' ],
			[ 'whatwg-fetch', 'https://github.com/JakeChampion/fetch' ],
			[ 'zxcvbn', 'https://github.com/dropbox/zxcvbn' ],
		];
	}
}
